"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CClientMetrics_ClientBootstrap_RequestInfo(_message.Message):

    ORIGINAL_HOSTNAME_FIELD_NUMBER: _builtins.int
    ACTUAL_HOSTNAME_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    BASE_NAME_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    STATUS_CODE_FIELD_NUMBER: _builtins.int
    ADDRESS_OF_REQUEST_URL_FIELD_NUMBER: _builtins.int
    RESPONSE_TIME_MS_FIELD_NUMBER: _builtins.int
    BYTES_RECEIVED_FIELD_NUMBER: _builtins.int
    NUM_RETRIES_FIELD_NUMBER: _builtins.int
    original_hostname: _builtins.str
    actual_hostname: _builtins.str
    path: _builtins.str
    base_name: _builtins.str
    success: _builtins.bool
    status_code: _builtins.int
    address_of_request_url: _builtins.str
    response_time_ms: _builtins.int
    bytes_received: _builtins.int
    num_retries: _builtins.int
    def __init__(
        self,
        *,
        original_hostname: _builtins.str | None = ...,
        actual_hostname: _builtins.str | None = ...,
        path: _builtins.str | None = ...,
        base_name: _builtins.str | None = ...,
        success: _builtins.bool | None = ...,
        status_code: _builtins.int | None = ...,
        address_of_request_url: _builtins.str | None = ...,
        response_time_ms: _builtins.int | None = ...,
        bytes_received: _builtins.int | None = ...,
        num_retries: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["actual_hostname", b"actual_hostname", "address_of_request_url", b"address_of_request_url", "base_name", b"base_name", "bytes_received", b"bytes_received", "num_retries", b"num_retries", "original_hostname", b"original_hostname", "path", b"path", "response_time_ms", b"response_time_ms", "status_code", b"status_code", "success", b"success"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actual_hostname", b"actual_hostname", "address_of_request_url", b"address_of_request_url", "base_name", b"base_name", "bytes_received", b"bytes_received", "num_retries", b"num_retries", "original_hostname", b"original_hostname", "path", b"path", "response_time_ms", b"response_time_ms", "status_code", b"status_code", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ClientBootstrap_RequestInfo: _TypeAlias = CClientMetrics_ClientBootstrap_RequestInfo  # noqa: Y015

@_typing.final
class CClientMetrics_ClientBootstrap_Summary(_message.Message):

    LAUNCHER_TYPE_FIELD_NUMBER: _builtins.int
    STEAM_REALM_FIELD_NUMBER: _builtins.int
    BETA_NAME_FIELD_NUMBER: _builtins.int
    DOWNLOAD_COMPLETED_FIELD_NUMBER: _builtins.int
    TOTAL_TIME_MS_FIELD_NUMBER: _builtins.int
    MANIFEST_REQUESTS_FIELD_NUMBER: _builtins.int
    PACKAGE_REQUESTS_FIELD_NUMBER: _builtins.int
    launcher_type: _builtins.int
    steam_realm: _builtins.int
    beta_name: _builtins.str
    download_completed: _builtins.bool
    total_time_ms: _builtins.int
    @_builtins.property
    def manifest_requests(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ClientBootstrap_RequestInfo]: ...
    @_builtins.property
    def package_requests(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ClientBootstrap_RequestInfo]: ...
    def __init__(
        self,
        *,
        launcher_type: _builtins.int | None = ...,
        steam_realm: _builtins.int | None = ...,
        beta_name: _builtins.str | None = ...,
        download_completed: _builtins.bool | None = ...,
        total_time_ms: _builtins.int | None = ...,
        manifest_requests: _abc.Iterable[Global___CClientMetrics_ClientBootstrap_RequestInfo] | None = ...,
        package_requests: _abc.Iterable[Global___CClientMetrics_ClientBootstrap_RequestInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["beta_name", b"beta_name", "download_completed", b"download_completed", "launcher_type", b"launcher_type", "steam_realm", b"steam_realm", "total_time_ms", b"total_time_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["beta_name", b"beta_name", "download_completed", b"download_completed", "launcher_type", b"launcher_type", "manifest_requests", b"manifest_requests", "package_requests", b"package_requests", "steam_realm", b"steam_realm", "total_time_ms", b"total_time_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ClientBootstrap_Summary: _TypeAlias = CClientMetrics_ClientBootstrap_Summary  # noqa: Y015

@_typing.final
class CClientMetrics_ContentDownloadResponse_Counts(_message.Message):

    CLASS_100_FIELD_NUMBER: _builtins.int
    CLASS_200_FIELD_NUMBER: _builtins.int
    CLASS_300_FIELD_NUMBER: _builtins.int
    CLASS_400_FIELD_NUMBER: _builtins.int
    CLASS_500_FIELD_NUMBER: _builtins.int
    NO_RESPONSE_FIELD_NUMBER: _builtins.int
    CLASS_UNKNOWN_FIELD_NUMBER: _builtins.int
    class_100: _builtins.int
    class_200: _builtins.int
    class_300: _builtins.int
    class_400: _builtins.int
    class_500: _builtins.int
    no_response: _builtins.int
    class_unknown: _builtins.int
    def __init__(
        self,
        *,
        class_100: _builtins.int | None = ...,
        class_200: _builtins.int | None = ...,
        class_300: _builtins.int | None = ...,
        class_400: _builtins.int | None = ...,
        class_500: _builtins.int | None = ...,
        no_response: _builtins.int | None = ...,
        class_unknown: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["class_100", b"class_100", "class_200", b"class_200", "class_300", b"class_300", "class_400", b"class_400", "class_500", b"class_500", "class_unknown", b"class_unknown", "no_response", b"no_response"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["class_100", b"class_100", "class_200", b"class_200", "class_300", b"class_300", "class_400", b"class_400", "class_500", b"class_500", "class_unknown", b"class_unknown", "no_response", b"no_response"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ContentDownloadResponse_Counts: _TypeAlias = CClientMetrics_ContentDownloadResponse_Counts  # noqa: Y015

@_typing.final
class CClientMetrics_ContentDownloadResponse_HostCounts(_message.Message):

    HOSTNAME_FIELD_NUMBER: _builtins.int
    SOURCE_TYPE_FIELD_NUMBER: _builtins.int
    COUNTS_FIELD_NUMBER: _builtins.int
    hostname: _builtins.str
    source_type: _builtins.int
    @_builtins.property
    def counts(self) -> Global___CClientMetrics_ContentDownloadResponse_Counts: ...
    def __init__(
        self,
        *,
        hostname: _builtins.str | None = ...,
        source_type: _builtins.int | None = ...,
        counts: Global___CClientMetrics_ContentDownloadResponse_Counts | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["counts", b"counts", "hostname", b"hostname", "source_type", b"source_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["counts", b"counts", "hostname", b"hostname", "source_type", b"source_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ContentDownloadResponse_HostCounts: _TypeAlias = CClientMetrics_ContentDownloadResponse_HostCounts  # noqa: Y015

@_typing.final
class CClientMetrics_ContentDownloadResponse_Hosts(_message.Message):

    HOSTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hosts(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ContentDownloadResponse_HostCounts]: ...
    def __init__(
        self,
        *,
        hosts: _abc.Iterable[Global___CClientMetrics_ContentDownloadResponse_HostCounts] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hosts", b"hosts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ContentDownloadResponse_Hosts: _TypeAlias = CClientMetrics_ContentDownloadResponse_Hosts  # noqa: Y015
