"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Offline_Ticket(_message.Message):

    ENCRYPTED_TICKET_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    KDF1_FIELD_NUMBER: _builtins.int
    SALT1_FIELD_NUMBER: _builtins.int
    KDF2_FIELD_NUMBER: _builtins.int
    SALT2_FIELD_NUMBER: _builtins.int
    encrypted_ticket: _builtins.bytes
    signature: _builtins.bytes
    kdf1: _builtins.int
    salt1: _builtins.bytes
    kdf2: _builtins.int
    salt2: _builtins.bytes
    def __init__(
        self,
        *,
        encrypted_ticket: _builtins.bytes | None = ...,
        signature: _builtins.bytes | None = ...,
        kdf1: _builtins.int | None = ...,
        salt1: _builtins.bytes | None = ...,
        kdf2: _builtins.int | None = ...,
        salt2: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encrypted_ticket", b"encrypted_ticket", "kdf1", b"kdf1", "kdf2", b"kdf2", "salt1", b"salt1", "salt2", b"salt2", "signature", b"signature"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encrypted_ticket", b"encrypted_ticket", "kdf1", b"kdf1", "kdf2", b"kdf2", "salt1", b"salt1", "salt2", b"salt2", "signature", b"signature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Offline_Ticket: _TypeAlias = Offline_Ticket  # noqa: Y015
