"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CMsgClientLBSSetScore(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    UPLOAD_SCORE_METHOD_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    leaderboard_id: _builtins.int
    score: _builtins.int
    details: _builtins.bytes
    upload_score_method: _builtins.int
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        leaderboard_id: _builtins.int | None = ...,
        score: _builtins.int | None = ...,
        details: _builtins.bytes | None = ...,
        upload_score_method: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "details", b"details", "leaderboard_id", b"leaderboard_id", "score", b"score", "upload_score_method", b"upload_score_method"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "details", b"details", "leaderboard_id", b"leaderboard_id", "score", b"score", "upload_score_method", b"upload_score_method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSSetScore: _TypeAlias = CMsgClientLBSSetScore  # noqa: Y015

@_typing.final
class CMsgClientLBSSetScoreResponse(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ENTRY_COUNT_FIELD_NUMBER: _builtins.int
    SCORE_CHANGED_FIELD_NUMBER: _builtins.int
    GLOBAL_RANK_PREVIOUS_FIELD_NUMBER: _builtins.int
    GLOBAL_RANK_NEW_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    leaderboard_entry_count: _builtins.int
    score_changed: _builtins.bool
    global_rank_previous: _builtins.int
    global_rank_new: _builtins.int
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
        leaderboard_entry_count: _builtins.int | None = ...,
        score_changed: _builtins.bool | None = ...,
        global_rank_previous: _builtins.int | None = ...,
        global_rank_new: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "global_rank_new", b"global_rank_new", "global_rank_previous", b"global_rank_previous", "leaderboard_entry_count", b"leaderboard_entry_count", "score_changed", b"score_changed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "global_rank_new", b"global_rank_new", "global_rank_previous", b"global_rank_previous", "leaderboard_entry_count", b"leaderboard_entry_count", "score_changed", b"score_changed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSSetScoreResponse: _TypeAlias = CMsgClientLBSSetScoreResponse  # noqa: Y015

@_typing.final
class CMsgClientLBSSetUGC(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ID_FIELD_NUMBER: _builtins.int
    UGC_ID_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    leaderboard_id: _builtins.int
    ugc_id: _builtins.int
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        leaderboard_id: _builtins.int | None = ...,
        ugc_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "leaderboard_id", b"leaderboard_id", "ugc_id", b"ugc_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "leaderboard_id", b"leaderboard_id", "ugc_id", b"ugc_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSSetUGC: _TypeAlias = CMsgClientLBSSetUGC  # noqa: Y015

@_typing.final
class CMsgClientLBSSetUGCResponse(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSSetUGCResponse: _TypeAlias = CMsgClientLBSSetUGCResponse  # noqa: Y015

@_typing.final
class CMsgClientLBSFindOrCreateLB(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    LEADERBOARD_SORT_METHOD_FIELD_NUMBER: _builtins.int
    LEADERBOARD_DISPLAY_TYPE_FIELD_NUMBER: _builtins.int
    CREATE_IF_NOT_FOUND_FIELD_NUMBER: _builtins.int
    LEADERBOARD_NAME_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    leaderboard_sort_method: _builtins.int
    leaderboard_display_type: _builtins.int
    create_if_not_found: _builtins.bool
    leaderboard_name: _builtins.str
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        leaderboard_sort_method: _builtins.int | None = ...,
        leaderboard_display_type: _builtins.int | None = ...,
        create_if_not_found: _builtins.bool | None = ...,
        leaderboard_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "create_if_not_found", b"create_if_not_found", "leaderboard_display_type", b"leaderboard_display_type", "leaderboard_name", b"leaderboard_name", "leaderboard_sort_method", b"leaderboard_sort_method"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "create_if_not_found", b"create_if_not_found", "leaderboard_display_type", b"leaderboard_display_type", "leaderboard_name", b"leaderboard_name", "leaderboard_sort_method", b"leaderboard_sort_method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSFindOrCreateLB: _TypeAlias = CMsgClientLBSFindOrCreateLB  # noqa: Y015

@_typing.final
class CMsgClientLBSFindOrCreateLBResponse(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ID_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ENTRY_COUNT_FIELD_NUMBER: _builtins.int
    LEADERBOARD_SORT_METHOD_FIELD_NUMBER: _builtins.int
    LEADERBOARD_DISPLAY_TYPE_FIELD_NUMBER: _builtins.int
    LEADERBOARD_NAME_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    leaderboard_id: _builtins.int
    leaderboard_entry_count: _builtins.int
    leaderboard_sort_method: _builtins.int
    leaderboard_display_type: _builtins.int
    leaderboard_name: _builtins.str
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
        leaderboard_id: _builtins.int | None = ...,
        leaderboard_entry_count: _builtins.int | None = ...,
        leaderboard_sort_method: _builtins.int | None = ...,
        leaderboard_display_type: _builtins.int | None = ...,
        leaderboard_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "leaderboard_display_type", b"leaderboard_display_type", "leaderboard_entry_count", b"leaderboard_entry_count", "leaderboard_id", b"leaderboard_id", "leaderboard_name", b"leaderboard_name", "leaderboard_sort_method", b"leaderboard_sort_method"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "leaderboard_display_type", b"leaderboard_display_type", "leaderboard_entry_count", b"leaderboard_entry_count", "leaderboard_id", b"leaderboard_id", "leaderboard_name", b"leaderboard_name", "leaderboard_sort_method", b"leaderboard_sort_method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSFindOrCreateLBResponse: _TypeAlias = CMsgClientLBSFindOrCreateLBResponse  # noqa: Y015

@_typing.final
class CMsgClientLBSGetLBEntries(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ID_FIELD_NUMBER: _builtins.int
    RANGE_START_FIELD_NUMBER: _builtins.int
    RANGE_END_FIELD_NUMBER: _builtins.int
    LEADERBOARD_DATA_REQUEST_FIELD_NUMBER: _builtins.int
    STEAMIDS_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    leaderboard_id: _builtins.int
    range_start: _builtins.int
    range_end: _builtins.int
    leaderboard_data_request: _builtins.int
    @_builtins.property
    def steamids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        leaderboard_id: _builtins.int | None = ...,
        range_start: _builtins.int | None = ...,
        range_end: _builtins.int | None = ...,
        leaderboard_data_request: _builtins.int | None = ...,
        steamids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "leaderboard_data_request", b"leaderboard_data_request", "leaderboard_id", b"leaderboard_id", "range_end", b"range_end", "range_start", b"range_start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "leaderboard_data_request", b"leaderboard_data_request", "leaderboard_id", b"leaderboard_id", "range_end", b"range_end", "range_start", b"range_start", "steamids", b"steamids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSGetLBEntries: _TypeAlias = CMsgClientLBSGetLBEntries  # noqa: Y015

@_typing.final
class CMsgClientLBSGetLBEntriesResponse(_message.Message):

    @_typing.final
    class Entry(_message.Message):

        STEAM_ID_USER_FIELD_NUMBER: _builtins.int
        GLOBAL_RANK_FIELD_NUMBER: _builtins.int
        SCORE_FIELD_NUMBER: _builtins.int
        DETAILS_FIELD_NUMBER: _builtins.int
        UGC_ID_FIELD_NUMBER: _builtins.int
        steam_id_user: _builtins.int
        global_rank: _builtins.int
        score: _builtins.int
        details: _builtins.bytes
        ugc_id: _builtins.int
        def __init__(
            self,
            *,
            steam_id_user: _builtins.int | None = ...,
            global_rank: _builtins.int | None = ...,
            score: _builtins.int | None = ...,
            details: _builtins.bytes | None = ...,
            ugc_id: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "global_rank", b"global_rank", "score", b"score", "steam_id_user", b"steam_id_user", "ugc_id", b"ugc_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "global_rank", b"global_rank", "score", b"score", "steam_id_user", b"steam_id_user", "ugc_id", b"ugc_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ERESULT_FIELD_NUMBER: _builtins.int
    LEADERBOARD_ENTRY_COUNT_FIELD_NUMBER: _builtins.int
    ENTRIES_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    leaderboard_entry_count: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientLBSGetLBEntriesResponse.Entry]: ...
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
        leaderboard_entry_count: _builtins.int | None = ...,
        entries: _abc.Iterable[Global___CMsgClientLBSGetLBEntriesResponse.Entry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "leaderboard_entry_count", b"leaderboard_entry_count"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "eresult", b"eresult", "leaderboard_entry_count", b"leaderboard_entry_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientLBSGetLBEntriesResponse: _TypeAlias = CMsgClientLBSGetLBEntriesResponse  # noqa: Y015
