"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import steam.protobufs.steammessages_base_pb2 as _steammessages_base_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CCredentials_GetSteamGuardDetails_Request(_message.Message):

    WEBCOOKIE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MINIMUM_WANTED_FIELD_NUMBER: _builtins.int
    DEPRECATED_IPADDRESS_FIELD_NUMBER: _builtins.int
    IP_ADDRESS_FIELD_NUMBER: _builtins.int
    webcookie: _builtins.str
    timestamp_minimum_wanted: _builtins.int
    deprecated_ipaddress: _builtins.int
    @_builtins.property
    def ip_address(self) -> _steammessages_base_pb2.CMsgIPAddress: ...
    def __init__(
        self,
        *,
        webcookie: _builtins.str | None = ...,
        timestamp_minimum_wanted: _builtins.int | None = ...,
        deprecated_ipaddress: _builtins.int | None = ...,
        ip_address: _steammessages_base_pb2.CMsgIPAddress | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deprecated_ipaddress", b"deprecated_ipaddress", "ip_address", b"ip_address", "timestamp_minimum_wanted", b"timestamp_minimum_wanted", "webcookie", b"webcookie"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deprecated_ipaddress", b"deprecated_ipaddress", "ip_address", b"ip_address", "timestamp_minimum_wanted", b"timestamp_minimum_wanted", "webcookie", b"webcookie"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_GetSteamGuardDetails_Request: _TypeAlias = CCredentials_GetSteamGuardDetails_Request  # noqa: Y015

@_typing.final
class CCredentials_GetSteamGuardDetails_Response(_message.Message):

    @_typing.final
    class SessionData(_message.Message):

        MACHINE_ID_FIELD_NUMBER: _builtins.int
        MACHINE_NAME_USERCHOSEN_FIELD_NUMBER: _builtins.int
        TIMESTAMP_MACHINE_STEAMGUARD_ENABLED_FIELD_NUMBER: _builtins.int
        AUTHENTICATION_EXISTS_FROM_GEOLOC_BEFORE_MINTIME_FIELD_NUMBER: _builtins.int
        AUTHENTICATION_EXISTS_FROM_SAME_IP_BEFORE_MINTIME_FIELD_NUMBER: _builtins.int
        PUBLIC_IPV4_FIELD_NUMBER: _builtins.int
        PUBLIC_IP_ADDRESS_FIELD_NUMBER: _builtins.int
        machine_id: _builtins.int
        machine_name_userchosen: _builtins.str
        timestamp_machine_steamguard_enabled: _builtins.int
        authentication_exists_from_geoloc_before_mintime: _builtins.bool
        authentication_exists_from_same_ip_before_mintime: _builtins.bool
        public_ipv4: _builtins.int
        public_ip_address: _builtins.str
        def __init__(
            self,
            *,
            machine_id: _builtins.int | None = ...,
            machine_name_userchosen: _builtins.str | None = ...,
            timestamp_machine_steamguard_enabled: _builtins.int | None = ...,
            authentication_exists_from_geoloc_before_mintime: _builtins.bool | None = ...,
            authentication_exists_from_same_ip_before_mintime: _builtins.bool | None = ...,
            public_ipv4: _builtins.int | None = ...,
            public_ip_address: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["authentication_exists_from_geoloc_before_mintime", b"authentication_exists_from_geoloc_before_mintime", "authentication_exists_from_same_ip_before_mintime", b"authentication_exists_from_same_ip_before_mintime", "machine_id", b"machine_id", "machine_name_userchosen", b"machine_name_userchosen", "public_ip_address", b"public_ip_address", "public_ipv4", b"public_ipv4", "timestamp_machine_steamguard_enabled", b"timestamp_machine_steamguard_enabled"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["authentication_exists_from_geoloc_before_mintime", b"authentication_exists_from_geoloc_before_mintime", "authentication_exists_from_same_ip_before_mintime", b"authentication_exists_from_same_ip_before_mintime", "machine_id", b"machine_id", "machine_name_userchosen", b"machine_name_userchosen", "public_ip_address", b"public_ip_address", "public_ipv4", b"public_ipv4", "timestamp_machine_steamguard_enabled", b"timestamp_machine_steamguard_enabled"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    IS_STEAMGUARD_ENABLED_FIELD_NUMBER: _builtins.int
    TIMESTAMP_STEAMGUARD_ENABLED_FIELD_NUMBER: _builtins.int
    DEPRECATED_MACHINE_NAME_USERCHOSEN_FIELD_NUMBER: _builtins.int
    DEPRECATED_TIMESTAMP_MACHINE_STEAMGUARD_ENABLED_FIELD_NUMBER: _builtins.int
    DEPRECATED_AUTHENTICATION_EXISTS_FROM_GEOLOC_BEFORE_MINTIME_FIELD_NUMBER: _builtins.int
    DEPRECATED_MACHINE_ID_FIELD_NUMBER: _builtins.int
    SESSION_DATA_FIELD_NUMBER: _builtins.int
    IS_TWOFACTOR_ENABLED_FIELD_NUMBER: _builtins.int
    TIMESTAMP_TWOFACTOR_ENABLED_FIELD_NUMBER: _builtins.int
    IS_PHONE_VERIFIED_FIELD_NUMBER: _builtins.int
    is_steamguard_enabled: _builtins.bool
    timestamp_steamguard_enabled: _builtins.int
    deprecated_machine_name_userchosen: _builtins.str
    deprecated_timestamp_machine_steamguard_enabled: _builtins.int
    deprecated_authentication_exists_from_geoloc_before_mintime: _builtins.bool
    deprecated_machine_id: _builtins.int
    is_twofactor_enabled: _builtins.bool
    timestamp_twofactor_enabled: _builtins.int
    is_phone_verified: _builtins.bool
    @_builtins.property
    def session_data(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCredentials_GetSteamGuardDetails_Response.SessionData]: ...
    def __init__(
        self,
        *,
        is_steamguard_enabled: _builtins.bool | None = ...,
        timestamp_steamguard_enabled: _builtins.int | None = ...,
        deprecated_machine_name_userchosen: _builtins.str | None = ...,
        deprecated_timestamp_machine_steamguard_enabled: _builtins.int | None = ...,
        deprecated_authentication_exists_from_geoloc_before_mintime: _builtins.bool | None = ...,
        deprecated_machine_id: _builtins.int | None = ...,
        session_data: _abc.Iterable[Global___CCredentials_GetSteamGuardDetails_Response.SessionData] | None = ...,
        is_twofactor_enabled: _builtins.bool | None = ...,
        timestamp_twofactor_enabled: _builtins.int | None = ...,
        is_phone_verified: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deprecated_authentication_exists_from_geoloc_before_mintime", b"deprecated_authentication_exists_from_geoloc_before_mintime", "deprecated_machine_id", b"deprecated_machine_id", "deprecated_machine_name_userchosen", b"deprecated_machine_name_userchosen", "deprecated_timestamp_machine_steamguard_enabled", b"deprecated_timestamp_machine_steamguard_enabled", "is_phone_verified", b"is_phone_verified", "is_steamguard_enabled", b"is_steamguard_enabled", "is_twofactor_enabled", b"is_twofactor_enabled", "timestamp_steamguard_enabled", b"timestamp_steamguard_enabled", "timestamp_twofactor_enabled", b"timestamp_twofactor_enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deprecated_authentication_exists_from_geoloc_before_mintime", b"deprecated_authentication_exists_from_geoloc_before_mintime", "deprecated_machine_id", b"deprecated_machine_id", "deprecated_machine_name_userchosen", b"deprecated_machine_name_userchosen", "deprecated_timestamp_machine_steamguard_enabled", b"deprecated_timestamp_machine_steamguard_enabled", "is_phone_verified", b"is_phone_verified", "is_steamguard_enabled", b"is_steamguard_enabled", "is_twofactor_enabled", b"is_twofactor_enabled", "session_data", b"session_data", "timestamp_steamguard_enabled", b"timestamp_steamguard_enabled", "timestamp_twofactor_enabled", b"timestamp_twofactor_enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_GetSteamGuardDetails_Response: _TypeAlias = CCredentials_GetSteamGuardDetails_Response  # noqa: Y015

@_typing.final
class CCredentials_ValidateEmailAddress_Request(_message.Message):

    STOKEN_FIELD_NUMBER: _builtins.int
    stoken: _builtins.str
    def __init__(
        self,
        *,
        stoken: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stoken", b"stoken"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stoken", b"stoken"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_ValidateEmailAddress_Request: _TypeAlias = CCredentials_ValidateEmailAddress_Request  # noqa: Y015

@_typing.final
class CCredentials_ValidateEmailAddress_Response(_message.Message):

    WAS_VALIDATED_FIELD_NUMBER: _builtins.int
    was_validated: _builtins.bool
    def __init__(
        self,
        *,
        was_validated: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["was_validated", b"was_validated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["was_validated", b"was_validated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_ValidateEmailAddress_Response: _TypeAlias = CCredentials_ValidateEmailAddress_Response  # noqa: Y015

@_typing.final
class CCredentials_SteamGuardPhishingReport_Request(_message.Message):

    PARAM_STRING_FIELD_NUMBER: _builtins.int
    IPADDRESS_ACTUAL_FIELD_NUMBER: _builtins.int
    param_string: _builtins.str
    ipaddress_actual: _builtins.str
    def __init__(
        self,
        *,
        param_string: _builtins.str | None = ...,
        ipaddress_actual: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ipaddress_actual", b"ipaddress_actual", "param_string", b"param_string"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ipaddress_actual", b"ipaddress_actual", "param_string", b"param_string"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_SteamGuardPhishingReport_Request: _TypeAlias = CCredentials_SteamGuardPhishingReport_Request  # noqa: Y015

@_typing.final
class CCredentials_SteamGuardPhishingReport_Response(_message.Message):

    IPADDRESS_LOGINATTEMPT_FIELD_NUMBER: _builtins.int
    COUNTRYNAME_LOGINATTEMPT_FIELD_NUMBER: _builtins.int
    STATENAME_LOGINATTEMPT_FIELD_NUMBER: _builtins.int
    CITYNAME_LOGINATTEMPT_FIELD_NUMBER: _builtins.int
    IPADDRESS_ACTUAL_FIELD_NUMBER: _builtins.int
    COUNTRYNAME_ACTUAL_FIELD_NUMBER: _builtins.int
    STATENAME_ACTUAL_FIELD_NUMBER: _builtins.int
    CITYNAME_ACTUAL_FIELD_NUMBER: _builtins.int
    STEAMGUARD_CODE_FIELD_NUMBER: _builtins.int
    ipaddress_loginattempt: _builtins.str
    countryname_loginattempt: _builtins.str
    statename_loginattempt: _builtins.str
    cityname_loginattempt: _builtins.str
    ipaddress_actual: _builtins.str
    countryname_actual: _builtins.str
    statename_actual: _builtins.str
    cityname_actual: _builtins.str
    steamguard_code: _builtins.str
    def __init__(
        self,
        *,
        ipaddress_loginattempt: _builtins.str | None = ...,
        countryname_loginattempt: _builtins.str | None = ...,
        statename_loginattempt: _builtins.str | None = ...,
        cityname_loginattempt: _builtins.str | None = ...,
        ipaddress_actual: _builtins.str | None = ...,
        countryname_actual: _builtins.str | None = ...,
        statename_actual: _builtins.str | None = ...,
        cityname_actual: _builtins.str | None = ...,
        steamguard_code: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cityname_actual", b"cityname_actual", "cityname_loginattempt", b"cityname_loginattempt", "countryname_actual", b"countryname_actual", "countryname_loginattempt", b"countryname_loginattempt", "ipaddress_actual", b"ipaddress_actual", "ipaddress_loginattempt", b"ipaddress_loginattempt", "statename_actual", b"statename_actual", "statename_loginattempt", b"statename_loginattempt", "steamguard_code", b"steamguard_code"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cityname_actual", b"cityname_actual", "cityname_loginattempt", b"cityname_loginattempt", "countryname_actual", b"countryname_actual", "countryname_loginattempt", b"countryname_loginattempt", "ipaddress_actual", b"ipaddress_actual", "ipaddress_loginattempt", b"ipaddress_loginattempt", "statename_actual", b"statename_actual", "statename_loginattempt", b"statename_loginattempt", "steamguard_code", b"steamguard_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_SteamGuardPhishingReport_Response: _TypeAlias = CCredentials_SteamGuardPhishingReport_Response  # noqa: Y015

@_typing.final
class CCredentials_LastCredentialChangeTime_Request(_message.Message):

    USER_CHANGES_ONLY_FIELD_NUMBER: _builtins.int
    user_changes_only: _builtins.bool
    def __init__(
        self,
        *,
        user_changes_only: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user_changes_only", b"user_changes_only"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_changes_only", b"user_changes_only"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_LastCredentialChangeTime_Request: _TypeAlias = CCredentials_LastCredentialChangeTime_Request  # noqa: Y015

@_typing.final
class CCredentials_LastCredentialChangeTime_Response(_message.Message):

    TIMESTAMP_LAST_PASSWORD_CHANGE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_LAST_EMAIL_CHANGE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_LAST_PASSWORD_RESET_FIELD_NUMBER: _builtins.int
    timestamp_last_password_change: _builtins.int
    timestamp_last_email_change: _builtins.int
    timestamp_last_password_reset: _builtins.int
    def __init__(
        self,
        *,
        timestamp_last_password_change: _builtins.int | None = ...,
        timestamp_last_email_change: _builtins.int | None = ...,
        timestamp_last_password_reset: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp_last_email_change", b"timestamp_last_email_change", "timestamp_last_password_change", b"timestamp_last_password_change", "timestamp_last_password_reset", b"timestamp_last_password_reset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timestamp_last_email_change", b"timestamp_last_email_change", "timestamp_last_password_change", b"timestamp_last_password_change", "timestamp_last_password_reset", b"timestamp_last_password_reset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_LastCredentialChangeTime_Response: _TypeAlias = CCredentials_LastCredentialChangeTime_Response  # noqa: Y015

@_typing.final
class CCredentials_GetAccountAuthSecret_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_GetAccountAuthSecret_Request: _TypeAlias = CCredentials_GetAccountAuthSecret_Request  # noqa: Y015

@_typing.final
class CCredentials_GetAccountAuthSecret_Response(_message.Message):

    SECRET_ID_FIELD_NUMBER: _builtins.int
    SECRET_FIELD_NUMBER: _builtins.int
    secret_id: _builtins.int
    secret: _builtins.bytes
    def __init__(
        self,
        *,
        secret_id: _builtins.int | None = ...,
        secret: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["secret", b"secret", "secret_id", b"secret_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["secret", b"secret", "secret_id", b"secret_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCredentials_GetAccountAuthSecret_Response: _TypeAlias = CCredentials_GetAccountAuthSecret_Response  # noqa: Y015
