"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CMsgClientGetUserStats(_message.Message):

    GAME_ID_FIELD_NUMBER: _builtins.int
    CRC_STATS_FIELD_NUMBER: _builtins.int
    SCHEMA_LOCAL_VERSION_FIELD_NUMBER: _builtins.int
    STEAM_ID_FOR_USER_FIELD_NUMBER: _builtins.int
    game_id: _builtins.int
    crc_stats: _builtins.int
    schema_local_version: _builtins.int
    steam_id_for_user: _builtins.int
    def __init__(
        self,
        *,
        game_id: _builtins.int | None = ...,
        crc_stats: _builtins.int | None = ...,
        schema_local_version: _builtins.int | None = ...,
        steam_id_for_user: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "game_id", b"game_id", "schema_local_version", b"schema_local_version", "steam_id_for_user", b"steam_id_for_user"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "game_id", b"game_id", "schema_local_version", b"schema_local_version", "steam_id_for_user", b"steam_id_for_user"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientGetUserStats: _TypeAlias = CMsgClientGetUserStats  # noqa: Y015

@_typing.final
class CMsgClientGetUserStatsResponse(_message.Message):

    @_typing.final
    class Stats(_message.Message):

        STAT_ID_FIELD_NUMBER: _builtins.int
        STAT_VALUE_FIELD_NUMBER: _builtins.int
        stat_id: _builtins.int
        stat_value: _builtins.int
        def __init__(
            self,
            *,
            stat_id: _builtins.int | None = ...,
            stat_value: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Achievement_Blocks(_message.Message):

        ACHIEVEMENT_ID_FIELD_NUMBER: _builtins.int
        UNLOCK_TIME_FIELD_NUMBER: _builtins.int
        achievement_id: _builtins.int
        @_builtins.property
        def unlock_time(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            achievement_id: _builtins.int | None = ...,
            unlock_time: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["achievement_id", b"achievement_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["achievement_id", b"achievement_id", "unlock_time", b"unlock_time"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    GAME_ID_FIELD_NUMBER: _builtins.int
    ERESULT_FIELD_NUMBER: _builtins.int
    CRC_STATS_FIELD_NUMBER: _builtins.int
    SCHEMA_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    ACHIEVEMENT_BLOCKS_FIELD_NUMBER: _builtins.int
    game_id: _builtins.int
    eresult: _builtins.int
    crc_stats: _builtins.int
    schema: _builtins.bytes
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientGetUserStatsResponse.Stats]: ...
    @_builtins.property
    def achievement_blocks(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientGetUserStatsResponse.Achievement_Blocks]: ...
    def __init__(
        self,
        *,
        game_id: _builtins.int | None = ...,
        eresult: _builtins.int | None = ...,
        crc_stats: _builtins.int | None = ...,
        schema: _builtins.bytes | None = ...,
        stats: _abc.Iterable[Global___CMsgClientGetUserStatsResponse.Stats] | None = ...,
        achievement_blocks: _abc.Iterable[Global___CMsgClientGetUserStatsResponse.Achievement_Blocks] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "eresult", b"eresult", "game_id", b"game_id", "schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["achievement_blocks", b"achievement_blocks", "crc_stats", b"crc_stats", "eresult", b"eresult", "game_id", b"game_id", "schema", b"schema", "stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientGetUserStatsResponse: _TypeAlias = CMsgClientGetUserStatsResponse  # noqa: Y015

@_typing.final
class CMsgClientStoreUserStatsResponse(_message.Message):

    @_typing.final
    class Stats_Failed_Validation(_message.Message):

        STAT_ID_FIELD_NUMBER: _builtins.int
        REVERTED_STAT_VALUE_FIELD_NUMBER: _builtins.int
        stat_id: _builtins.int
        reverted_stat_value: _builtins.int
        def __init__(
            self,
            *,
            stat_id: _builtins.int | None = ...,
            reverted_stat_value: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["reverted_stat_value", b"reverted_stat_value", "stat_id", b"stat_id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["reverted_stat_value", b"reverted_stat_value", "stat_id", b"stat_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    GAME_ID_FIELD_NUMBER: _builtins.int
    ERESULT_FIELD_NUMBER: _builtins.int
    CRC_STATS_FIELD_NUMBER: _builtins.int
    STATS_FAILED_VALIDATION_FIELD_NUMBER: _builtins.int
    STATS_OUT_OF_DATE_FIELD_NUMBER: _builtins.int
    game_id: _builtins.int
    eresult: _builtins.int
    crc_stats: _builtins.int
    stats_out_of_date: _builtins.bool
    @_builtins.property
    def stats_failed_validation(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientStoreUserStatsResponse.Stats_Failed_Validation]: ...
    def __init__(
        self,
        *,
        game_id: _builtins.int | None = ...,
        eresult: _builtins.int | None = ...,
        crc_stats: _builtins.int | None = ...,
        stats_failed_validation: _abc.Iterable[Global___CMsgClientStoreUserStatsResponse.Stats_Failed_Validation] | None = ...,
        stats_out_of_date: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "eresult", b"eresult", "game_id", b"game_id", "stats_out_of_date", b"stats_out_of_date"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "eresult", b"eresult", "game_id", b"game_id", "stats_failed_validation", b"stats_failed_validation", "stats_out_of_date", b"stats_out_of_date"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientStoreUserStatsResponse: _TypeAlias = CMsgClientStoreUserStatsResponse  # noqa: Y015

@_typing.final
class CMsgClientStoreUserStats2(_message.Message):

    @_typing.final
    class Stats(_message.Message):

        STAT_ID_FIELD_NUMBER: _builtins.int
        STAT_VALUE_FIELD_NUMBER: _builtins.int
        stat_id: _builtins.int
        stat_value: _builtins.int
        def __init__(
            self,
            *,
            stat_id: _builtins.int | None = ...,
            stat_value: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    GAME_ID_FIELD_NUMBER: _builtins.int
    SETTOR_STEAM_ID_FIELD_NUMBER: _builtins.int
    SETTEE_STEAM_ID_FIELD_NUMBER: _builtins.int
    CRC_STATS_FIELD_NUMBER: _builtins.int
    EXPLICIT_RESET_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    game_id: _builtins.int
    settor_steam_id: _builtins.int
    settee_steam_id: _builtins.int
    crc_stats: _builtins.int
    explicit_reset: _builtins.bool
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientStoreUserStats2.Stats]: ...
    def __init__(
        self,
        *,
        game_id: _builtins.int | None = ...,
        settor_steam_id: _builtins.int | None = ...,
        settee_steam_id: _builtins.int | None = ...,
        crc_stats: _builtins.int | None = ...,
        explicit_reset: _builtins.bool | None = ...,
        stats: _abc.Iterable[Global___CMsgClientStoreUserStats2.Stats] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "explicit_reset", b"explicit_reset", "game_id", b"game_id", "settee_steam_id", b"settee_steam_id", "settor_steam_id", b"settor_steam_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "explicit_reset", b"explicit_reset", "game_id", b"game_id", "settee_steam_id", b"settee_steam_id", "settor_steam_id", b"settor_steam_id", "stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientStoreUserStats2: _TypeAlias = CMsgClientStoreUserStats2  # noqa: Y015

@_typing.final
class CMsgClientStatsUpdated(_message.Message):

    @_typing.final
    class Updated_Stats(_message.Message):

        STAT_ID_FIELD_NUMBER: _builtins.int
        STAT_VALUE_FIELD_NUMBER: _builtins.int
        stat_id: _builtins.int
        stat_value: _builtins.int
        def __init__(
            self,
            *,
            stat_id: _builtins.int | None = ...,
            stat_value: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["stat_id", b"stat_id", "stat_value", b"stat_value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    STEAM_ID_FIELD_NUMBER: _builtins.int
    GAME_ID_FIELD_NUMBER: _builtins.int
    CRC_STATS_FIELD_NUMBER: _builtins.int
    UPDATED_STATS_FIELD_NUMBER: _builtins.int
    steam_id: _builtins.int
    game_id: _builtins.int
    crc_stats: _builtins.int
    @_builtins.property
    def updated_stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgClientStatsUpdated.Updated_Stats]: ...
    def __init__(
        self,
        *,
        steam_id: _builtins.int | None = ...,
        game_id: _builtins.int | None = ...,
        crc_stats: _builtins.int | None = ...,
        updated_stats: _abc.Iterable[Global___CMsgClientStatsUpdated.Updated_Stats] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "game_id", b"game_id", "steam_id", b"steam_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crc_stats", b"crc_stats", "game_id", b"game_id", "steam_id", b"steam_id", "updated_stats", b"updated_stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientStatsUpdated: _TypeAlias = CMsgClientStatsUpdated  # noqa: Y015
