"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CMsgClientSiteInfo(_message.Message):

    SITE_ID_FIELD_NUMBER: _builtins.int
    SITE_NAME_FIELD_NUMBER: _builtins.int
    ALLOW_CACHED_CREDENTIALS_FIELD_NUMBER: _builtins.int
    site_id: _builtins.int
    site_name: _builtins.str
    allow_cached_credentials: _builtins.bool
    def __init__(
        self,
        *,
        site_id: _builtins.int | None = ...,
        site_name: _builtins.str | None = ...,
        allow_cached_credentials: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["allow_cached_credentials", b"allow_cached_credentials", "site_id", b"site_id", "site_name", b"site_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_cached_credentials", b"allow_cached_credentials", "site_id", b"site_id", "site_name", b"site_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteInfo: _TypeAlias = CMsgClientSiteInfo  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseCheckout(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseCheckout: _TypeAlias = CMsgClientSiteLicenseCheckout  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseCheckoutResponse(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseCheckoutResponse: _TypeAlias = CMsgClientSiteLicenseCheckoutResponse  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseGetAvailableSeats(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseGetAvailableSeats: _TypeAlias = CMsgClientSiteLicenseGetAvailableSeats  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseGetAvailableSeatsResponse(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    SEATS_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    seats: _builtins.int
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
        seats: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "seats", b"seats"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eresult", b"eresult", "seats", b"seats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseGetAvailableSeatsResponse: _TypeAlias = CMsgClientSiteLicenseGetAvailableSeatsResponse  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseGetContentCacheInfo(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseGetContentCacheInfo: _TypeAlias = CMsgClientSiteLicenseGetContentCacheInfo  # noqa: Y015

@_typing.final
class CMsgClientSiteLicenseGetContentCacheInfoResponse(_message.Message):

    USE_CACHE_FIELD_NUMBER: _builtins.int
    IPV4_ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_NUMBER_FIELD_NUMBER: _builtins.int
    P2P_GROUP_FIELD_NUMBER: _builtins.int
    IP_ADDRESS_FIELD_NUMBER: _builtins.int
    use_cache: _builtins.bool
    ipv4_address: _builtins.int
    port_number: _builtins.int
    p2p_group: _builtins.int
    ip_address: _builtins.str
    def __init__(
        self,
        *,
        use_cache: _builtins.bool | None = ...,
        ipv4_address: _builtins.int | None = ...,
        port_number: _builtins.int | None = ...,
        p2p_group: _builtins.int | None = ...,
        ip_address: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ip_address", b"ip_address", "ipv4_address", b"ipv4_address", "p2p_group", b"p2p_group", "port_number", b"port_number", "use_cache", b"use_cache"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip_address", b"ip_address", "ipv4_address", b"ipv4_address", "p2p_group", b"p2p_group", "port_number", b"port_number", "use_cache", b"use_cache"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgClientSiteLicenseGetContentCacheInfoResponse: _TypeAlias = CMsgClientSiteLicenseGetContentCacheInfoResponse  # noqa: Y015
