"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import steam.protobufs.steammessages_clientserver_video_pb2 as _steammessages_clientserver_video_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CVideoManagerClipID(_message.Message):

    VIDEO_MANAGER_CLIP_ID_FIELD_NUMBER: _builtins.int
    VIDEO_MANAGER_VIDEO_ID_FIELD_NUMBER: _builtins.int
    SERVER_TIMELINE_ID_FIELD_NUMBER: _builtins.int
    MANIFEST_URL_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    START_OFFSET_MS_FIELD_NUMBER: _builtins.int
    video_manager_clip_id: _builtins.int
    video_manager_video_id: _builtins.int
    server_timeline_id: _builtins.int
    manifest_url: _builtins.str
    duration_ms: _builtins.int
    start_offset_ms: _builtins.int
    def __init__(
        self,
        *,
        video_manager_clip_id: _builtins.int | None = ...,
        video_manager_video_id: _builtins.int | None = ...,
        server_timeline_id: _builtins.int | None = ...,
        manifest_url: _builtins.str | None = ...,
        duration_ms: _builtins.int | None = ...,
        start_offset_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["duration_ms", b"duration_ms", "manifest_url", b"manifest_url", "server_timeline_id", b"server_timeline_id", "start_offset_ms", b"start_offset_ms", "video_manager_clip_id", b"video_manager_clip_id", "video_manager_video_id", b"video_manager_video_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_ms", b"duration_ms", "manifest_url", b"manifest_url", "server_timeline_id", b"server_timeline_id", "start_offset_ms", b"start_offset_ms", "video_manager_clip_id", b"video_manager_clip_id", "video_manager_video_id", b"video_manager_video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideoManagerClipID: _TypeAlias = CVideoManagerClipID  # noqa: Y015

@_typing.final
class CGameRecordingClip(_message.Message):

    CLIP_ID_FIELD_NUMBER: _builtins.int
    GAMEID_FIELD_NUMBER: _builtins.int
    DATE_RECORDED_FIELD_NUMBER: _builtins.int
    TOTAL_FILE_SIZE_BYTES_FIELD_NUMBER: _builtins.int
    VIDEO_IDS_FIELD_NUMBER: _builtins.int
    OWNER_STEAMID_FIELD_NUMBER: _builtins.int
    UPLOAD_COMPLETE_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    clip_id: _builtins.int
    gameid: _builtins.int
    date_recorded: _builtins.int
    total_file_size_bytes: _builtins.int
    owner_steamid: _builtins.int
    upload_complete: _builtins.bool
    duration_ms: _builtins.int
    @_builtins.property
    def video_ids(self) -> _containers.RepeatedCompositeFieldContainer[Global___CVideoManagerClipID]: ...
    def __init__(
        self,
        *,
        clip_id: _builtins.int | None = ...,
        gameid: _builtins.int | None = ...,
        date_recorded: _builtins.int | None = ...,
        total_file_size_bytes: _builtins.int | None = ...,
        video_ids: _abc.Iterable[Global___CVideoManagerClipID] | None = ...,
        owner_steamid: _builtins.int | None = ...,
        upload_complete: _builtins.bool | None = ...,
        duration_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id", "date_recorded", b"date_recorded", "duration_ms", b"duration_ms", "gameid", b"gameid", "owner_steamid", b"owner_steamid", "total_file_size_bytes", b"total_file_size_bytes", "upload_complete", b"upload_complete"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id", "date_recorded", b"date_recorded", "duration_ms", b"duration_ms", "gameid", b"gameid", "owner_steamid", b"owner_steamid", "total_file_size_bytes", b"total_file_size_bytes", "upload_complete", b"upload_complete", "video_ids", b"video_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecordingClip: _TypeAlias = CGameRecordingClip  # noqa: Y015

@_typing.final
class CGameRecording_CreateShareClip_Request(_message.Message):

    CLIP_FIELD_NUMBER: _builtins.int
    VIDEO_DEF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def clip(self) -> Global___CGameRecordingClip: ...
    @_builtins.property
    def video_def(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_clientserver_video_pb2.CMsgVideoGameRecordingDef]: ...
    def __init__(
        self,
        *,
        clip: Global___CGameRecordingClip | None = ...,
        video_def: _abc.Iterable[_steammessages_clientserver_video_pb2.CMsgVideoGameRecordingDef] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip", "video_def", b"video_def"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_CreateShareClip_Request: _TypeAlias = CGameRecording_CreateShareClip_Request  # noqa: Y015

@_typing.final
class CGameRecording_CreateShareClip_Response(_message.Message):

    CLIP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def clip(self) -> Global___CGameRecordingClip: ...
    def __init__(
        self,
        *,
        clip: Global___CGameRecordingClip | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_CreateShareClip_Response: _TypeAlias = CGameRecording_CreateShareClip_Response  # noqa: Y015

@_typing.final
class CGameRecording_DeleteSharedClip_Request(_message.Message):

    CLIP_ID_FIELD_NUMBER: _builtins.int
    clip_id: _builtins.int
    def __init__(
        self,
        *,
        clip_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_DeleteSharedClip_Request: _TypeAlias = CGameRecording_DeleteSharedClip_Request  # noqa: Y015

@_typing.final
class CGameRecording_DeleteSharedClip_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_DeleteSharedClip_Response: _TypeAlias = CGameRecording_DeleteSharedClip_Response  # noqa: Y015

@_typing.final
class CGameRecording_GetSingleSharedClip_Request(_message.Message):

    CLIP_ID_FIELD_NUMBER: _builtins.int
    clip_id: _builtins.int
    def __init__(
        self,
        *,
        clip_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip_id", b"clip_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_GetSingleSharedClip_Request: _TypeAlias = CGameRecording_GetSingleSharedClip_Request  # noqa: Y015

@_typing.final
class CGameRecording_GetSingleSharedClip_Response(_message.Message):

    CLIP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def clip(self) -> Global___CGameRecordingClip: ...
    def __init__(
        self,
        *,
        clip: Global___CGameRecordingClip | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clip", b"clip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_GetSingleSharedClip_Response: _TypeAlias = CGameRecording_GetSingleSharedClip_Response  # noqa: Y015

@_typing.final
class CVideo_BeginGameRecordingSegmentsUpload_Request(_message.Message):

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    COMPONENT_NAME_FIELD_NUMBER: _builtins.int
    REPRESENTATION_NAME_FIELD_NUMBER: _builtins.int
    SEGMENTS_TO_STORE_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.int
    component_name: _builtins.str
    representation_name: _builtins.str
    @_builtins.property
    def segments_to_store(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentInfo]: ...
    def __init__(
        self,
        *,
        recording_id: _builtins.int | None = ...,
        component_name: _builtins.str | None = ...,
        representation_name: _builtins.str | None = ...,
        segments_to_store: _abc.Iterable[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["component_name", b"component_name", "recording_id", b"recording_id", "representation_name", b"representation_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["component_name", b"component_name", "recording_id", b"recording_id", "representation_name", b"representation_name", "segments_to_store", b"segments_to_store"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_BeginGameRecordingSegmentsUpload_Request: _TypeAlias = CVideo_BeginGameRecordingSegmentsUpload_Request  # noqa: Y015

@_typing.final
class CVideo_BeginGameRecordingSegmentsUpload_Response(_message.Message):

    SEGMENTS_NEEDED_FIELD_NUMBER: _builtins.int
    CALL_AGAIN_FIELD_NUMBER: _builtins.int
    call_again: _builtins.bool
    @_builtins.property
    def segments_needed(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentUploadInfo]: ...
    def __init__(
        self,
        *,
        segments_needed: _abc.Iterable[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentUploadInfo] | None = ...,
        call_again: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["call_again", b"call_again"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["call_again", b"call_again", "segments_needed", b"segments_needed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_BeginGameRecordingSegmentsUpload_Response: _TypeAlias = CVideo_BeginGameRecordingSegmentsUpload_Response  # noqa: Y015

@_typing.final
class CVideo_CommitGameRecordingSegmentsUpload_Request(_message.Message):

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    COMPONENT_NAME_FIELD_NUMBER: _builtins.int
    REPRESENTATION_NAME_FIELD_NUMBER: _builtins.int
    FIRST_SEGMENT_NUMBER_FIELD_NUMBER: _builtins.int
    NUM_SEGMENTS_FIELD_NUMBER: _builtins.int
    UPLOAD_RESULT_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.int
    component_name: _builtins.str
    representation_name: _builtins.str
    first_segment_number: _builtins.int
    num_segments: _builtins.int
    upload_result: _builtins.int
    def __init__(
        self,
        *,
        recording_id: _builtins.int | None = ...,
        component_name: _builtins.str | None = ...,
        representation_name: _builtins.str | None = ...,
        first_segment_number: _builtins.int | None = ...,
        num_segments: _builtins.int | None = ...,
        upload_result: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["component_name", b"component_name", "first_segment_number", b"first_segment_number", "num_segments", b"num_segments", "recording_id", b"recording_id", "representation_name", b"representation_name", "upload_result", b"upload_result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["component_name", b"component_name", "first_segment_number", b"first_segment_number", "num_segments", b"num_segments", "recording_id", b"recording_id", "representation_name", b"representation_name", "upload_result", b"upload_result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_CommitGameRecordingSegmentsUpload_Request: _TypeAlias = CVideo_CommitGameRecordingSegmentsUpload_Request  # noqa: Y015

@_typing.final
class CVideo_CommitGameRecordingSegmentsUpload_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_CommitGameRecordingSegmentsUpload_Response: _TypeAlias = CVideo_CommitGameRecordingSegmentsUpload_Response  # noqa: Y015

@_typing.final
class CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Request(_message.Message):

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.int
    def __init__(
        self,
        *,
        recording_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Request: _TypeAlias = CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Request  # noqa: Y015

@_typing.final
class CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Response(_message.Message):

    SEGMENTS_NEEDED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def segments_needed(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentUploadInfo]: ...
    def __init__(
        self,
        *,
        segments_needed: _abc.Iterable[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentUploadInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["segments_needed", b"segments_needed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Response: _TypeAlias = CVideo_GameRecordingGetNextBatchOfSegmentsToUpload_Response  # noqa: Y015

@_typing.final
class CVideo_GameRecordingCommitSegmentUploads_Request(_message.Message):

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    SEGMENTS_UPLOADED_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.int
    @_builtins.property
    def segments_uploaded(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentInfo]: ...
    def __init__(
        self,
        *,
        recording_id: _builtins.int | None = ...,
        segments_uploaded: _abc.Iterable[_steammessages_clientserver_video_pb2.CVideo_GameRecordingSegmentInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id", "segments_uploaded", b"segments_uploaded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_GameRecordingCommitSegmentUploads_Request: _TypeAlias = CVideo_GameRecordingCommitSegmentUploads_Request  # noqa: Y015

@_typing.final
class CVideo_GameRecordingCommitSegmentUploads_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CVideo_GameRecordingCommitSegmentUploads_Response: _TypeAlias = CVideo_GameRecordingCommitSegmentUploads_Response  # noqa: Y015
