"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import steam.protobufs.steammessages_storebrowse_pb2 as _steammessages_storebrowse_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _EMarketingMessageType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageInvalid: _EMarketingMessageType.ValueType  # 0
    k_EMarketingMessageNowAvailable: _EMarketingMessageType.ValueType  # 1
    k_EMarketingMessageWeekendDeal: _EMarketingMessageType.ValueType  # 2
    k_EMarketingMessagePrePurchase: _EMarketingMessageType.ValueType  # 3
    k_EMarketingMessagePlayNow: _EMarketingMessageType.ValueType  # 4
    k_EMarketingMessagePreloadNow: _EMarketingMessageType.ValueType  # 5
    k_EMarketingMessageGeneral: _EMarketingMessageType.ValueType  # 6
    k_EMarketingMessageDemoQuit: _EMarketingMessageType.ValueType  # 7
    k_EMarketingMessageGifting: _EMarketingMessageType.ValueType  # 8
    k_EMarketingMessageEJsKorner: _EMarketingMessageType.ValueType  # 9
    k_EMarketingMessageUpdate: _EMarketingMessageType.ValueType  # 10
    k_EMarketingMessageMidweekDeal: _EMarketingMessageType.ValueType  # 11
    k_EMarketingMessageDailyDeal: _EMarketingMessageType.ValueType  # 12
    k_EMarketingMessageNewDLC: _EMarketingMessageType.ValueType  # 13
    k_EMarketingMessageFreeWeekend: _EMarketingMessageType.ValueType  # 14
    k_EMarketingMessageSalePages: _EMarketingMessageType.ValueType  # 15
    k_EMarketingMessagePlaytestAvailable: _EMarketingMessageType.ValueType  # 16

class EMarketingMessageType(_EMarketingMessageType, metaclass=_EMarketingMessageTypeEnumTypeWrapper): ...

k_EMarketingMessageInvalid: EMarketingMessageType.ValueType  # 0
k_EMarketingMessageNowAvailable: EMarketingMessageType.ValueType  # 1
k_EMarketingMessageWeekendDeal: EMarketingMessageType.ValueType  # 2
k_EMarketingMessagePrePurchase: EMarketingMessageType.ValueType  # 3
k_EMarketingMessagePlayNow: EMarketingMessageType.ValueType  # 4
k_EMarketingMessagePreloadNow: EMarketingMessageType.ValueType  # 5
k_EMarketingMessageGeneral: EMarketingMessageType.ValueType  # 6
k_EMarketingMessageDemoQuit: EMarketingMessageType.ValueType  # 7
k_EMarketingMessageGifting: EMarketingMessageType.ValueType  # 8
k_EMarketingMessageEJsKorner: EMarketingMessageType.ValueType  # 9
k_EMarketingMessageUpdate: EMarketingMessageType.ValueType  # 10
k_EMarketingMessageMidweekDeal: EMarketingMessageType.ValueType  # 11
k_EMarketingMessageDailyDeal: EMarketingMessageType.ValueType  # 12
k_EMarketingMessageNewDLC: EMarketingMessageType.ValueType  # 13
k_EMarketingMessageFreeWeekend: EMarketingMessageType.ValueType  # 14
k_EMarketingMessageSalePages: EMarketingMessageType.ValueType  # 15
k_EMarketingMessagePlaytestAvailable: EMarketingMessageType.ValueType  # 16
Global___EMarketingMessageType: _TypeAlias = EMarketingMessageType  # noqa: Y015

class _EMarketingMessageVisibility:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageVisibilityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageVisibility.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageVisibleBeta: _EMarketingMessageVisibility.ValueType  # 1
    k_EMarketingMessageVisiblePublic: _EMarketingMessageVisibility.ValueType  # 2
    k_EMarketingMessageVisibleApprovedForPublish: _EMarketingMessageVisibility.ValueType  # 3

class EMarketingMessageVisibility(_EMarketingMessageVisibility, metaclass=_EMarketingMessageVisibilityEnumTypeWrapper): ...

k_EMarketingMessageVisibleBeta: EMarketingMessageVisibility.ValueType  # 1
k_EMarketingMessageVisiblePublic: EMarketingMessageVisibility.ValueType  # 2
k_EMarketingMessageVisibleApprovedForPublish: EMarketingMessageVisibility.ValueType  # 3
Global___EMarketingMessageVisibility: _TypeAlias = EMarketingMessageVisibility  # noqa: Y015

class _EMarketingMessageAssociationType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageAssociationTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageAssociationType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageNoAssociation: _EMarketingMessageAssociationType.ValueType  # 0
    k_EMarketingMessageAppAssociation: _EMarketingMessageAssociationType.ValueType  # 1
    k_EMarketingMessageSubscriptionAssociation: _EMarketingMessageAssociationType.ValueType  # 2
    k_EMarketingMessagePublisherAssociation: _EMarketingMessageAssociationType.ValueType  # 3
    k_EMarketingMessageGenreAssociation: _EMarketingMessageAssociationType.ValueType  # 4
    k_EMarketingMessageBundleAssociation: _EMarketingMessageAssociationType.ValueType  # 5

class EMarketingMessageAssociationType(_EMarketingMessageAssociationType, metaclass=_EMarketingMessageAssociationTypeEnumTypeWrapper): ...

k_EMarketingMessageNoAssociation: EMarketingMessageAssociationType.ValueType  # 0
k_EMarketingMessageAppAssociation: EMarketingMessageAssociationType.ValueType  # 1
k_EMarketingMessageSubscriptionAssociation: EMarketingMessageAssociationType.ValueType  # 2
k_EMarketingMessagePublisherAssociation: EMarketingMessageAssociationType.ValueType  # 3
k_EMarketingMessageGenreAssociation: EMarketingMessageAssociationType.ValueType  # 4
k_EMarketingMessageBundleAssociation: EMarketingMessageAssociationType.ValueType  # 5
Global___EMarketingMessageAssociationType: _TypeAlias = EMarketingMessageAssociationType  # noqa: Y015

class _EMarketingMessageTemplateType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageTemplateTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageTemplateType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageTemplate_Unknown: _EMarketingMessageTemplateType.ValueType  # 0
    k_EMarketingMessageTemplate_Image: _EMarketingMessageTemplateType.ValueType  # 1
    k_EMarketingMessageTemplate_Animated: _EMarketingMessageTemplateType.ValueType  # 2
    k_EMarketingMessageTemplate_Featured_Video: _EMarketingMessageTemplateType.ValueType  # 3
    k_EMarketingMessageTemplate_DLC_Override: _EMarketingMessageTemplateType.ValueType  # 4
    k_EMarketingMessageTemplate_Replay: _EMarketingMessageTemplateType.ValueType  # 5
    k_EMarketingMessageTemplate_Event: _EMarketingMessageTemplateType.ValueType  # 6
    k_EMarketingMessageTemplate_AutoRender: _EMarketingMessageTemplateType.ValueType  # 7
    k_EMarketingMessageTemplate_MAX: _EMarketingMessageTemplateType.ValueType  # 8

class EMarketingMessageTemplateType(_EMarketingMessageTemplateType, metaclass=_EMarketingMessageTemplateTypeEnumTypeWrapper): ...

k_EMarketingMessageTemplate_Unknown: EMarketingMessageTemplateType.ValueType  # 0
k_EMarketingMessageTemplate_Image: EMarketingMessageTemplateType.ValueType  # 1
k_EMarketingMessageTemplate_Animated: EMarketingMessageTemplateType.ValueType  # 2
k_EMarketingMessageTemplate_Featured_Video: EMarketingMessageTemplateType.ValueType  # 3
k_EMarketingMessageTemplate_DLC_Override: EMarketingMessageTemplateType.ValueType  # 4
k_EMarketingMessageTemplate_Replay: EMarketingMessageTemplateType.ValueType  # 5
k_EMarketingMessageTemplate_Event: EMarketingMessageTemplateType.ValueType  # 6
k_EMarketingMessageTemplate_AutoRender: EMarketingMessageTemplateType.ValueType  # 7
k_EMarketingMessageTemplate_MAX: EMarketingMessageTemplateType.ValueType  # 8
Global___EMarketingMessageTemplateType: _TypeAlias = EMarketingMessageTemplateType  # noqa: Y015

class _EMarketingMessageClickLocation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageClickLocationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageClickLocation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageClickLocation_Unknown: _EMarketingMessageClickLocation.ValueType  # 0
    k_EMarketingMessageClickLocation_Image: _EMarketingMessageClickLocation.ValueType  # 1
    k_EMarketingMessageClickLocation_Button: _EMarketingMessageClickLocation.ValueType  # 2
    k_EMarketingMessageClickLocation_DlcCapsule: _EMarketingMessageClickLocation.ValueType  # 3
    k_EMarketingMessageClickLocation_HeaderArea: _EMarketingMessageClickLocation.ValueType  # 4
    k_EMarketingMessageClickLocation_GameCapsule: _EMarketingMessageClickLocation.ValueType  # 5
    k_EMarketingMessageClickLocation_PartnerEvent: _EMarketingMessageClickLocation.ValueType  # 6

class EMarketingMessageClickLocation(_EMarketingMessageClickLocation, metaclass=_EMarketingMessageClickLocationEnumTypeWrapper): ...

k_EMarketingMessageClickLocation_Unknown: EMarketingMessageClickLocation.ValueType  # 0
k_EMarketingMessageClickLocation_Image: EMarketingMessageClickLocation.ValueType  # 1
k_EMarketingMessageClickLocation_Button: EMarketingMessageClickLocation.ValueType  # 2
k_EMarketingMessageClickLocation_DlcCapsule: EMarketingMessageClickLocation.ValueType  # 3
k_EMarketingMessageClickLocation_HeaderArea: EMarketingMessageClickLocation.ValueType  # 4
k_EMarketingMessageClickLocation_GameCapsule: EMarketingMessageClickLocation.ValueType  # 5
k_EMarketingMessageClickLocation_PartnerEvent: EMarketingMessageClickLocation.ValueType  # 6
Global___EMarketingMessageClickLocation: _TypeAlias = EMarketingMessageClickLocation  # noqa: Y015

class _EMarketingMessageLookupType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EMarketingMessageLookupTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EMarketingMessageLookupType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EMarketingMessageLookupInvalid: _EMarketingMessageLookupType.ValueType  # 0
    k_EMarketingMessageLookupByGID: _EMarketingMessageLookupType.ValueType  # 1
    k_EMarketingMessageLookupActive: _EMarketingMessageLookupType.ValueType  # 2
    k_EMarketingMessageLookupByTitleWithType: _EMarketingMessageLookupType.ValueType  # 3
    k_EMarketingMessageLookupByGIDList: _EMarketingMessageLookupType.ValueType  # 4
    k_EMarketingMessageLookupByAssociatedID: _EMarketingMessageLookupType.ValueType  # 5

class EMarketingMessageLookupType(_EMarketingMessageLookupType, metaclass=_EMarketingMessageLookupTypeEnumTypeWrapper): ...

k_EMarketingMessageLookupInvalid: EMarketingMessageLookupType.ValueType  # 0
k_EMarketingMessageLookupByGID: EMarketingMessageLookupType.ValueType  # 1
k_EMarketingMessageLookupActive: EMarketingMessageLookupType.ValueType  # 2
k_EMarketingMessageLookupByTitleWithType: EMarketingMessageLookupType.ValueType  # 3
k_EMarketingMessageLookupByGIDList: EMarketingMessageLookupType.ValueType  # 4
k_EMarketingMessageLookupByAssociatedID: EMarketingMessageLookupType.ValueType  # 5
Global___EMarketingMessageLookupType: _TypeAlias = EMarketingMessageLookupType  # noqa: Y015

@_typing.final
class CMarketingMessages_GetActiveMarketingMessages_Request(_message.Message):

    COUNTRY_FIELD_NUMBER: _builtins.int
    ANONYMOUS_USER_FIELD_NUMBER: _builtins.int
    country: _builtins.str
    anonymous_user: _builtins.bool
    def __init__(
        self,
        *,
        country: _builtins.str | None = ...,
        anonymous_user: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["anonymous_user", b"anonymous_user", "country", b"country"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["anonymous_user", b"anonymous_user", "country", b"country"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetActiveMarketingMessages_Request: _TypeAlias = CMarketingMessages_GetActiveMarketingMessages_Request  # noqa: Y015

@_typing.final
class CMarketingMessageProto(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    VISIBILITY_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    ASSOCIATION_TYPE_FIELD_NUMBER: _builtins.int
    ASSOCIATED_ID_FIELD_NUMBER: _builtins.int
    ASSOCIATED_NAME_FIELD_NUMBER: _builtins.int
    START_DATE_FIELD_NUMBER: _builtins.int
    END_DATE_FIELD_NUMBER: _builtins.int
    COUNTRY_ALLOW_FIELD_NUMBER: _builtins.int
    COUNTRY_DENY_FIELD_NUMBER: _builtins.int
    OWNERSHIP_RESTRICTIONS_OVERRIDDEN_FIELD_NUMBER: _builtins.int
    MUST_OWN_APPID_FIELD_NUMBER: _builtins.int
    MUST_NOT_OWN_APPID_FIELD_NUMBER: _builtins.int
    MUST_OWN_PACKAGEID_FIELD_NUMBER: _builtins.int
    MUST_NOT_OWN_PACKAGEID_FIELD_NUMBER: _builtins.int
    MUST_HAVE_LAUNCHED_APPID_FIELD_NUMBER: _builtins.int
    ADDITIONAL_RESTRICTIONS_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    TEMPLATE_VARS_FIELD_NUMBER: _builtins.int
    FLAGS_FIELD_NUMBER: _builtins.int
    CREATOR_NAME_FIELD_NUMBER: _builtins.int
    TEMPLATE_VARS_JSON_FIELD_NUMBER: _builtins.int
    ADDITIONAL_RESTRICTIONS_JSON_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    title: _builtins.str
    type: Global___EMarketingMessageType.ValueType
    visibility: Global___EMarketingMessageVisibility.ValueType
    priority: _builtins.int
    association_type: Global___EMarketingMessageAssociationType.ValueType
    associated_id: _builtins.int
    associated_name: _builtins.str
    start_date: _builtins.int
    end_date: _builtins.int
    country_allow: _builtins.str
    country_deny: _builtins.str
    ownership_restrictions_overridden: _builtins.bool
    must_own_appid: _builtins.int
    must_not_own_appid: _builtins.int
    must_own_packageid: _builtins.int
    must_not_own_packageid: _builtins.int
    must_have_launched_appid: _builtins.int
    additional_restrictions: _builtins.str
    template_type: _builtins.str
    template_vars: _builtins.str
    flags: _builtins.int
    creator_name: _builtins.str
    template_vars_json: _builtins.str
    additional_restrictions_json: _builtins.str
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        title: _builtins.str | None = ...,
        type: Global___EMarketingMessageType.ValueType | None = ...,
        visibility: Global___EMarketingMessageVisibility.ValueType | None = ...,
        priority: _builtins.int | None = ...,
        association_type: Global___EMarketingMessageAssociationType.ValueType | None = ...,
        associated_id: _builtins.int | None = ...,
        associated_name: _builtins.str | None = ...,
        start_date: _builtins.int | None = ...,
        end_date: _builtins.int | None = ...,
        country_allow: _builtins.str | None = ...,
        country_deny: _builtins.str | None = ...,
        ownership_restrictions_overridden: _builtins.bool | None = ...,
        must_own_appid: _builtins.int | None = ...,
        must_not_own_appid: _builtins.int | None = ...,
        must_own_packageid: _builtins.int | None = ...,
        must_not_own_packageid: _builtins.int | None = ...,
        must_have_launched_appid: _builtins.int | None = ...,
        additional_restrictions: _builtins.str | None = ...,
        template_type: _builtins.str | None = ...,
        template_vars: _builtins.str | None = ...,
        flags: _builtins.int | None = ...,
        creator_name: _builtins.str | None = ...,
        template_vars_json: _builtins.str | None = ...,
        additional_restrictions_json: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["additional_restrictions", b"additional_restrictions", "additional_restrictions_json", b"additional_restrictions_json", "associated_id", b"associated_id", "associated_name", b"associated_name", "association_type", b"association_type", "country_allow", b"country_allow", "country_deny", b"country_deny", "creator_name", b"creator_name", "end_date", b"end_date", "flags", b"flags", "gid", b"gid", "must_have_launched_appid", b"must_have_launched_appid", "must_not_own_appid", b"must_not_own_appid", "must_not_own_packageid", b"must_not_own_packageid", "must_own_appid", b"must_own_appid", "must_own_packageid", b"must_own_packageid", "ownership_restrictions_overridden", b"ownership_restrictions_overridden", "priority", b"priority", "start_date", b"start_date", "template_type", b"template_type", "template_vars", b"template_vars", "template_vars_json", b"template_vars_json", "title", b"title", "type", b"type", "visibility", b"visibility"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["additional_restrictions", b"additional_restrictions", "additional_restrictions_json", b"additional_restrictions_json", "associated_id", b"associated_id", "associated_name", b"associated_name", "association_type", b"association_type", "country_allow", b"country_allow", "country_deny", b"country_deny", "creator_name", b"creator_name", "end_date", b"end_date", "flags", b"flags", "gid", b"gid", "must_have_launched_appid", b"must_have_launched_appid", "must_not_own_appid", b"must_not_own_appid", "must_not_own_packageid", b"must_not_own_packageid", "must_own_appid", b"must_own_appid", "must_own_packageid", b"must_own_packageid", "ownership_restrictions_overridden", b"ownership_restrictions_overridden", "priority", b"priority", "start_date", b"start_date", "template_type", b"template_type", "template_vars", b"template_vars", "template_vars_json", b"template_vars_json", "title", b"title", "type", b"type", "visibility", b"visibility"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessageProto: _TypeAlias = CMarketingMessageProto  # noqa: Y015

@_typing.final
class CMarketingMessages_GetActiveMarketingMessages_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    TIME_NEXT_MESSAGE_AGE_FIELD_NUMBER: _builtins.int
    time_next_message_age: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageProto]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessageProto] | None = ...,
        time_next_message_age: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time_next_message_age", b"time_next_message_age"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages", "time_next_message_age", b"time_next_message_age"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetActiveMarketingMessages_Response: _TypeAlias = CMarketingMessages_GetActiveMarketingMessages_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPastMarketingMessages_Request(_message.Message):

    START_PAST_DAYS_FIELD_NUMBER: _builtins.int
    UPTO_PAST_DAYS_FIELD_NUMBER: _builtins.int
    start_past_days: _builtins.int
    upto_past_days: _builtins.int
    def __init__(
        self,
        *,
        start_past_days: _builtins.int | None = ...,
        upto_past_days: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["start_past_days", b"start_past_days", "upto_past_days", b"upto_past_days"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["start_past_days", b"start_past_days", "upto_past_days", b"upto_past_days"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPastMarketingMessages_Request: _TypeAlias = CMarketingMessages_GetPastMarketingMessages_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPastMarketingMessages_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageProto]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessageProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPastMarketingMessages_Response: _TypeAlias = CMarketingMessages_GetPastMarketingMessages_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessagesForUser_Request(_message.Message):

    INCLUDE_SEEN_MESSAGES_FIELD_NUMBER: _builtins.int
    COUNTRY_CODE_FIELD_NUMBER: _builtins.int
    ELANGUAGE_FIELD_NUMBER: _builtins.int
    OPERATING_SYSTEM_FIELD_NUMBER: _builtins.int
    CLIENT_PACKAGE_VERSION_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    DATA_REQUEST_FIELD_NUMBER: _builtins.int
    include_seen_messages: _builtins.bool
    country_code: _builtins.str
    elanguage: _builtins.int
    operating_system: _builtins.int
    client_package_version: _builtins.int
    @_builtins.property
    def context(self) -> _steammessages_storebrowse_pb2.StoreBrowseContext: ...
    @_builtins.property
    def data_request(self) -> _steammessages_storebrowse_pb2.StoreBrowseItemDataRequest: ...
    def __init__(
        self,
        *,
        include_seen_messages: _builtins.bool | None = ...,
        country_code: _builtins.str | None = ...,
        elanguage: _builtins.int | None = ...,
        operating_system: _builtins.int | None = ...,
        client_package_version: _builtins.int | None = ...,
        context: _steammessages_storebrowse_pb2.StoreBrowseContext | None = ...,
        data_request: _steammessages_storebrowse_pb2.StoreBrowseItemDataRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_package_version", b"client_package_version", "context", b"context", "country_code", b"country_code", "data_request", b"data_request", "elanguage", b"elanguage", "include_seen_messages", b"include_seen_messages", "operating_system", b"operating_system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_package_version", b"client_package_version", "context", b"context", "country_code", b"country_code", "data_request", b"data_request", "elanguage", b"elanguage", "include_seen_messages", b"include_seen_messages", "operating_system", b"operating_system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessagesForUser_Request: _TypeAlias = CMarketingMessages_GetMarketingMessagesForUser_Request  # noqa: Y015

@_typing.final
class CDisplayMarketingMessage(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    ASSOCIATED_ITEM_ID_FIELD_NUMBER: _builtins.int
    ASSOCIATED_ITEM_FIELD_NUMBER: _builtins.int
    ASSOCIATED_NAME_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    TEMPLATE_VARS_JSON_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    title: _builtins.str
    type: Global___EMarketingMessageType.ValueType
    associated_name: _builtins.str
    template_type: _builtins.str
    template_vars_json: _builtins.str
    @_builtins.property
    def associated_item_id(self) -> _steammessages_storebrowse_pb2.StoreItemID: ...
    @_builtins.property
    def associated_item(self) -> _steammessages_storebrowse_pb2.StoreItem: ...
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        title: _builtins.str | None = ...,
        type: Global___EMarketingMessageType.ValueType | None = ...,
        associated_item_id: _steammessages_storebrowse_pb2.StoreItemID | None = ...,
        associated_item: _steammessages_storebrowse_pb2.StoreItem | None = ...,
        associated_name: _builtins.str | None = ...,
        template_type: _builtins.str | None = ...,
        template_vars_json: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["associated_item", b"associated_item", "associated_item_id", b"associated_item_id", "associated_name", b"associated_name", "gid", b"gid", "template_type", b"template_type", "template_vars_json", b"template_vars_json", "title", b"title", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["associated_item", b"associated_item", "associated_item_id", b"associated_item_id", "associated_name", b"associated_name", "gid", b"gid", "template_type", b"template_type", "template_vars_json", b"template_vars_json", "title", b"title", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CDisplayMarketingMessage: _TypeAlias = CDisplayMarketingMessage  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessagesForUser_Response(_message.Message):

    @_typing.final
    class MarketingMessageForUser(_message.Message):

        ALREADY_SEEN_FIELD_NUMBER: _builtins.int
        MESSAGE_FIELD_NUMBER: _builtins.int
        already_seen: _builtins.bool
        @_builtins.property
        def message(self) -> Global___CDisplayMarketingMessage: ...
        def __init__(
            self,
            *,
            already_seen: _builtins.bool | None = ...,
            message: Global___CDisplayMarketingMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["already_seen", b"already_seen", "message", b"message"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["already_seen", b"already_seen", "message", b"message"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessages_GetMarketingMessagesForUser_Response.MarketingMessageForUser]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessages_GetMarketingMessagesForUser_Response.MarketingMessageForUser] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessagesForUser_Response: _TypeAlias = CMarketingMessages_GetMarketingMessagesForUser_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_DoesUserHavePendingMarketingMessages_Request(_message.Message):

    COUNTRY_CODE_FIELD_NUMBER: _builtins.int
    ELANGUAGE_FIELD_NUMBER: _builtins.int
    OPERATING_SYSTEM_FIELD_NUMBER: _builtins.int
    CLIENT_PACKAGE_VERSION_FIELD_NUMBER: _builtins.int
    country_code: _builtins.str
    elanguage: _builtins.int
    operating_system: _builtins.int
    client_package_version: _builtins.int
    def __init__(
        self,
        *,
        country_code: _builtins.str | None = ...,
        elanguage: _builtins.int | None = ...,
        operating_system: _builtins.int | None = ...,
        client_package_version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_package_version", b"client_package_version", "country_code", b"country_code", "elanguage", b"elanguage", "operating_system", b"operating_system"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_package_version", b"client_package_version", "country_code", b"country_code", "elanguage", b"elanguage", "operating_system", b"operating_system"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_DoesUserHavePendingMarketingMessages_Request: _TypeAlias = CMarketingMessages_DoesUserHavePendingMarketingMessages_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_DoesUserHavePendingMarketingMessages_Response(_message.Message):

    HAS_PENDING_MESSAGES_FIELD_NUMBER: _builtins.int
    PENDING_MESSAGE_COUNT_FIELD_NUMBER: _builtins.int
    has_pending_messages: _builtins.bool
    pending_message_count: _builtins.int
    def __init__(
        self,
        *,
        has_pending_messages: _builtins.bool | None = ...,
        pending_message_count: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["has_pending_messages", b"has_pending_messages", "pending_message_count", b"pending_message_count"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_pending_messages", b"has_pending_messages", "pending_message_count", b"pending_message_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_DoesUserHavePendingMarketingMessages_Response: _TypeAlias = CMarketingMessages_DoesUserHavePendingMarketingMessages_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetDisplayMarketingMessage_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    DATA_REQUEST_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    @_builtins.property
    def context(self) -> _steammessages_storebrowse_pb2.StoreBrowseContext: ...
    @_builtins.property
    def data_request(self) -> _steammessages_storebrowse_pb2.StoreBrowseItemDataRequest: ...
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        context: _steammessages_storebrowse_pb2.StoreBrowseContext | None = ...,
        data_request: _steammessages_storebrowse_pb2.StoreBrowseItemDataRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "data_request", b"data_request", "gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "data_request", b"data_request", "gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetDisplayMarketingMessage_Request: _TypeAlias = CMarketingMessages_GetDisplayMarketingMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetDisplayMarketingMessage_Response(_message.Message):

    MESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def message(self) -> Global___CDisplayMarketingMessage: ...
    def __init__(
        self,
        *,
        message: Global___CDisplayMarketingMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetDisplayMarketingMessage_Response: _TypeAlias = CMarketingMessages_GetDisplayMarketingMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_MarkMessageSeen_Notification(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    DISPLAY_INDEX_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    display_index: _builtins.int
    template_type: Global___EMarketingMessageTemplateType.ValueType
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        display_index: _builtins.int | None = ...,
        template_type: Global___EMarketingMessageTemplateType.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["display_index", b"display_index", "gid", b"gid", "template_type", b"template_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_index", b"display_index", "gid", b"gid", "template_type", b"template_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_MarkMessageSeen_Notification: _TypeAlias = CMarketingMessages_MarkMessageSeen_Notification  # noqa: Y015

@_typing.final
class CMarketingMessages_MarkMessageClicked_Notification(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    DISPLAY_INDEX_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    CLICK_LOCATION_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    display_index: _builtins.int
    template_type: Global___EMarketingMessageTemplateType.ValueType
    click_location: Global___EMarketingMessageClickLocation.ValueType
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        display_index: _builtins.int | None = ...,
        template_type: Global___EMarketingMessageTemplateType.ValueType | None = ...,
        click_location: Global___EMarketingMessageClickLocation.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["click_location", b"click_location", "display_index", b"display_index", "gid", b"gid", "template_type", b"template_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["click_location", b"click_location", "display_index", b"display_index", "gid", b"gid", "template_type", b"template_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_MarkMessageClicked_Notification: _TypeAlias = CMarketingMessages_MarkMessageClicked_Notification  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessage_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessage_Request: _TypeAlias = CMarketingMessages_GetMarketingMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessage_Response(_message.Message):

    MESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def message(self) -> Global___CMarketingMessageProto: ...
    def __init__(
        self,
        *,
        message: Global___CMarketingMessageProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessage_Response: _TypeAlias = CMarketingMessages_GetMarketingMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_CreateMarketingMessage_Request(_message.Message):

    MESSAGE_FIELD_NUMBER: _builtins.int
    FROM_JSON_FIELD_NUMBER: _builtins.int
    from_json: _builtins.bool
    @_builtins.property
    def message(self) -> Global___CMarketingMessageProto: ...
    def __init__(
        self,
        *,
        message: Global___CMarketingMessageProto | None = ...,
        from_json: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["from_json", b"from_json", "message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from_json", b"from_json", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_CreateMarketingMessage_Request: _TypeAlias = CMarketingMessages_CreateMarketingMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_CreateMarketingMessage_Response(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_CreateMarketingMessage_Response: _TypeAlias = CMarketingMessages_CreateMarketingMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_UpdateMarketingMessage_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    FROM_JSON_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    from_json: _builtins.bool
    @_builtins.property
    def message(self) -> Global___CMarketingMessageProto: ...
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        message: Global___CMarketingMessageProto | None = ...,
        from_json: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["from_json", b"from_json", "gid", b"gid", "message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from_json", b"from_json", "gid", b"gid", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_UpdateMarketingMessage_Request: _TypeAlias = CMarketingMessages_UpdateMarketingMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_UpdateMarketingMessage_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_UpdateMarketingMessage_Response: _TypeAlias = CMarketingMessages_UpdateMarketingMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_DeleteMarketingMessage_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_DeleteMarketingMessage_Request: _TypeAlias = CMarketingMessages_DeleteMarketingMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_DeleteMarketingMessage_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_DeleteMarketingMessage_Response: _TypeAlias = CMarketingMessages_DeleteMarketingMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_FindMarketingMessages_Request(_message.Message):

    LOOKUP_TYPE_FIELD_NUMBER: _builtins.int
    GID_FIELD_NUMBER: _builtins.int
    MESSAGE_TYPE_FIELD_NUMBER: _builtins.int
    GIDLIST_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    ASSOCIATED_ID_FIELD_NUMBER: _builtins.int
    lookup_type: Global___EMarketingMessageLookupType.ValueType
    gid: _builtins.int
    message_type: Global___EMarketingMessageType.ValueType
    title: _builtins.str
    associated_id: _builtins.int
    @_builtins.property
    def gidlist(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        lookup_type: Global___EMarketingMessageLookupType.ValueType | None = ...,
        gid: _builtins.int | None = ...,
        message_type: Global___EMarketingMessageType.ValueType | None = ...,
        gidlist: _abc.Iterable[_builtins.int] | None = ...,
        title: _builtins.str | None = ...,
        associated_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["associated_id", b"associated_id", "gid", b"gid", "lookup_type", b"lookup_type", "message_type", b"message_type", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["associated_id", b"associated_id", "gid", b"gid", "gidlist", b"gidlist", "lookup_type", b"lookup_type", "message_type", b"message_type", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_FindMarketingMessages_Request: _TypeAlias = CMarketingMessages_FindMarketingMessages_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_FindMarketingMessages_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageProto]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessageProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_FindMarketingMessages_Response: _TypeAlias = CMarketingMessages_FindMarketingMessages_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessageViewerStats_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessageViewerStats_Request: _TypeAlias = CMarketingMessages_GetMarketingMessageViewerStats_Request  # noqa: Y015

@_typing.final
class CMarketingMessageHourlyStats(_message.Message):

    RT_TIME_HOUR_FIELD_NUMBER: _builtins.int
    SEEN_COUNT_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    DISPLAY_INDEX_FIELD_NUMBER: _builtins.int
    rt_time_hour: _builtins.int
    seen_count: _builtins.int
    template_type: Global___EMarketingMessageTemplateType.ValueType
    display_index: _builtins.int
    def __init__(
        self,
        *,
        rt_time_hour: _builtins.int | None = ...,
        seen_count: _builtins.int | None = ...,
        template_type: Global___EMarketingMessageTemplateType.ValueType | None = ...,
        display_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["display_index", b"display_index", "rt_time_hour", b"rt_time_hour", "seen_count", b"seen_count", "template_type", b"template_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_index", b"display_index", "rt_time_hour", b"rt_time_hour", "seen_count", b"seen_count", "template_type", b"template_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessageHourlyStats: _TypeAlias = CMarketingMessageHourlyStats  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessageViewerStats_Response(_message.Message):

    STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageHourlyStats]: ...
    def __init__(
        self,
        *,
        stats: _abc.Iterable[Global___CMarketingMessageHourlyStats] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessageViewerStats_Response: _TypeAlias = CMarketingMessages_GetMarketingMessageViewerStats_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessagesViewerRangeStats_Request(_message.Message):

    RT_START_TIME_FIELD_NUMBER: _builtins.int
    RT_END_TIME_FIELD_NUMBER: _builtins.int
    rt_start_time: _builtins.int
    rt_end_time: _builtins.int
    def __init__(
        self,
        *,
        rt_start_time: _builtins.int | None = ...,
        rt_end_time: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rt_end_time", b"rt_end_time", "rt_start_time", b"rt_start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rt_end_time", b"rt_end_time", "rt_start_time", b"rt_start_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessagesViewerRangeStats_Request: _TypeAlias = CMarketingMessages_GetMarketingMessagesViewerRangeStats_Request  # noqa: Y015

@_typing.final
class CMarketingMessageClickedHourlyStats(_message.Message):

    RT_TIME_HOUR_FIELD_NUMBER: _builtins.int
    CLICKED_COUNT_FIELD_NUMBER: _builtins.int
    DISPLAY_INDEX_FIELD_NUMBER: _builtins.int
    TEMPLATE_TYPE_FIELD_NUMBER: _builtins.int
    CLICK_LOCATION_FIELD_NUMBER: _builtins.int
    rt_time_hour: _builtins.int
    clicked_count: _builtins.int
    display_index: _builtins.int
    template_type: Global___EMarketingMessageTemplateType.ValueType
    click_location: Global___EMarketingMessageClickLocation.ValueType
    def __init__(
        self,
        *,
        rt_time_hour: _builtins.int | None = ...,
        clicked_count: _builtins.int | None = ...,
        display_index: _builtins.int | None = ...,
        template_type: Global___EMarketingMessageTemplateType.ValueType | None = ...,
        click_location: Global___EMarketingMessageClickLocation.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["click_location", b"click_location", "clicked_count", b"clicked_count", "display_index", b"display_index", "rt_time_hour", b"rt_time_hour", "template_type", b"template_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["click_location", b"click_location", "clicked_count", b"clicked_count", "display_index", b"display_index", "rt_time_hour", b"rt_time_hour", "template_type", b"template_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessageClickedHourlyStats: _TypeAlias = CMarketingMessageClickedHourlyStats  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessagesViewerRangeStats_Response(_message.Message):

    STATS_FIELD_NUMBER: _builtins.int
    CLICKED_STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageHourlyStats]: ...
    @_builtins.property
    def clicked_stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageClickedHourlyStats]: ...
    def __init__(
        self,
        *,
        stats: _abc.Iterable[Global___CMarketingMessageHourlyStats] | None = ...,
        clicked_stats: _abc.Iterable[Global___CMarketingMessageClickedHourlyStats] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clicked_stats", b"clicked_stats", "stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessagesViewerRangeStats_Response: _TypeAlias = CMarketingMessages_GetMarketingMessagesViewerRangeStats_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessageClickedStats_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessageClickedStats_Request: _TypeAlias = CMarketingMessages_GetMarketingMessageClickedStats_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetMarketingMessageClickedStats_Response(_message.Message):

    STATS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageClickedHourlyStats]: ...
    def __init__(
        self,
        *,
        stats: _abc.Iterable[Global___CMarketingMessageClickedHourlyStats] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stats", b"stats"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetMarketingMessageClickedStats_Response: _TypeAlias = CMarketingMessages_GetMarketingMessageClickedStats_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPartnerReadyToPublishMessages_Request(_message.Message):

    PARTNERID_FIELD_NUMBER: _builtins.int
    partnerid: _builtins.int
    def __init__(
        self,
        *,
        partnerid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["partnerid", b"partnerid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["partnerid", b"partnerid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPartnerReadyToPublishMessages_Request: _TypeAlias = CMarketingMessages_GetPartnerReadyToPublishMessages_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPartnerReadyToPublishMessages_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CDisplayMarketingMessage]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CDisplayMarketingMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPartnerReadyToPublishMessages_Response: _TypeAlias = CMarketingMessages_GetPartnerReadyToPublishMessages_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_PartnerPublishMessage_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    PARTNERID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    partnerid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        partnerid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid", "partnerid", b"partnerid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid", "partnerid", b"partnerid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_PartnerPublishMessage_Request: _TypeAlias = CMarketingMessages_PartnerPublishMessage_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_PartnerPublishMessage_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_PartnerPublishMessage_Response: _TypeAlias = CMarketingMessages_PartnerPublishMessage_Response  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPartnerMessagePreview_Request(_message.Message):

    GID_FIELD_NUMBER: _builtins.int
    PARTNERID_FIELD_NUMBER: _builtins.int
    gid: _builtins.int
    partnerid: _builtins.int
    def __init__(
        self,
        *,
        gid: _builtins.int | None = ...,
        partnerid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid", "partnerid", b"partnerid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gid", b"gid", "partnerid", b"partnerid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPartnerMessagePreview_Request: _TypeAlias = CMarketingMessages_GetPartnerMessagePreview_Request  # noqa: Y015

@_typing.final
class CMarketingMessages_GetPartnerMessagePreview_Response(_message.Message):

    MESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def message(self) -> Global___CMarketingMessageProto: ...
    def __init__(
        self,
        *,
        message: Global___CMarketingMessageProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessages_GetPartnerMessagePreview_Response: _TypeAlias = CMarketingMessages_GetPartnerMessagePreview_Response  # noqa: Y015

@_typing.final
class CMarketingMessage_GetMarketingMessagesForPartner_Request(_message.Message):

    PARTNERID_FIELD_NUMBER: _builtins.int
    partnerid: _builtins.int
    def __init__(
        self,
        *,
        partnerid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["partnerid", b"partnerid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["partnerid", b"partnerid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessage_GetMarketingMessagesForPartner_Request: _TypeAlias = CMarketingMessage_GetMarketingMessagesForPartner_Request  # noqa: Y015

@_typing.final
class CMarketingMessage_GetMarketingMessagesForPartner_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageProto]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessageProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessage_GetMarketingMessagesForPartner_Response: _TypeAlias = CMarketingMessage_GetMarketingMessagesForPartner_Response  # noqa: Y015

@_typing.final
class CMarketingMessage_GetMarketingMessagesForApps_Request(_message.Message):

    APPIDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def appids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        appids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appids", b"appids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessage_GetMarketingMessagesForApps_Request: _TypeAlias = CMarketingMessage_GetMarketingMessagesForApps_Request  # noqa: Y015

@_typing.final
class CMarketingMessage_GetMarketingMessagesForApps_Response(_message.Message):

    MESSAGES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMarketingMessageProto]: ...
    def __init__(
        self,
        *,
        messages: _abc.Iterable[Global___CMarketingMessageProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMarketingMessage_GetMarketingMessagesForApps_Response: _TypeAlias = CMarketingMessage_GetMarketingMessagesForApps_Response  # noqa: Y015
