"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import steam.protobufs.enums_pb2 as _enums_pb2
import steam.protobufs.steammessages_client_objects_pb2 as _steammessages_client_objects_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CCloud_ClientLogUploadCheck_Notification(_message.Message):

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.int
    def __init__(
        self,
        *,
        client_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientLogUploadCheck_Notification: _TypeAlias = CCloud_ClientLogUploadCheck_Notification  # noqa: Y015

@_typing.final
class CCloud_ClientLogUploadComplete_Notification(_message.Message):

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    client_id: _builtins.int
    request_id: _builtins.int
    def __init__(
        self,
        *,
        client_id: _builtins.int | None = ...,
        request_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "request_id", b"request_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientLogUploadComplete_Notification: _TypeAlias = CCloud_ClientLogUploadComplete_Notification  # noqa: Y015

@_typing.final
class CCloud_BeginHTTPUpload_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    FILE_SIZE_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    IS_PUBLIC_FIELD_NUMBER: _builtins.int
    PLATFORMS_TO_SYNC_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_NAMES_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_VALUES_FIELD_NUMBER: _builtins.int
    UPLOAD_BATCH_ID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    file_size: _builtins.int
    filename: _builtins.str
    file_sha: _builtins.str
    is_public: _builtins.bool
    upload_batch_id: _builtins.int
    @_builtins.property
    def platforms_to_sync(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def request_headers_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def request_headers_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        file_size: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        file_sha: _builtins.str | None = ...,
        is_public: _builtins.bool | None = ...,
        platforms_to_sync: _abc.Iterable[_builtins.str] | None = ...,
        request_headers_names: _abc.Iterable[_builtins.str] | None = ...,
        request_headers_values: _abc.Iterable[_builtins.str] | None = ...,
        upload_batch_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "is_public", b"is_public", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "is_public", b"is_public", "platforms_to_sync", b"platforms_to_sync", "request_headers_names", b"request_headers_names", "request_headers_values", b"request_headers_values", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginHTTPUpload_Request: _TypeAlias = CCloud_BeginHTTPUpload_Request  # noqa: Y015

@_typing.final
class CCloud_BeginHTTPUpload_Response(_message.Message):

    @_typing.final
    class HTTPHeaders(_message.Message):

        NAME_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    UGCID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    URL_HOST_FIELD_NUMBER: _builtins.int
    URL_PATH_FIELD_NUMBER: _builtins.int
    USE_HTTPS_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_FIELD_NUMBER: _builtins.int
    ugcid: _builtins.int
    timestamp: _builtins.int
    url_host: _builtins.str
    url_path: _builtins.str
    use_https: _builtins.bool
    @_builtins.property
    def request_headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCloud_BeginHTTPUpload_Response.HTTPHeaders]: ...
    def __init__(
        self,
        *,
        ugcid: _builtins.int | None = ...,
        timestamp: _builtins.int | None = ...,
        url_host: _builtins.str | None = ...,
        url_path: _builtins.str | None = ...,
        use_https: _builtins.bool | None = ...,
        request_headers: _abc.Iterable[Global___CCloud_BeginHTTPUpload_Response.HTTPHeaders] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp", "ugcid", b"ugcid", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_headers", b"request_headers", "timestamp", b"timestamp", "ugcid", b"ugcid", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginHTTPUpload_Response: _TypeAlias = CCloud_BeginHTTPUpload_Response  # noqa: Y015

@_typing.final
class CCloud_CommitHTTPUpload_Request(_message.Message):

    TRANSFER_SUCCEEDED_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    transfer_succeeded: _builtins.bool
    appid: _builtins.int
    file_sha: _builtins.str
    filename: _builtins.str
    def __init__(
        self,
        *,
        transfer_succeeded: _builtins.bool | None = ...,
        appid: _builtins.int | None = ...,
        file_sha: _builtins.str | None = ...,
        filename: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "filename", b"filename", "transfer_succeeded", b"transfer_succeeded"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "filename", b"filename", "transfer_succeeded", b"transfer_succeeded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CommitHTTPUpload_Request: _TypeAlias = CCloud_CommitHTTPUpload_Request  # noqa: Y015

@_typing.final
class CCloud_CommitHTTPUpload_Response(_message.Message):

    FILE_COMMITTED_FIELD_NUMBER: _builtins.int
    file_committed: _builtins.bool
    def __init__(
        self,
        *,
        file_committed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CommitHTTPUpload_Response: _TypeAlias = CCloud_CommitHTTPUpload_Response  # noqa: Y015

@_typing.final
class CCloud_BeginUGCUpload_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    FILE_SIZE_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    file_size: _builtins.int
    filename: _builtins.str
    file_sha: _builtins.str
    content_type: _builtins.str
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        file_size: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        file_sha: _builtins.str | None = ...,
        content_type: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "content_type", b"content_type", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "content_type", b"content_type", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginUGCUpload_Request: _TypeAlias = CCloud_BeginUGCUpload_Request  # noqa: Y015

@_typing.final
class CCloud_BeginUGCUpload_Response(_message.Message):

    @_typing.final
    class HTTPHeaders(_message.Message):

        NAME_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    STORAGE_SYSTEM_FIELD_NUMBER: _builtins.int
    UGCID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    URL_HOST_FIELD_NUMBER: _builtins.int
    URL_PATH_FIELD_NUMBER: _builtins.int
    USE_HTTPS_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_FIELD_NUMBER: _builtins.int
    storage_system: _enums_pb2.EPublishedFileStorageSystem.ValueType
    ugcid: _builtins.int
    timestamp: _builtins.int
    url_host: _builtins.str
    url_path: _builtins.str
    use_https: _builtins.bool
    @_builtins.property
    def request_headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCloud_BeginUGCUpload_Response.HTTPHeaders]: ...
    def __init__(
        self,
        *,
        storage_system: _enums_pb2.EPublishedFileStorageSystem.ValueType | None = ...,
        ugcid: _builtins.int | None = ...,
        timestamp: _builtins.int | None = ...,
        url_host: _builtins.str | None = ...,
        url_path: _builtins.str | None = ...,
        use_https: _builtins.bool | None = ...,
        request_headers: _abc.Iterable[Global___CCloud_BeginUGCUpload_Response.HTTPHeaders] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["storage_system", b"storage_system", "timestamp", b"timestamp", "ugcid", b"ugcid", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_headers", b"request_headers", "storage_system", b"storage_system", "timestamp", b"timestamp", "ugcid", b"ugcid", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginUGCUpload_Response: _TypeAlias = CCloud_BeginUGCUpload_Response  # noqa: Y015

@_typing.final
class CCloud_CommitUGCUpload_Request(_message.Message):

    TRANSFER_SUCCEEDED_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    UGCID_FIELD_NUMBER: _builtins.int
    transfer_succeeded: _builtins.bool
    appid: _builtins.int
    ugcid: _builtins.int
    def __init__(
        self,
        *,
        transfer_succeeded: _builtins.bool | None = ...,
        appid: _builtins.int | None = ...,
        ugcid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "transfer_succeeded", b"transfer_succeeded", "ugcid", b"ugcid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "transfer_succeeded", b"transfer_succeeded", "ugcid", b"ugcid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CommitUGCUpload_Request: _TypeAlias = CCloud_CommitUGCUpload_Request  # noqa: Y015

@_typing.final
class CCloud_CommitUGCUpload_Response(_message.Message):

    FILE_COMMITTED_FIELD_NUMBER: _builtins.int
    file_committed: _builtins.bool
    def __init__(
        self,
        *,
        file_committed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CommitUGCUpload_Response: _TypeAlias = CCloud_CommitUGCUpload_Response  # noqa: Y015

@_typing.final
class CCloud_GetFileDetails_Request(_message.Message):

    UGCID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    ugcid: _builtins.int
    appid: _builtins.int
    def __init__(
        self,
        *,
        ugcid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "ugcid", b"ugcid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "ugcid", b"ugcid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetFileDetails_Request: _TypeAlias = CCloud_GetFileDetails_Request  # noqa: Y015

@_typing.final
class CCloud_UserFile(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    UGCID_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    FILE_SIZE_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    STEAMID_CREATOR_FIELD_NUMBER: _builtins.int
    FLAGS_FIELD_NUMBER: _builtins.int
    PLATFORMS_TO_SYNC_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    COMPRESSED_FILE_SIZE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    ugcid: _builtins.int
    filename: _builtins.str
    timestamp: _builtins.int
    file_size: _builtins.int
    url: _builtins.str
    steamid_creator: _builtins.int
    flags: _builtins.int
    file_sha: _builtins.str
    compressed_file_size: _builtins.int
    @_builtins.property
    def platforms_to_sync(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        ugcid: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        timestamp: _builtins.int | None = ...,
        file_size: _builtins.int | None = ...,
        url: _builtins.str | None = ...,
        steamid_creator: _builtins.int | None = ...,
        flags: _builtins.int | None = ...,
        platforms_to_sync: _abc.Iterable[_builtins.str] | None = ...,
        file_sha: _builtins.str | None = ...,
        compressed_file_size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "compressed_file_size", b"compressed_file_size", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "flags", b"flags", "steamid_creator", b"steamid_creator", "timestamp", b"timestamp", "ugcid", b"ugcid", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "compressed_file_size", b"compressed_file_size", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "flags", b"flags", "platforms_to_sync", b"platforms_to_sync", "steamid_creator", b"steamid_creator", "timestamp", b"timestamp", "ugcid", b"ugcid", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_UserFile: _TypeAlias = CCloud_UserFile  # noqa: Y015

@_typing.final
class CCloud_GetFileDetails_Response(_message.Message):

    DETAILS_FIELD_NUMBER: _builtins.int
    RANGECHECK_HOST_FIELD_NUMBER: _builtins.int
    rangecheck_host: _builtins.str
    @_builtins.property
    def details(self) -> Global___CCloud_UserFile: ...
    def __init__(
        self,
        *,
        details: Global___CCloud_UserFile | None = ...,
        rangecheck_host: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "rangecheck_host", b"rangecheck_host"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["details", b"details", "rangecheck_host", b"rangecheck_host"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetFileDetails_Response: _TypeAlias = CCloud_GetFileDetails_Response  # noqa: Y015

@_typing.final
class CCloud_GetSingleFileInfo_Request(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    FILE_NAME_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    file_name: _builtins.str
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        file_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetSingleFileInfo_Request: _TypeAlias = CCloud_GetSingleFileInfo_Request  # noqa: Y015

@_typing.final
class CCloud_GetSingleFileInfo_Response(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    FILE_NAME_FIELD_NUMBER: _builtins.int
    SHA_FILE_FIELD_NUMBER: _builtins.int
    TIME_STAMP_FIELD_NUMBER: _builtins.int
    RAW_FILE_SIZE_FIELD_NUMBER: _builtins.int
    IS_EXPLICIT_DELETE_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    file_name: _builtins.str
    sha_file: _builtins.bytes
    time_stamp: _builtins.int
    raw_file_size: _builtins.int
    is_explicit_delete: _builtins.bool
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        file_name: _builtins.str | None = ...,
        sha_file: _builtins.bytes | None = ...,
        time_stamp: _builtins.int | None = ...,
        raw_file_size: _builtins.int | None = ...,
        is_explicit_delete: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name", "is_explicit_delete", b"is_explicit_delete", "raw_file_size", b"raw_file_size", "sha_file", b"sha_file", "time_stamp", b"time_stamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name", "is_explicit_delete", b"is_explicit_delete", "raw_file_size", b"raw_file_size", "sha_file", b"sha_file", "time_stamp", b"time_stamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetSingleFileInfo_Response: _TypeAlias = CCloud_GetSingleFileInfo_Response  # noqa: Y015

@_typing.final
class CCloud_ShareFile_Request(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    FILE_NAME_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    file_name: _builtins.str
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        file_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "file_name", b"file_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ShareFile_Request: _TypeAlias = CCloud_ShareFile_Request  # noqa: Y015

@_typing.final
class CCloud_ShareFile_Response(_message.Message):

    HCONTENT_FIELD_NUMBER: _builtins.int
    hcontent: _builtins.int
    def __init__(
        self,
        *,
        hcontent: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["hcontent", b"hcontent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hcontent", b"hcontent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ShareFile_Response: _TypeAlias = CCloud_ShareFile_Response  # noqa: Y015

@_typing.final
class CCloud_EnumerateUserFiles_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    EXTENDED_DETAILS_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    START_INDEX_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    extended_details: _builtins.bool
    count: _builtins.int
    start_index: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        extended_details: _builtins.bool | None = ...,
        count: _builtins.int | None = ...,
        start_index: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "count", b"count", "extended_details", b"extended_details", "start_index", b"start_index"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "count", b"count", "extended_details", b"extended_details", "start_index", b"start_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_EnumerateUserFiles_Request: _TypeAlias = CCloud_EnumerateUserFiles_Request  # noqa: Y015

@_typing.final
class CCloud_EnumerateUserFiles_Response(_message.Message):

    FILES_FIELD_NUMBER: _builtins.int
    TOTAL_FILES_FIELD_NUMBER: _builtins.int
    total_files: _builtins.int
    @_builtins.property
    def files(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCloud_UserFile]: ...
    def __init__(
        self,
        *,
        files: _abc.Iterable[Global___CCloud_UserFile] | None = ...,
        total_files: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["total_files", b"total_files"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["files", b"files", "total_files", b"total_files"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_EnumerateUserFiles_Response: _TypeAlias = CCloud_EnumerateUserFiles_Response  # noqa: Y015

@_typing.final
class CCloud_Delete_Request(_message.Message):

    FILENAME_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    UPLOAD_BATCH_ID_FIELD_NUMBER: _builtins.int
    filename: _builtins.str
    appid: _builtins.int
    upload_batch_id: _builtins.int
    def __init__(
        self,
        *,
        filename: _builtins.str | None = ...,
        appid: _builtins.int | None = ...,
        upload_batch_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_Delete_Request: _TypeAlias = CCloud_Delete_Request  # noqa: Y015

@_typing.final
class CCloud_Delete_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_Delete_Response: _TypeAlias = CCloud_Delete_Response  # noqa: Y015

@_typing.final
class CCloud_GetClientEncryptionKey_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetClientEncryptionKey_Request: _TypeAlias = CCloud_GetClientEncryptionKey_Request  # noqa: Y015

@_typing.final
class CCloud_GetClientEncryptionKey_Response(_message.Message):

    KEY_FIELD_NUMBER: _builtins.int
    CRC_FIELD_NUMBER: _builtins.int
    key: _builtins.bytes
    crc: _builtins.int
    def __init__(
        self,
        *,
        key: _builtins.bytes | None = ...,
        crc: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["crc", b"crc", "key", b"key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crc", b"crc", "key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetClientEncryptionKey_Response: _TypeAlias = CCloud_GetClientEncryptionKey_Response  # noqa: Y015

@_typing.final
class CCloud_CDNReport_Notification(_message.Message):

    STEAMID_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    HTTP_STATUS_CODE_FIELD_NUMBER: _builtins.int
    EXPECTED_BYTES_FIELD_NUMBER: _builtins.int
    RECEIVED_BYTES_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    steamid: _builtins.int
    url: _builtins.str
    success: _builtins.bool
    http_status_code: _builtins.int
    expected_bytes: _builtins.int
    received_bytes: _builtins.int
    duration: _builtins.int
    def __init__(
        self,
        *,
        steamid: _builtins.int | None = ...,
        url: _builtins.str | None = ...,
        success: _builtins.bool | None = ...,
        http_status_code: _builtins.int | None = ...,
        expected_bytes: _builtins.int | None = ...,
        received_bytes: _builtins.int | None = ...,
        duration: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "expected_bytes", b"expected_bytes", "http_status_code", b"http_status_code", "received_bytes", b"received_bytes", "steamid", b"steamid", "success", b"success", "url", b"url"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "expected_bytes", b"expected_bytes", "http_status_code", b"http_status_code", "received_bytes", b"received_bytes", "steamid", b"steamid", "success", b"success", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CDNReport_Notification: _TypeAlias = CCloud_CDNReport_Notification  # noqa: Y015

@_typing.final
class CCloud_ExternalStorageTransferReport_Notification(_message.Message):

    HOST_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    IS_UPLOAD_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    HTTP_STATUS_CODE_FIELD_NUMBER: _builtins.int
    BYTES_EXPECTED_FIELD_NUMBER: _builtins.int
    BYTES_ACTUAL_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    CELLID_FIELD_NUMBER: _builtins.int
    PROXIED_FIELD_NUMBER: _builtins.int
    IPV6_LOCAL_FIELD_NUMBER: _builtins.int
    IPV6_REMOTE_FIELD_NUMBER: _builtins.int
    TIME_TO_CONNECT_MS_FIELD_NUMBER: _builtins.int
    TIME_TO_SEND_REQ_MS_FIELD_NUMBER: _builtins.int
    TIME_TO_FIRST_BYTE_MS_FIELD_NUMBER: _builtins.int
    TIME_TO_LAST_BYTE_MS_FIELD_NUMBER: _builtins.int
    host: _builtins.str
    path: _builtins.str
    is_upload: _builtins.bool
    success: _builtins.bool
    http_status_code: _builtins.int
    bytes_expected: _builtins.int
    bytes_actual: _builtins.int
    duration_ms: _builtins.int
    cellid: _builtins.int
    proxied: _builtins.bool
    ipv6_local: _builtins.bool
    ipv6_remote: _builtins.bool
    time_to_connect_ms: _builtins.int
    time_to_send_req_ms: _builtins.int
    time_to_first_byte_ms: _builtins.int
    time_to_last_byte_ms: _builtins.int
    def __init__(
        self,
        *,
        host: _builtins.str | None = ...,
        path: _builtins.str | None = ...,
        is_upload: _builtins.bool | None = ...,
        success: _builtins.bool | None = ...,
        http_status_code: _builtins.int | None = ...,
        bytes_expected: _builtins.int | None = ...,
        bytes_actual: _builtins.int | None = ...,
        duration_ms: _builtins.int | None = ...,
        cellid: _builtins.int | None = ...,
        proxied: _builtins.bool | None = ...,
        ipv6_local: _builtins.bool | None = ...,
        ipv6_remote: _builtins.bool | None = ...,
        time_to_connect_ms: _builtins.int | None = ...,
        time_to_send_req_ms: _builtins.int | None = ...,
        time_to_first_byte_ms: _builtins.int | None = ...,
        time_to_last_byte_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bytes_actual", b"bytes_actual", "bytes_expected", b"bytes_expected", "cellid", b"cellid", "duration_ms", b"duration_ms", "host", b"host", "http_status_code", b"http_status_code", "ipv6_local", b"ipv6_local", "ipv6_remote", b"ipv6_remote", "is_upload", b"is_upload", "path", b"path", "proxied", b"proxied", "success", b"success", "time_to_connect_ms", b"time_to_connect_ms", "time_to_first_byte_ms", b"time_to_first_byte_ms", "time_to_last_byte_ms", b"time_to_last_byte_ms", "time_to_send_req_ms", b"time_to_send_req_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_actual", b"bytes_actual", "bytes_expected", b"bytes_expected", "cellid", b"cellid", "duration_ms", b"duration_ms", "host", b"host", "http_status_code", b"http_status_code", "ipv6_local", b"ipv6_local", "ipv6_remote", b"ipv6_remote", "is_upload", b"is_upload", "path", b"path", "proxied", b"proxied", "success", b"success", "time_to_connect_ms", b"time_to_connect_ms", "time_to_first_byte_ms", b"time_to_first_byte_ms", "time_to_last_byte_ms", b"time_to_last_byte_ms", "time_to_send_req_ms", b"time_to_send_req_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ExternalStorageTransferReport_Notification: _TypeAlias = CCloud_ExternalStorageTransferReport_Notification  # noqa: Y015

@_typing.final
class CCloud_BeginAppUploadBatch_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    MACHINE_NAME_FIELD_NUMBER: _builtins.int
    FILES_TO_UPLOAD_FIELD_NUMBER: _builtins.int
    FILES_TO_DELETE_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    APP_BUILD_ID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    machine_name: _builtins.str
    client_id: _builtins.int
    app_build_id: _builtins.int
    @_builtins.property
    def files_to_upload(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def files_to_delete(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        machine_name: _builtins.str | None = ...,
        files_to_upload: _abc.Iterable[_builtins.str] | None = ...,
        files_to_delete: _abc.Iterable[_builtins.str] | None = ...,
        client_id: _builtins.int | None = ...,
        app_build_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_build_id", b"app_build_id", "appid", b"appid", "client_id", b"client_id", "machine_name", b"machine_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_build_id", b"app_build_id", "appid", b"appid", "client_id", b"client_id", "files_to_delete", b"files_to_delete", "files_to_upload", b"files_to_upload", "machine_name", b"machine_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginAppUploadBatch_Request: _TypeAlias = CCloud_BeginAppUploadBatch_Request  # noqa: Y015

@_typing.final
class CCloud_BeginAppUploadBatch_Response(_message.Message):

    BATCH_ID_FIELD_NUMBER: _builtins.int
    APP_CHANGE_NUMBER_FIELD_NUMBER: _builtins.int
    batch_id: _builtins.int
    app_change_number: _builtins.int
    def __init__(
        self,
        *,
        batch_id: _builtins.int | None = ...,
        app_change_number: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_change_number", b"app_change_number", "batch_id", b"batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_change_number", b"app_change_number", "batch_id", b"batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_BeginAppUploadBatch_Response: _TypeAlias = CCloud_BeginAppUploadBatch_Response  # noqa: Y015

@_typing.final
class CCloud_CompleteAppUploadBatch_Notification(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    BATCH_ID_FIELD_NUMBER: _builtins.int
    BATCH_ERESULT_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    batch_id: _builtins.int
    batch_eresult: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        batch_id: _builtins.int | None = ...,
        batch_eresult: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "batch_eresult", b"batch_eresult", "batch_id", b"batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "batch_eresult", b"batch_eresult", "batch_id", b"batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CompleteAppUploadBatch_Notification: _TypeAlias = CCloud_CompleteAppUploadBatch_Notification  # noqa: Y015

@_typing.final
class CCloud_CompleteAppUploadBatch_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    BATCH_ID_FIELD_NUMBER: _builtins.int
    BATCH_ERESULT_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    batch_id: _builtins.int
    batch_eresult: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        batch_id: _builtins.int | None = ...,
        batch_eresult: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "batch_eresult", b"batch_eresult", "batch_id", b"batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "batch_eresult", b"batch_eresult", "batch_id", b"batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CompleteAppUploadBatch_Request: _TypeAlias = CCloud_CompleteAppUploadBatch_Request  # noqa: Y015

@_typing.final
class CCloud_CompleteAppUploadBatch_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_CompleteAppUploadBatch_Response: _TypeAlias = CCloud_CompleteAppUploadBatch_Response  # noqa: Y015

@_typing.final
class CCloud_ClientBeginFileUpload_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    FILE_SIZE_FIELD_NUMBER: _builtins.int
    RAW_FILE_SIZE_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    TIME_STAMP_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    PLATFORMS_TO_SYNC_FIELD_NUMBER: _builtins.int
    CELL_ID_FIELD_NUMBER: _builtins.int
    CAN_ENCRYPT_FIELD_NUMBER: _builtins.int
    IS_SHARED_FILE_FIELD_NUMBER: _builtins.int
    DEPRECATED_REALM_FIELD_NUMBER: _builtins.int
    UPLOAD_BATCH_ID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    file_size: _builtins.int
    raw_file_size: _builtins.int
    file_sha: _builtins.bytes
    time_stamp: _builtins.int
    filename: _builtins.str
    platforms_to_sync: _builtins.int
    cell_id: _builtins.int
    can_encrypt: _builtins.bool
    is_shared_file: _builtins.bool
    deprecated_realm: _builtins.int
    upload_batch_id: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        file_size: _builtins.int | None = ...,
        raw_file_size: _builtins.int | None = ...,
        file_sha: _builtins.bytes | None = ...,
        time_stamp: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        platforms_to_sync: _builtins.int | None = ...,
        cell_id: _builtins.int | None = ...,
        can_encrypt: _builtins.bool | None = ...,
        is_shared_file: _builtins.bool | None = ...,
        deprecated_realm: _builtins.int | None = ...,
        upload_batch_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "can_encrypt", b"can_encrypt", "cell_id", b"cell_id", "deprecated_realm", b"deprecated_realm", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "is_shared_file", b"is_shared_file", "platforms_to_sync", b"platforms_to_sync", "raw_file_size", b"raw_file_size", "time_stamp", b"time_stamp", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "can_encrypt", b"can_encrypt", "cell_id", b"cell_id", "deprecated_realm", b"deprecated_realm", "file_sha", b"file_sha", "file_size", b"file_size", "filename", b"filename", "is_shared_file", b"is_shared_file", "platforms_to_sync", b"platforms_to_sync", "raw_file_size", b"raw_file_size", "time_stamp", b"time_stamp", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientBeginFileUpload_Request: _TypeAlias = CCloud_ClientBeginFileUpload_Request  # noqa: Y015

@_typing.final
class ClientCloudFileUploadBlockDetails(_message.Message):

    @_typing.final
    class HTTPHeaders(_message.Message):

        NAME_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    URL_HOST_FIELD_NUMBER: _builtins.int
    URL_PATH_FIELD_NUMBER: _builtins.int
    USE_HTTPS_FIELD_NUMBER: _builtins.int
    HTTP_METHOD_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_FIELD_NUMBER: _builtins.int
    BLOCK_OFFSET_FIELD_NUMBER: _builtins.int
    BLOCK_LENGTH_FIELD_NUMBER: _builtins.int
    EXPLICIT_BODY_DATA_FIELD_NUMBER: _builtins.int
    MAY_PARALLELIZE_FIELD_NUMBER: _builtins.int
    url_host: _builtins.str
    url_path: _builtins.str
    use_https: _builtins.bool
    http_method: _builtins.int
    block_offset: _builtins.int
    block_length: _builtins.int
    explicit_body_data: _builtins.bytes
    may_parallelize: _builtins.bool
    @_builtins.property
    def request_headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___ClientCloudFileUploadBlockDetails.HTTPHeaders]: ...
    def __init__(
        self,
        *,
        url_host: _builtins.str | None = ...,
        url_path: _builtins.str | None = ...,
        use_https: _builtins.bool | None = ...,
        http_method: _builtins.int | None = ...,
        request_headers: _abc.Iterable[Global___ClientCloudFileUploadBlockDetails.HTTPHeaders] | None = ...,
        block_offset: _builtins.int | None = ...,
        block_length: _builtins.int | None = ...,
        explicit_body_data: _builtins.bytes | None = ...,
        may_parallelize: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["block_length", b"block_length", "block_offset", b"block_offset", "explicit_body_data", b"explicit_body_data", "http_method", b"http_method", "may_parallelize", b"may_parallelize", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_length", b"block_length", "block_offset", b"block_offset", "explicit_body_data", b"explicit_body_data", "http_method", b"http_method", "may_parallelize", b"may_parallelize", "request_headers", b"request_headers", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClientCloudFileUploadBlockDetails: _TypeAlias = ClientCloudFileUploadBlockDetails  # noqa: Y015

@_typing.final
class CCloud_ClientBeginFileUpload_Response(_message.Message):

    ENCRYPT_FILE_FIELD_NUMBER: _builtins.int
    BLOCK_REQUESTS_FIELD_NUMBER: _builtins.int
    encrypt_file: _builtins.bool
    @_builtins.property
    def block_requests(self) -> _containers.RepeatedCompositeFieldContainer[Global___ClientCloudFileUploadBlockDetails]: ...
    def __init__(
        self,
        *,
        encrypt_file: _builtins.bool | None = ...,
        block_requests: _abc.Iterable[Global___ClientCloudFileUploadBlockDetails] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encrypt_file", b"encrypt_file"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_requests", b"block_requests", "encrypt_file", b"encrypt_file"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientBeginFileUpload_Response: _TypeAlias = CCloud_ClientBeginFileUpload_Response  # noqa: Y015

@_typing.final
class CCloud_ClientCommitFileUpload_Request(_message.Message):

    TRANSFER_SUCCEEDED_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    FILE_SHA_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    transfer_succeeded: _builtins.bool
    appid: _builtins.int
    file_sha: _builtins.bytes
    filename: _builtins.str
    def __init__(
        self,
        *,
        transfer_succeeded: _builtins.bool | None = ...,
        appid: _builtins.int | None = ...,
        file_sha: _builtins.bytes | None = ...,
        filename: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "filename", b"filename", "transfer_succeeded", b"transfer_succeeded"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "file_sha", b"file_sha", "filename", b"filename", "transfer_succeeded", b"transfer_succeeded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientCommitFileUpload_Request: _TypeAlias = CCloud_ClientCommitFileUpload_Request  # noqa: Y015

@_typing.final
class CCloud_ClientCommitFileUpload_Response(_message.Message):

    FILE_COMMITTED_FIELD_NUMBER: _builtins.int
    file_committed: _builtins.bool
    def __init__(
        self,
        *,
        file_committed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_committed", b"file_committed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientCommitFileUpload_Response: _TypeAlias = CCloud_ClientCommitFileUpload_Response  # noqa: Y015

@_typing.final
class CCloud_ClientFileDownload_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    REALM_FIELD_NUMBER: _builtins.int
    FORCE_PROXY_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    filename: _builtins.str
    realm: _builtins.int
    force_proxy: _builtins.bool
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        realm: _builtins.int | None = ...,
        force_proxy: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "force_proxy", b"force_proxy", "realm", b"realm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "force_proxy", b"force_proxy", "realm", b"realm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientFileDownload_Request: _TypeAlias = CCloud_ClientFileDownload_Request  # noqa: Y015

@_typing.final
class CCloud_ClientFileDownload_Response(_message.Message):

    @_typing.final
    class HTTPHeaders(_message.Message):

        NAME_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    APPID_FIELD_NUMBER: _builtins.int
    FILE_SIZE_FIELD_NUMBER: _builtins.int
    RAW_FILE_SIZE_FIELD_NUMBER: _builtins.int
    SHA_FILE_FIELD_NUMBER: _builtins.int
    TIME_STAMP_FIELD_NUMBER: _builtins.int
    IS_EXPLICIT_DELETE_FIELD_NUMBER: _builtins.int
    URL_HOST_FIELD_NUMBER: _builtins.int
    URL_PATH_FIELD_NUMBER: _builtins.int
    USE_HTTPS_FIELD_NUMBER: _builtins.int
    REQUEST_HEADERS_FIELD_NUMBER: _builtins.int
    ENCRYPTED_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    file_size: _builtins.int
    raw_file_size: _builtins.int
    sha_file: _builtins.bytes
    time_stamp: _builtins.int
    is_explicit_delete: _builtins.bool
    url_host: _builtins.str
    url_path: _builtins.str
    use_https: _builtins.bool
    encrypted: _builtins.bool
    @_builtins.property
    def request_headers(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCloud_ClientFileDownload_Response.HTTPHeaders]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        file_size: _builtins.int | None = ...,
        raw_file_size: _builtins.int | None = ...,
        sha_file: _builtins.bytes | None = ...,
        time_stamp: _builtins.int | None = ...,
        is_explicit_delete: _builtins.bool | None = ...,
        url_host: _builtins.str | None = ...,
        url_path: _builtins.str | None = ...,
        use_https: _builtins.bool | None = ...,
        request_headers: _abc.Iterable[Global___CCloud_ClientFileDownload_Response.HTTPHeaders] | None = ...,
        encrypted: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "encrypted", b"encrypted", "file_size", b"file_size", "is_explicit_delete", b"is_explicit_delete", "raw_file_size", b"raw_file_size", "sha_file", b"sha_file", "time_stamp", b"time_stamp", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "encrypted", b"encrypted", "file_size", b"file_size", "is_explicit_delete", b"is_explicit_delete", "raw_file_size", b"raw_file_size", "request_headers", b"request_headers", "sha_file", b"sha_file", "time_stamp", b"time_stamp", "url_host", b"url_host", "url_path", b"url_path", "use_https", b"use_https"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientFileDownload_Response: _TypeAlias = CCloud_ClientFileDownload_Response  # noqa: Y015

@_typing.final
class CCloud_ClientDeleteFile_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    IS_EXPLICIT_DELETE_FIELD_NUMBER: _builtins.int
    UPLOAD_BATCH_ID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    filename: _builtins.str
    is_explicit_delete: _builtins.bool
    upload_batch_id: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        filename: _builtins.str | None = ...,
        is_explicit_delete: _builtins.bool | None = ...,
        upload_batch_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "is_explicit_delete", b"is_explicit_delete", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "filename", b"filename", "is_explicit_delete", b"is_explicit_delete", "upload_batch_id", b"upload_batch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientDeleteFile_Request: _TypeAlias = CCloud_ClientDeleteFile_Request  # noqa: Y015

@_typing.final
class CCloud_ClientDeleteFile_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientDeleteFile_Response: _TypeAlias = CCloud_ClientDeleteFile_Response  # noqa: Y015

@_typing.final
class CCloud_ClientConflictResolution_Notification(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CHOSE_LOCAL_FILES_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    chose_local_files: _builtins.bool
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        chose_local_files: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "chose_local_files", b"chose_local_files"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "chose_local_files", b"chose_local_files"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientConflictResolution_Notification: _TypeAlias = CCloud_ClientConflictResolution_Notification  # noqa: Y015

@_typing.final
class CCloud_GetAppFileChangelist_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    SYNCED_CHANGE_NUMBER_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    synced_change_number: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        synced_change_number: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "synced_change_number", b"synced_change_number"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "synced_change_number", b"synced_change_number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetAppFileChangelist_Request: _TypeAlias = CCloud_GetAppFileChangelist_Request  # noqa: Y015

@_typing.final
class CCloud_AppFileInfo(_message.Message):

    FILE_NAME_FIELD_NUMBER: _builtins.int
    SHA_FILE_FIELD_NUMBER: _builtins.int
    TIME_STAMP_FIELD_NUMBER: _builtins.int
    RAW_FILE_SIZE_FIELD_NUMBER: _builtins.int
    PERSIST_STATE_FIELD_NUMBER: _builtins.int
    PLATFORMS_TO_SYNC_FIELD_NUMBER: _builtins.int
    PATH_PREFIX_INDEX_FIELD_NUMBER: _builtins.int
    MACHINE_NAME_INDEX_FIELD_NUMBER: _builtins.int
    REUPLOAD_REQUESTED_FIELD_NUMBER: _builtins.int
    file_name: _builtins.str
    sha_file: _builtins.bytes
    time_stamp: _builtins.int
    raw_file_size: _builtins.int
    persist_state: _enums_pb2.ECloudStoragePersistState.ValueType
    platforms_to_sync: _builtins.int
    path_prefix_index: _builtins.int
    machine_name_index: _builtins.int
    reupload_requested: _builtins.bool
    def __init__(
        self,
        *,
        file_name: _builtins.str | None = ...,
        sha_file: _builtins.bytes | None = ...,
        time_stamp: _builtins.int | None = ...,
        raw_file_size: _builtins.int | None = ...,
        persist_state: _enums_pb2.ECloudStoragePersistState.ValueType | None = ...,
        platforms_to_sync: _builtins.int | None = ...,
        path_prefix_index: _builtins.int | None = ...,
        machine_name_index: _builtins.int | None = ...,
        reupload_requested: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["file_name", b"file_name", "machine_name_index", b"machine_name_index", "path_prefix_index", b"path_prefix_index", "persist_state", b"persist_state", "platforms_to_sync", b"platforms_to_sync", "raw_file_size", b"raw_file_size", "reupload_requested", b"reupload_requested", "sha_file", b"sha_file", "time_stamp", b"time_stamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_name", b"file_name", "machine_name_index", b"machine_name_index", "path_prefix_index", b"path_prefix_index", "persist_state", b"persist_state", "platforms_to_sync", b"platforms_to_sync", "raw_file_size", b"raw_file_size", "reupload_requested", b"reupload_requested", "sha_file", b"sha_file", "time_stamp", b"time_stamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppFileInfo: _TypeAlias = CCloud_AppFileInfo  # noqa: Y015

@_typing.final
class CCloud_GetAppFileChangelist_Response(_message.Message):

    CURRENT_CHANGE_NUMBER_FIELD_NUMBER: _builtins.int
    FILES_FIELD_NUMBER: _builtins.int
    IS_ONLY_DELTA_FIELD_NUMBER: _builtins.int
    PATH_PREFIXES_FIELD_NUMBER: _builtins.int
    MACHINE_NAMES_FIELD_NUMBER: _builtins.int
    APP_BUILDID_HWM_FIELD_NUMBER: _builtins.int
    current_change_number: _builtins.int
    is_only_delta: _builtins.bool
    app_buildid_hwm: _builtins.int
    @_builtins.property
    def files(self) -> _containers.RepeatedCompositeFieldContainer[Global___CCloud_AppFileInfo]: ...
    @_builtins.property
    def path_prefixes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def machine_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        current_change_number: _builtins.int | None = ...,
        files: _abc.Iterable[Global___CCloud_AppFileInfo] | None = ...,
        is_only_delta: _builtins.bool | None = ...,
        path_prefixes: _abc.Iterable[_builtins.str] | None = ...,
        machine_names: _abc.Iterable[_builtins.str] | None = ...,
        app_buildid_hwm: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_buildid_hwm", b"app_buildid_hwm", "current_change_number", b"current_change_number", "is_only_delta", b"is_only_delta"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_buildid_hwm", b"app_buildid_hwm", "current_change_number", b"current_change_number", "files", b"files", "is_only_delta", b"is_only_delta", "machine_names", b"machine_names", "path_prefixes", b"path_prefixes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_GetAppFileChangelist_Response: _TypeAlias = CCloud_GetAppFileChangelist_Response  # noqa: Y015

@_typing.final
class CCloud_AppSessionSuspend_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    MACHINE_NAME_FIELD_NUMBER: _builtins.int
    CLOUD_SYNC_COMPLETED_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    client_id: _builtins.int
    machine_name: _builtins.str
    cloud_sync_completed: _builtins.bool
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        client_id: _builtins.int | None = ...,
        machine_name: _builtins.str | None = ...,
        cloud_sync_completed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "cloud_sync_completed", b"cloud_sync_completed", "machine_name", b"machine_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "cloud_sync_completed", b"cloud_sync_completed", "machine_name", b"machine_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppSessionSuspend_Request: _TypeAlias = CCloud_AppSessionSuspend_Request  # noqa: Y015

@_typing.final
class CCloud_AppSessionSuspend_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppSessionSuspend_Response: _TypeAlias = CCloud_AppSessionSuspend_Response  # noqa: Y015

@_typing.final
class CCloud_AppSessionResume_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    client_id: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        client_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppSessionResume_Request: _TypeAlias = CCloud_AppSessionResume_Request  # noqa: Y015

@_typing.final
class CCloud_AppSessionResume_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppSessionResume_Response: _TypeAlias = CCloud_AppSessionResume_Response  # noqa: Y015

@_typing.final
class CCloud_AppLaunchIntent_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    MACHINE_NAME_FIELD_NUMBER: _builtins.int
    IGNORE_PENDING_OPERATIONS_FIELD_NUMBER: _builtins.int
    OS_TYPE_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    client_id: _builtins.int
    machine_name: _builtins.str
    ignore_pending_operations: _builtins.bool
    os_type: _builtins.int
    device_type: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        client_id: _builtins.int | None = ...,
        machine_name: _builtins.str | None = ...,
        ignore_pending_operations: _builtins.bool | None = ...,
        os_type: _builtins.int | None = ...,
        device_type: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "device_type", b"device_type", "ignore_pending_operations", b"ignore_pending_operations", "machine_name", b"machine_name", "os_type", b"os_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "device_type", b"device_type", "ignore_pending_operations", b"ignore_pending_operations", "machine_name", b"machine_name", "os_type", b"os_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppLaunchIntent_Request: _TypeAlias = CCloud_AppLaunchIntent_Request  # noqa: Y015

@_typing.final
class CCloud_AppLaunchIntent_Response(_message.Message):

    PENDING_REMOTE_OPERATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pending_remote_operations(self) -> _containers.RepeatedCompositeFieldContainer[_steammessages_client_objects_pb2.CCloud_PendingRemoteOperation]: ...
    def __init__(
        self,
        *,
        pending_remote_operations: _abc.Iterable[_steammessages_client_objects_pb2.CCloud_PendingRemoteOperation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pending_remote_operations", b"pending_remote_operations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppLaunchIntent_Response: _TypeAlias = CCloud_AppLaunchIntent_Response  # noqa: Y015

@_typing.final
class CCloud_AppExitSyncDone_Notification(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    UPLOADS_COMPLETED_FIELD_NUMBER: _builtins.int
    UPLOADS_REQUIRED_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    client_id: _builtins.int
    uploads_completed: _builtins.bool
    uploads_required: _builtins.bool
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        client_id: _builtins.int | None = ...,
        uploads_completed: _builtins.bool | None = ...,
        uploads_required: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "uploads_completed", b"uploads_completed", "uploads_required", b"uploads_required"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "client_id", b"client_id", "uploads_completed", b"uploads_completed", "uploads_required", b"uploads_required"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppExitSyncDone_Notification: _TypeAlias = CCloud_AppExitSyncDone_Notification  # noqa: Y015

@_typing.final
class CCloud_ClientGetAppQuotaUsage_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientGetAppQuotaUsage_Request: _TypeAlias = CCloud_ClientGetAppQuotaUsage_Request  # noqa: Y015

@_typing.final
class CCloud_ClientGetAppQuotaUsage_Response(_message.Message):

    EXISTING_FILES_FIELD_NUMBER: _builtins.int
    EXISTING_BYTES_FIELD_NUMBER: _builtins.int
    MAX_NUM_FILES_FIELD_NUMBER: _builtins.int
    MAX_NUM_BYTES_FIELD_NUMBER: _builtins.int
    existing_files: _builtins.int
    existing_bytes: _builtins.int
    max_num_files: _builtins.int
    max_num_bytes: _builtins.int
    def __init__(
        self,
        *,
        existing_files: _builtins.int | None = ...,
        existing_bytes: _builtins.int | None = ...,
        max_num_files: _builtins.int | None = ...,
        max_num_bytes: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["existing_bytes", b"existing_bytes", "existing_files", b"existing_files", "max_num_bytes", b"max_num_bytes", "max_num_files", b"max_num_files"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["existing_bytes", b"existing_bytes", "existing_files", b"existing_files", "max_num_bytes", b"max_num_bytes", "max_num_files", b"max_num_files"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientGetAppQuotaUsage_Response: _TypeAlias = CCloud_ClientGetAppQuotaUsage_Response  # noqa: Y015

@_typing.final
class CCloud_AppCloudStateChange_Notification(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    APP_CHANGE_NUMBER_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    app_change_number: _builtins.int
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        app_change_number: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_change_number", b"app_change_number", "appid", b"appid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_change_number", b"app_change_number", "appid", b"appid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_AppCloudStateChange_Notification: _TypeAlias = CCloud_AppCloudStateChange_Notification  # noqa: Y015

@_typing.final
class CCloud_ClientLogUploadRequest_Notification(_message.Message):

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    def __init__(
        self,
        *,
        request_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CCloud_ClientLogUploadRequest_Notification: _TypeAlias = CCloud_ClientLogUploadRequest_Notification  # noqa: Y015
