"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CGameRecording_AudioSessionsChanged_Notification(_message.Message):

    @_typing.final
    class Session(_message.Message):

        ID_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        IS_SYSTEM_FIELD_NUMBER: _builtins.int
        IS_MUTED_FIELD_NUMBER: _builtins.int
        IS_ACTIVE_FIELD_NUMBER: _builtins.int
        IS_CAPTURED_FIELD_NUMBER: _builtins.int
        RECENT_PEAK_FIELD_NUMBER: _builtins.int
        IS_GAME_FIELD_NUMBER: _builtins.int
        IS_STEAM_FIELD_NUMBER: _builtins.int
        IS_SAVED_FIELD_NUMBER: _builtins.int
        id: _builtins.str
        name: _builtins.str
        is_system: _builtins.bool
        is_muted: _builtins.bool
        is_active: _builtins.bool
        is_captured: _builtins.bool
        recent_peak: _builtins.float
        is_game: _builtins.bool
        is_steam: _builtins.bool
        is_saved: _builtins.bool
        def __init__(
            self,
            *,
            id: _builtins.str | None = ...,
            name: _builtins.str | None = ...,
            is_system: _builtins.bool | None = ...,
            is_muted: _builtins.bool | None = ...,
            is_active: _builtins.bool | None = ...,
            is_captured: _builtins.bool | None = ...,
            recent_peak: _builtins.float | None = ...,
            is_game: _builtins.bool | None = ...,
            is_steam: _builtins.bool | None = ...,
            is_saved: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_active", b"is_active", "is_captured", b"is_captured", "is_game", b"is_game", "is_muted", b"is_muted", "is_saved", b"is_saved", "is_steam", b"is_steam", "is_system", b"is_system", "name", b"name", "recent_peak", b"recent_peak"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_active", b"is_active", "is_captured", b"is_captured", "is_game", b"is_game", "is_muted", b"is_muted", "is_saved", b"is_saved", "is_steam", b"is_steam", "is_system", b"is_system", "name", b"name", "recent_peak", b"recent_peak"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SESSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameRecording_AudioSessionsChanged_Notification.Session]: ...
    def __init__(
        self,
        *,
        sessions: _abc.Iterable[Global___CGameRecording_AudioSessionsChanged_Notification.Session] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sessions", b"sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameRecording_AudioSessionsChanged_Notification: _TypeAlias = CGameRecording_AudioSessionsChanged_Notification  # noqa: Y015
