"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _EHIDDeviceLocation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EHIDDeviceLocationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EHIDDeviceLocation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EDeviceLocationLocal: _EHIDDeviceLocation.ValueType  # 0
    k_EDeviceLocationRemote: _EHIDDeviceLocation.ValueType  # 2
    k_EDeviceLocationAny: _EHIDDeviceLocation.ValueType  # 3

class EHIDDeviceLocation(_EHIDDeviceLocation, metaclass=_EHIDDeviceLocationEnumTypeWrapper): ...

k_EDeviceLocationLocal: EHIDDeviceLocation.ValueType  # 0
k_EDeviceLocationRemote: EHIDDeviceLocation.ValueType  # 2
k_EDeviceLocationAny: EHIDDeviceLocation.ValueType  # 3
Global___EHIDDeviceLocation: _TypeAlias = EHIDDeviceLocation  # noqa: Y015

class _EHIDDeviceDisconnectMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EHIDDeviceDisconnectMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EHIDDeviceDisconnectMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EDeviceDisconnectMethodUnknown: _EHIDDeviceDisconnectMethod.ValueType  # 0
    k_EDeviceDisconnectMethodBluetooth: _EHIDDeviceDisconnectMethod.ValueType  # 1
    k_EDeviceDisconnectMethodFeatureReport: _EHIDDeviceDisconnectMethod.ValueType  # 2
    k_EDeviceDisconnectMethodOutputReport: _EHIDDeviceDisconnectMethod.ValueType  # 3

class EHIDDeviceDisconnectMethod(_EHIDDeviceDisconnectMethod, metaclass=_EHIDDeviceDisconnectMethodEnumTypeWrapper): ...

k_EDeviceDisconnectMethodUnknown: EHIDDeviceDisconnectMethod.ValueType  # 0
k_EDeviceDisconnectMethodBluetooth: EHIDDeviceDisconnectMethod.ValueType  # 1
k_EDeviceDisconnectMethodFeatureReport: EHIDDeviceDisconnectMethod.ValueType  # 2
k_EDeviceDisconnectMethodOutputReport: EHIDDeviceDisconnectMethod.ValueType  # 3
Global___EHIDDeviceDisconnectMethod: _TypeAlias = EHIDDeviceDisconnectMethod  # noqa: Y015

@_typing.final
class CHIDDeviceInfo(_message.Message):

    LOCATION_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    VENDOR_ID_FIELD_NUMBER: _builtins.int
    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    RELEASE_NUMBER_FIELD_NUMBER: _builtins.int
    MANUFACTURER_STRING_FIELD_NUMBER: _builtins.int
    PRODUCT_STRING_FIELD_NUMBER: _builtins.int
    USAGE_PAGE_FIELD_NUMBER: _builtins.int
    USAGE_FIELD_NUMBER: _builtins.int
    INTERFACE_NUMBER_FIELD_NUMBER: _builtins.int
    OSTYPE_FIELD_NUMBER: _builtins.int
    IS_GENERIC_GAMEPAD_FIELD_NUMBER: _builtins.int
    IS_GENERIC_JOYSTICK_FIELD_NUMBER: _builtins.int
    CAPS_BITS_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    ECONTROLLERTYPE_OBSOLETE_FIELD_NUMBER: _builtins.int
    IS_XINPUT_DEVICE_OBSOLETE_FIELD_NUMBER: _builtins.int
    SESSION_REMOTE_PLAY_TOGETHER_APPID_FIELD_NUMBER: _builtins.int
    IS_STEAMVR_DEVICE_FIELD_NUMBER: _builtins.int
    CAPS_BITS2_FIELD_NUMBER: _builtins.int
    location: Global___EHIDDeviceLocation.ValueType
    path: _builtins.str
    vendor_id: _builtins.int
    product_id: _builtins.int
    serial_number: _builtins.str
    release_number: _builtins.int
    manufacturer_string: _builtins.str
    product_string: _builtins.str
    usage_page: _builtins.int
    usage: _builtins.int
    interface_number: _builtins.int
    ostype: _builtins.int
    is_generic_gamepad: _builtins.bool
    is_generic_joystick: _builtins.bool
    caps_bits: _builtins.int
    session_id: _builtins.int
    eControllerType_OBSOLETE: _builtins.int
    is_xinput_device_OBSOLETE: _builtins.bool
    session_remote_play_together_appid: _builtins.int
    is_steamvr_device: _builtins.bool
    caps_bits2: _builtins.int
    def __init__(
        self,
        *,
        location: Global___EHIDDeviceLocation.ValueType | None = ...,
        path: _builtins.str | None = ...,
        vendor_id: _builtins.int | None = ...,
        product_id: _builtins.int | None = ...,
        serial_number: _builtins.str | None = ...,
        release_number: _builtins.int | None = ...,
        manufacturer_string: _builtins.str | None = ...,
        product_string: _builtins.str | None = ...,
        usage_page: _builtins.int | None = ...,
        usage: _builtins.int | None = ...,
        interface_number: _builtins.int | None = ...,
        ostype: _builtins.int | None = ...,
        is_generic_gamepad: _builtins.bool | None = ...,
        is_generic_joystick: _builtins.bool | None = ...,
        caps_bits: _builtins.int | None = ...,
        session_id: _builtins.int | None = ...,
        eControllerType_OBSOLETE: _builtins.int | None = ...,
        is_xinput_device_OBSOLETE: _builtins.bool | None = ...,
        session_remote_play_together_appid: _builtins.int | None = ...,
        is_steamvr_device: _builtins.bool | None = ...,
        caps_bits2: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["caps_bits", b"caps_bits", "caps_bits2", b"caps_bits2", "eControllerType_OBSOLETE", b"eControllerType_OBSOLETE", "interface_number", b"interface_number", "is_generic_gamepad", b"is_generic_gamepad", "is_generic_joystick", b"is_generic_joystick", "is_steamvr_device", b"is_steamvr_device", "is_xinput_device_OBSOLETE", b"is_xinput_device_OBSOLETE", "location", b"location", "manufacturer_string", b"manufacturer_string", "ostype", b"ostype", "path", b"path", "product_id", b"product_id", "product_string", b"product_string", "release_number", b"release_number", "serial_number", b"serial_number", "session_id", b"session_id", "session_remote_play_together_appid", b"session_remote_play_together_appid", "usage", b"usage", "usage_page", b"usage_page", "vendor_id", b"vendor_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["caps_bits", b"caps_bits", "caps_bits2", b"caps_bits2", "eControllerType_OBSOLETE", b"eControllerType_OBSOLETE", "interface_number", b"interface_number", "is_generic_gamepad", b"is_generic_gamepad", "is_generic_joystick", b"is_generic_joystick", "is_steamvr_device", b"is_steamvr_device", "is_xinput_device_OBSOLETE", b"is_xinput_device_OBSOLETE", "location", b"location", "manufacturer_string", b"manufacturer_string", "ostype", b"ostype", "path", b"path", "product_id", b"product_id", "product_string", b"product_string", "release_number", b"release_number", "serial_number", b"serial_number", "session_id", b"session_id", "session_remote_play_together_appid", b"session_remote_play_together_appid", "usage", b"usage", "usage_page", b"usage_page", "vendor_id", b"vendor_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CHIDDeviceInfo: _TypeAlias = CHIDDeviceInfo  # noqa: Y015

@_typing.final
class CHIDDeviceInputReport(_message.Message):

    FULL_REPORT_FIELD_NUMBER: _builtins.int
    DELTA_REPORT_FIELD_NUMBER: _builtins.int
    DELTA_REPORT_SIZE_FIELD_NUMBER: _builtins.int
    DELTA_REPORT_CRC_FIELD_NUMBER: _builtins.int
    full_report: _builtins.bytes
    delta_report: _builtins.bytes
    delta_report_size: _builtins.int
    delta_report_crc: _builtins.int
    def __init__(
        self,
        *,
        full_report: _builtins.bytes | None = ...,
        delta_report: _builtins.bytes | None = ...,
        delta_report_size: _builtins.int | None = ...,
        delta_report_crc: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["delta_report", b"delta_report", "delta_report_crc", b"delta_report_crc", "delta_report_size", b"delta_report_size", "full_report", b"full_report"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delta_report", b"delta_report", "delta_report_crc", b"delta_report_crc", "delta_report_size", b"delta_report_size", "full_report", b"full_report"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CHIDDeviceInputReport: _TypeAlias = CHIDDeviceInputReport  # noqa: Y015

@_typing.final
class CHIDMessageToRemote(_message.Message):

    @_typing.final
    class DeviceOpen(_message.Message):

        INFO_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def info(self) -> Global___CHIDDeviceInfo: ...
        def __init__(
            self,
            *,
            info: Global___CHIDDeviceInfo | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceClose(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceWrite(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        data: _builtins.bytes
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            data: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceRead(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        LENGTH_FIELD_NUMBER: _builtins.int
        TIMEOUT_MS_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        length: _builtins.int
        timeout_ms: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            length: _builtins.int | None = ...,
            timeout_ms: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length", "timeout_ms", b"timeout_ms"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length", "timeout_ms", b"timeout_ms"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceSendFeatureReport(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        data: _builtins.bytes
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            data: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceGetFeatureReport(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        REPORT_NUMBER_FIELD_NUMBER: _builtins.int
        LENGTH_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        report_number: _builtins.bytes
        length: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            report_number: _builtins.bytes | None = ...,
            length: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length", "report_number", b"report_number"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length", "report_number", b"report_number"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceGetVendorString(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceGetProductString(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceGetSerialNumberString(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceStartInputReports(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        LENGTH_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        length: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            length: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "length", b"length"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceRequestFullReport(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceDisconnect(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        DISCONNECTMETHOD_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        disconnectMethod: Global___EHIDDeviceDisconnectMethod.ValueType
        data: _builtins.bytes
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
            disconnectMethod: Global___EHIDDeviceDisconnectMethod.ValueType | None = ...,
            data: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device", "disconnectMethod", b"disconnectMethod"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "device", b"device", "disconnectMethod", b"disconnectMethod"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    DEVICE_OPEN_FIELD_NUMBER: _builtins.int
    DEVICE_CLOSE_FIELD_NUMBER: _builtins.int
    DEVICE_WRITE_FIELD_NUMBER: _builtins.int
    DEVICE_READ_FIELD_NUMBER: _builtins.int
    DEVICE_SEND_FEATURE_REPORT_FIELD_NUMBER: _builtins.int
    DEVICE_GET_FEATURE_REPORT_FIELD_NUMBER: _builtins.int
    DEVICE_GET_VENDOR_STRING_FIELD_NUMBER: _builtins.int
    DEVICE_GET_PRODUCT_STRING_FIELD_NUMBER: _builtins.int
    DEVICE_GET_SERIAL_NUMBER_STRING_FIELD_NUMBER: _builtins.int
    DEVICE_START_INPUT_REPORTS_FIELD_NUMBER: _builtins.int
    DEVICE_REQUEST_FULL_REPORT_FIELD_NUMBER: _builtins.int
    DEVICE_DISCONNECT_FIELD_NUMBER: _builtins.int
    request_id: _builtins.int
    @_builtins.property
    def device_open(self) -> Global___CHIDMessageToRemote.DeviceOpen: ...
    @_builtins.property
    def device_close(self) -> Global___CHIDMessageToRemote.DeviceClose: ...
    @_builtins.property
    def device_write(self) -> Global___CHIDMessageToRemote.DeviceWrite: ...
    @_builtins.property
    def device_read(self) -> Global___CHIDMessageToRemote.DeviceRead: ...
    @_builtins.property
    def device_send_feature_report(self) -> Global___CHIDMessageToRemote.DeviceSendFeatureReport: ...
    @_builtins.property
    def device_get_feature_report(self) -> Global___CHIDMessageToRemote.DeviceGetFeatureReport: ...
    @_builtins.property
    def device_get_vendor_string(self) -> Global___CHIDMessageToRemote.DeviceGetVendorString: ...
    @_builtins.property
    def device_get_product_string(self) -> Global___CHIDMessageToRemote.DeviceGetProductString: ...
    @_builtins.property
    def device_get_serial_number_string(self) -> Global___CHIDMessageToRemote.DeviceGetSerialNumberString: ...
    @_builtins.property
    def device_start_input_reports(self) -> Global___CHIDMessageToRemote.DeviceStartInputReports: ...
    @_builtins.property
    def device_request_full_report(self) -> Global___CHIDMessageToRemote.DeviceRequestFullReport: ...
    @_builtins.property
    def device_disconnect(self) -> Global___CHIDMessageToRemote.DeviceDisconnect: ...
    def __init__(
        self,
        *,
        request_id: _builtins.int | None = ...,
        device_open: Global___CHIDMessageToRemote.DeviceOpen | None = ...,
        device_close: Global___CHIDMessageToRemote.DeviceClose | None = ...,
        device_write: Global___CHIDMessageToRemote.DeviceWrite | None = ...,
        device_read: Global___CHIDMessageToRemote.DeviceRead | None = ...,
        device_send_feature_report: Global___CHIDMessageToRemote.DeviceSendFeatureReport | None = ...,
        device_get_feature_report: Global___CHIDMessageToRemote.DeviceGetFeatureReport | None = ...,
        device_get_vendor_string: Global___CHIDMessageToRemote.DeviceGetVendorString | None = ...,
        device_get_product_string: Global___CHIDMessageToRemote.DeviceGetProductString | None = ...,
        device_get_serial_number_string: Global___CHIDMessageToRemote.DeviceGetSerialNumberString | None = ...,
        device_start_input_reports: Global___CHIDMessageToRemote.DeviceStartInputReports | None = ...,
        device_request_full_report: Global___CHIDMessageToRemote.DeviceRequestFullReport | None = ...,
        device_disconnect: Global___CHIDMessageToRemote.DeviceDisconnect | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "device_close", b"device_close", "device_disconnect", b"device_disconnect", "device_get_feature_report", b"device_get_feature_report", "device_get_product_string", b"device_get_product_string", "device_get_serial_number_string", b"device_get_serial_number_string", "device_get_vendor_string", b"device_get_vendor_string", "device_open", b"device_open", "device_read", b"device_read", "device_request_full_report", b"device_request_full_report", "device_send_feature_report", b"device_send_feature_report", "device_start_input_reports", b"device_start_input_reports", "device_write", b"device_write", "request_id", b"request_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "device_close", b"device_close", "device_disconnect", b"device_disconnect", "device_get_feature_report", b"device_get_feature_report", "device_get_product_string", b"device_get_product_string", "device_get_serial_number_string", b"device_get_serial_number_string", "device_get_vendor_string", b"device_get_vendor_string", "device_open", b"device_open", "device_read", b"device_read", "device_request_full_report", b"device_request_full_report", "device_send_feature_report", b"device_send_feature_report", "device_start_input_reports", b"device_start_input_reports", "device_write", b"device_write", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_command: _TypeAlias = _typing.Literal["device_open", "device_close", "device_write", "device_read", "device_send_feature_report", "device_get_feature_report", "device_get_vendor_string", "device_get_product_string", "device_get_serial_number_string", "device_start_input_reports", "device_request_full_report", "device_disconnect"]  # noqa: Y015
    _WhichOneofArgType_command: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_command) -> _WhichOneofReturnType_command | None: ...

Global___CHIDMessageToRemote: _TypeAlias = CHIDMessageToRemote  # noqa: Y015

@_typing.final
class CHIDMessageFromRemote(_message.Message):

    @_typing.final
    class UpdateDeviceList(_message.Message):

        DEVICES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___CHIDDeviceInfo]: ...
        def __init__(
            self,
            *,
            devices: _abc.Iterable[Global___CHIDDeviceInfo] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class RequestResponse(_message.Message):

        REQUEST_ID_FIELD_NUMBER: _builtins.int
        RESULT_FIELD_NUMBER: _builtins.int
        DATA_FIELD_NUMBER: _builtins.int
        request_id: _builtins.int
        result: _builtins.int
        data: _builtins.bytes
        def __init__(
            self,
            *,
            request_id: _builtins.int | None = ...,
            result: _builtins.int | None = ...,
            data: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "request_id", b"request_id", "result", b"result"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "request_id", b"request_id", "result", b"result"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeviceInputReports(_message.Message):

        @_typing.final
        class DeviceInputReport(_message.Message):

            DEVICE_FIELD_NUMBER: _builtins.int
            REPORTS_FIELD_NUMBER: _builtins.int
            device: _builtins.int
            @_builtins.property
            def reports(self) -> _containers.RepeatedCompositeFieldContainer[Global___CHIDDeviceInputReport]: ...
            def __init__(
                self,
                *,
                device: _builtins.int | None = ...,
                reports: _abc.Iterable[Global___CHIDDeviceInputReport] | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "reports", b"reports"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        DEVICE_REPORTS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def device_reports(self) -> _containers.RepeatedCompositeFieldContainer[Global___CHIDMessageFromRemote.DeviceInputReports.DeviceInputReport]: ...
        def __init__(
            self,
            *,
            device_reports: _abc.Iterable[Global___CHIDMessageFromRemote.DeviceInputReports.DeviceInputReport] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device_reports", b"device_reports"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CloseDevice(_message.Message):

        DEVICE_FIELD_NUMBER: _builtins.int
        device: _builtins.int
        def __init__(
            self,
            *,
            device: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CloseAllDevices(_message.Message):

        def __init__(
            self,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    UPDATE_DEVICE_LIST_FIELD_NUMBER: _builtins.int
    RESPONSE_FIELD_NUMBER: _builtins.int
    REPORTS_FIELD_NUMBER: _builtins.int
    CLOSE_DEVICE_FIELD_NUMBER: _builtins.int
    CLOSE_ALL_DEVICES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def update_device_list(self) -> Global___CHIDMessageFromRemote.UpdateDeviceList: ...
    @_builtins.property
    def response(self) -> Global___CHIDMessageFromRemote.RequestResponse: ...
    @_builtins.property
    def reports(self) -> Global___CHIDMessageFromRemote.DeviceInputReports: ...
    @_builtins.property
    def close_device(self) -> Global___CHIDMessageFromRemote.CloseDevice: ...
    @_builtins.property
    def close_all_devices(self) -> Global___CHIDMessageFromRemote.CloseAllDevices: ...
    def __init__(
        self,
        *,
        update_device_list: Global___CHIDMessageFromRemote.UpdateDeviceList | None = ...,
        response: Global___CHIDMessageFromRemote.RequestResponse | None = ...,
        reports: Global___CHIDMessageFromRemote.DeviceInputReports | None = ...,
        close_device: Global___CHIDMessageFromRemote.CloseDevice | None = ...,
        close_all_devices: Global___CHIDMessageFromRemote.CloseAllDevices | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close_all_devices", b"close_all_devices", "close_device", b"close_device", "command", b"command", "reports", b"reports", "response", b"response", "update_device_list", b"update_device_list"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close_all_devices", b"close_all_devices", "close_device", b"close_device", "command", b"command", "reports", b"reports", "response", b"response", "update_device_list", b"update_device_list"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_command: _TypeAlias = _typing.Literal["update_device_list", "response", "reports", "close_device", "close_all_devices"]  # noqa: Y015
    _WhichOneofArgType_command: _TypeAlias = _typing.Literal["command", b"command"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_command) -> _WhichOneofReturnType_command | None: ...

Global___CHIDMessageFromRemote: _TypeAlias = CHIDMessageFromRemote  # noqa: Y015
