"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import steam.protobufs.clientmetrics_pb2 as _clientmetrics_pb2
import steam.protobufs.enums_pb2 as _enums_pb2
import steam.protobufs.steammessages_base_pb2 as _steammessages_base_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ESteamPipeWorkType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ESteamPipeWorkTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ESteamPipeWorkType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_ESteamPipeClientWorkType_Invalid: _ESteamPipeWorkType.ValueType  # 0
    k_ESteamPipeClientWorkType_StageFromChunkStores: _ESteamPipeWorkType.ValueType  # 1

class ESteamPipeWorkType(_ESteamPipeWorkType, metaclass=_ESteamPipeWorkTypeEnumTypeWrapper): ...

k_ESteamPipeClientWorkType_Invalid: ESteamPipeWorkType.ValueType  # 0
k_ESteamPipeClientWorkType_StageFromChunkStores: ESteamPipeWorkType.ValueType  # 1
Global___ESteamPipeWorkType: _TypeAlias = ESteamPipeWorkType  # noqa: Y015

class _ESteamPipeOperationType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ESteamPipeOperationTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ESteamPipeOperationType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_ESteamPipeOperationType_Invalid: _ESteamPipeOperationType.ValueType  # 0
    k_ESteamPipeOperationType_DecryptCPU: _ESteamPipeOperationType.ValueType  # 1
    k_ESteamPipeOperationType_DiskRead: _ESteamPipeOperationType.ValueType  # 2
    k_ESteamPipeOperationType_DiskWrite: _ESteamPipeOperationType.ValueType  # 3

class ESteamPipeOperationType(_ESteamPipeOperationType, metaclass=_ESteamPipeOperationTypeEnumTypeWrapper): ...

k_ESteamPipeOperationType_Invalid: ESteamPipeOperationType.ValueType  # 0
k_ESteamPipeOperationType_DecryptCPU: ESteamPipeOperationType.ValueType  # 1
k_ESteamPipeOperationType_DiskRead: ESteamPipeOperationType.ValueType  # 2
k_ESteamPipeOperationType_DiskWrite: ESteamPipeOperationType.ValueType  # 3
Global___ESteamPipeOperationType: _TypeAlias = ESteamPipeOperationType  # noqa: Y015

class _EClipShareMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EClipShareMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EClipShareMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EClipShareMethod_Chat: _EClipShareMethod.ValueType  # 1
    k_EClipShareMethod_Clipboard: _EClipShareMethod.ValueType  # 2
    k_EClipShareMethod_File: _EClipShareMethod.ValueType  # 3
    k_EClipShareMethod_SendClip: _EClipShareMethod.ValueType  # 4
    k_EClipShareMethod_SaveToMedia: _EClipShareMethod.ValueType  # 5
    k_EClipShareMethod_CreateLink: _EClipShareMethod.ValueType  # 6

class EClipShareMethod(_EClipShareMethod, metaclass=_EClipShareMethodEnumTypeWrapper): ...

k_EClipShareMethod_Chat: EClipShareMethod.ValueType  # 1
k_EClipShareMethod_Clipboard: EClipShareMethod.ValueType  # 2
k_EClipShareMethod_File: EClipShareMethod.ValueType  # 3
k_EClipShareMethod_SendClip: EClipShareMethod.ValueType  # 4
k_EClipShareMethod_SaveToMedia: EClipShareMethod.ValueType  # 5
k_EClipShareMethod_CreateLink: EClipShareMethod.ValueType  # 6
Global___EClipShareMethod: _TypeAlias = EClipShareMethod  # noqa: Y015

class _EClipRangeMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EClipRangeMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EClipRangeMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    k_EClipRangeMethod_CreateClipButton: _EClipRangeMethod.ValueType  # 1
    k_EClipRangeMethod_Highlight: _EClipRangeMethod.ValueType  # 2
    k_EClipRangeMethod_BeginEndButtons: _EClipRangeMethod.ValueType  # 3
    k_EClipRangeMethod_ContextMenu: _EClipRangeMethod.ValueType  # 4
    k_EClipRangeMethod_Drag: _EClipRangeMethod.ValueType  # 5
    k_EClipRangeMethod_EntireClip: _EClipRangeMethod.ValueType  # 6
    k_EClipRangeMethod_PhaseRecording: _EClipRangeMethod.ValueType  # 7

class EClipRangeMethod(_EClipRangeMethod, metaclass=_EClipRangeMethodEnumTypeWrapper): ...

k_EClipRangeMethod_CreateClipButton: EClipRangeMethod.ValueType  # 1
k_EClipRangeMethod_Highlight: EClipRangeMethod.ValueType  # 2
k_EClipRangeMethod_BeginEndButtons: EClipRangeMethod.ValueType  # 3
k_EClipRangeMethod_ContextMenu: EClipRangeMethod.ValueType  # 4
k_EClipRangeMethod_Drag: EClipRangeMethod.ValueType  # 5
k_EClipRangeMethod_EntireClip: EClipRangeMethod.ValueType  # 6
k_EClipRangeMethod_PhaseRecording: EClipRangeMethod.ValueType  # 7
Global___EClipRangeMethod: _TypeAlias = EClipRangeMethod  # noqa: Y015

@_typing.final
class CClientMetrics_AppInterfaceCreation(_message.Message):

    RAW_VERSION_FIELD_NUMBER: _builtins.int
    REQUESTED_INTERFACE_TYPE_FIELD_NUMBER: _builtins.int
    raw_version: _builtins.str
    requested_interface_type: _builtins.str
    def __init__(
        self,
        *,
        raw_version: _builtins.str | None = ...,
        requested_interface_type: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["raw_version", b"raw_version", "requested_interface_type", b"requested_interface_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["raw_version", b"raw_version", "requested_interface_type", b"requested_interface_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_AppInterfaceCreation: _TypeAlias = CClientMetrics_AppInterfaceCreation  # noqa: Y015

@_typing.final
class CClientMetrics_AppInterfaceMethodCounts(_message.Message):

    INTERFACE_NAME_FIELD_NUMBER: _builtins.int
    METHOD_NAME_FIELD_NUMBER: _builtins.int
    CALL_COUNT_FIELD_NUMBER: _builtins.int
    interface_name: _builtins.str
    method_name: _builtins.str
    call_count: _builtins.int
    def __init__(
        self,
        *,
        interface_name: _builtins.str | None = ...,
        method_name: _builtins.str | None = ...,
        call_count: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["call_count", b"call_count", "interface_name", b"interface_name", "method_name", b"method_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["call_count", b"call_count", "interface_name", b"interface_name", "method_name", b"method_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_AppInterfaceMethodCounts: _TypeAlias = CClientMetrics_AppInterfaceMethodCounts  # noqa: Y015

@_typing.final
class CClientMetrics_AppInterfaceStats_Notification(_message.Message):

    GAME_ID_FIELD_NUMBER: _builtins.int
    INTERFACES_CREATED_FIELD_NUMBER: _builtins.int
    METHODS_CALLED_FIELD_NUMBER: _builtins.int
    SESSION_LENGTH_SECONDS_FIELD_NUMBER: _builtins.int
    game_id: _builtins.int
    session_length_seconds: _builtins.int
    @_builtins.property
    def interfaces_created(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_AppInterfaceCreation]: ...
    @_builtins.property
    def methods_called(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_AppInterfaceMethodCounts]: ...
    def __init__(
        self,
        *,
        game_id: _builtins.int | None = ...,
        interfaces_created: _abc.Iterable[Global___CClientMetrics_AppInterfaceCreation] | None = ...,
        methods_called: _abc.Iterable[Global___CClientMetrics_AppInterfaceMethodCounts] | None = ...,
        session_length_seconds: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["game_id", b"game_id", "session_length_seconds", b"session_length_seconds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["game_id", b"game_id", "interfaces_created", b"interfaces_created", "methods_called", b"methods_called", "session_length_seconds", b"session_length_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_AppInterfaceStats_Notification: _TypeAlias = CClientMetrics_AppInterfaceStats_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_IPv6Connectivity_Result(_message.Message):

    PROTOCOL_TESTED_FIELD_NUMBER: _builtins.int
    CONNECTIVITY_STATE_FIELD_NUMBER: _builtins.int
    protocol_tested: _builtins.int
    connectivity_state: _builtins.int
    def __init__(
        self,
        *,
        protocol_tested: _builtins.int | None = ...,
        connectivity_state: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["connectivity_state", b"connectivity_state", "protocol_tested", b"protocol_tested"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connectivity_state", b"connectivity_state", "protocol_tested", b"protocol_tested"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_IPv6Connectivity_Result: _TypeAlias = CClientMetrics_IPv6Connectivity_Result  # noqa: Y015

@_typing.final
class CClientMetrics_IPv6Connectivity_Notification(_message.Message):

    CELL_ID_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    PRIVATE_IP_IS_RFC6598_FIELD_NUMBER: _builtins.int
    cell_id: _builtins.int
    private_ip_is_rfc6598: _builtins.bool
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_IPv6Connectivity_Result]: ...
    def __init__(
        self,
        *,
        cell_id: _builtins.int | None = ...,
        results: _abc.Iterable[Global___CClientMetrics_IPv6Connectivity_Result] | None = ...,
        private_ip_is_rfc6598: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "private_ip_is_rfc6598", b"private_ip_is_rfc6598"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "private_ip_is_rfc6598", b"private_ip_is_rfc6598", "results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_IPv6Connectivity_Notification: _TypeAlias = CClientMetrics_IPv6Connectivity_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_SteamPipeWorkStats_Operation(_message.Message):

    TYPE_FIELD_NUMBER: _builtins.int
    NUM_OPS_FIELD_NUMBER: _builtins.int
    NUM_BYTES_FIELD_NUMBER: _builtins.int
    BUSY_TIME_MS_FIELD_NUMBER: _builtins.int
    IDLE_TIME_MS_FIELD_NUMBER: _builtins.int
    SUM_RUN_TIME_MS_FIELD_NUMBER: _builtins.int
    SUM_WAIT_TIME_MS_FIELD_NUMBER: _builtins.int
    type: Global___ESteamPipeOperationType.ValueType
    num_ops: _builtins.int
    num_bytes: _builtins.int
    busy_time_ms: _builtins.int
    idle_time_ms: _builtins.int
    sum_run_time_ms: _builtins.int
    sum_wait_time_ms: _builtins.int
    def __init__(
        self,
        *,
        type: Global___ESteamPipeOperationType.ValueType | None = ...,
        num_ops: _builtins.int | None = ...,
        num_bytes: _builtins.int | None = ...,
        busy_time_ms: _builtins.int | None = ...,
        idle_time_ms: _builtins.int | None = ...,
        sum_run_time_ms: _builtins.int | None = ...,
        sum_wait_time_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["busy_time_ms", b"busy_time_ms", "idle_time_ms", b"idle_time_ms", "num_bytes", b"num_bytes", "num_ops", b"num_ops", "sum_run_time_ms", b"sum_run_time_ms", "sum_wait_time_ms", b"sum_wait_time_ms", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["busy_time_ms", b"busy_time_ms", "idle_time_ms", b"idle_time_ms", "num_bytes", b"num_bytes", "num_ops", b"num_ops", "sum_run_time_ms", b"sum_run_time_ms", "sum_wait_time_ms", b"sum_wait_time_ms", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_SteamPipeWorkStats_Operation: _TypeAlias = CClientMetrics_SteamPipeWorkStats_Operation  # noqa: Y015

@_typing.final
class CClientMetrics_SteamPipeWorkStats_Notification(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    DEPOTID_FIELD_NUMBER: _builtins.int
    WORK_TYPE_FIELD_NUMBER: _builtins.int
    OPERATIONS_FIELD_NUMBER: _builtins.int
    HARDWARE_TYPE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    depotid: _builtins.int
    work_type: Global___ESteamPipeWorkType.ValueType
    hardware_type: _builtins.int
    @_builtins.property
    def operations(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_SteamPipeWorkStats_Operation]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        depotid: _builtins.int | None = ...,
        work_type: Global___ESteamPipeWorkType.ValueType | None = ...,
        operations: _abc.Iterable[Global___CClientMetrics_SteamPipeWorkStats_Operation] | None = ...,
        hardware_type: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "depotid", b"depotid", "hardware_type", b"hardware_type", "work_type", b"work_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "depotid", b"depotid", "hardware_type", b"hardware_type", "operations", b"operations", "work_type", b"work_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_SteamPipeWorkStats_Notification: _TypeAlias = CClientMetrics_SteamPipeWorkStats_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ReportReactUsage_Notification(_message.Message):

    @_typing.final
    class RouteData(_message.Message):

        ROUTE_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        route: _builtins.str
        count: _builtins.int
        def __init__(
            self,
            *,
            route: _builtins.str | None = ...,
            count: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "route", b"route"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "route", b"route"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ComponentData(_message.Message):

        COMPONENT_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        component: _builtins.str
        count: _builtins.int
        def __init__(
            self,
            *,
            component: _builtins.str | None = ...,
            count: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["component", b"component", "count", b"count"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["component", b"component", "count", b"count"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ActionData(_message.Message):

        ACTION_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        action: _builtins.str
        count: _builtins.int
        def __init__(
            self,
            *,
            action: _builtins.str | None = ...,
            count: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "count", b"count"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "count", b"count"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    PRODUCT_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    ROUTES_FIELD_NUMBER: _builtins.int
    COMPONENTS_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    product: _builtins.str
    version: _builtins.str
    @_builtins.property
    def routes(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ReportReactUsage_Notification.RouteData]: ...
    @_builtins.property
    def components(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ReportReactUsage_Notification.ComponentData]: ...
    @_builtins.property
    def actions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ReportReactUsage_Notification.ActionData]: ...
    def __init__(
        self,
        *,
        product: _builtins.str | None = ...,
        version: _builtins.str | None = ...,
        routes: _abc.Iterable[Global___CClientMetrics_ReportReactUsage_Notification.RouteData] | None = ...,
        components: _abc.Iterable[Global___CClientMetrics_ReportReactUsage_Notification.ComponentData] | None = ...,
        actions: _abc.Iterable[Global___CClientMetrics_ReportReactUsage_Notification.ActionData] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actions", b"actions", "components", b"components", "product", b"product", "routes", b"routes", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ReportReactUsage_Notification: _TypeAlias = CClientMetrics_ReportReactUsage_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ReportClientError_Notification(_message.Message):

    @_typing.final
    class Error(_message.Message):

        IDENTIFIER_FIELD_NUMBER: _builtins.int
        MESSAGE_FIELD_NUMBER: _builtins.int
        COUNT_FIELD_NUMBER: _builtins.int
        CONTEXT_FIELD_NUMBER: _builtins.int
        URL_FIELD_NUMBER: _builtins.int
        identifier: _builtins.str
        message: _builtins.str
        count: _builtins.int
        context: _builtins.str
        url: _builtins.str
        def __init__(
            self,
            *,
            identifier: _builtins.str | None = ...,
            message: _builtins.str | None = ...,
            count: _builtins.int | None = ...,
            context: _builtins.str | None = ...,
            url: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "count", b"count", "identifier", b"identifier", "message", b"message", "url", b"url"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "count", b"count", "identifier", b"identifier", "message", b"message", "url", b"url"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    PRODUCT_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    ERRORS_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    product: _builtins.str
    version: _builtins.str
    @_builtins.property
    def errors(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_ReportClientError_Notification.Error]: ...
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        product: _builtins.str | None = ...,
        version: _builtins.str | None = ...,
        errors: _abc.Iterable[Global___CClientMetrics_ReportClientError_Notification.Error] | None = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["errors", b"errors", "product", b"product", "tags", b"tags", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ReportClientError_Notification: _TypeAlias = CClientMetrics_ReportClientError_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ClientBootstrap_Notification(_message.Message):

    SUMMARY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def summary(self) -> _clientmetrics_pb2.CClientMetrics_ClientBootstrap_Summary: ...
    def __init__(
        self,
        *,
        summary: _clientmetrics_pb2.CClientMetrics_ClientBootstrap_Summary | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ClientBootstrap_Notification: _TypeAlias = CClientMetrics_ClientBootstrap_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_DownloadRates_Notification(_message.Message):

    @_typing.final
    class StatsInfo(_message.Message):

        SOURCE_TYPE_FIELD_NUMBER: _builtins.int
        SOURCE_ID_FIELD_NUMBER: _builtins.int
        BYTES_FIELD_NUMBER: _builtins.int
        HOST_NAME_FIELD_NUMBER: _builtins.int
        MICROSECONDS_FIELD_NUMBER: _builtins.int
        USED_IPV6_FIELD_NUMBER: _builtins.int
        PROXIED_FIELD_NUMBER: _builtins.int
        USED_HTTP2_FIELD_NUMBER: _builtins.int
        CACHE_HITS_FIELD_NUMBER: _builtins.int
        CACHE_MISSES_FIELD_NUMBER: _builtins.int
        HIT_BYTES_FIELD_NUMBER: _builtins.int
        MISS_BYTES_FIELD_NUMBER: _builtins.int
        CHUNKS_SCORED_FIELD_NUMBER: _builtins.int
        SUM_CHUNK_SCORES_FIELD_NUMBER: _builtins.int
        source_type: _builtins.int
        source_id: _builtins.int
        bytes: _builtins.int
        host_name: _builtins.str
        microseconds: _builtins.int
        used_ipv6: _builtins.bool
        proxied: _builtins.bool
        used_http2: _builtins.bool
        cache_hits: _builtins.int
        cache_misses: _builtins.int
        hit_bytes: _builtins.int
        miss_bytes: _builtins.int
        chunks_scored: _builtins.int
        sum_chunk_scores: _builtins.float
        def __init__(
            self,
            *,
            source_type: _builtins.int | None = ...,
            source_id: _builtins.int | None = ...,
            bytes: _builtins.int | None = ...,
            host_name: _builtins.str | None = ...,
            microseconds: _builtins.int | None = ...,
            used_ipv6: _builtins.bool | None = ...,
            proxied: _builtins.bool | None = ...,
            used_http2: _builtins.bool | None = ...,
            cache_hits: _builtins.int | None = ...,
            cache_misses: _builtins.int | None = ...,
            hit_bytes: _builtins.int | None = ...,
            miss_bytes: _builtins.int | None = ...,
            chunks_scored: _builtins.int | None = ...,
            sum_chunk_scores: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "cache_hits", b"cache_hits", "cache_misses", b"cache_misses", "chunks_scored", b"chunks_scored", "hit_bytes", b"hit_bytes", "host_name", b"host_name", "microseconds", b"microseconds", "miss_bytes", b"miss_bytes", "proxied", b"proxied", "source_id", b"source_id", "source_type", b"source_type", "sum_chunk_scores", b"sum_chunk_scores", "used_http2", b"used_http2", "used_ipv6", b"used_ipv6"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "cache_hits", b"cache_hits", "cache_misses", b"cache_misses", "chunks_scored", b"chunks_scored", "hit_bytes", b"hit_bytes", "host_name", b"host_name", "microseconds", b"microseconds", "miss_bytes", b"miss_bytes", "proxied", b"proxied", "source_id", b"source_id", "source_type", b"source_type", "sum_chunk_scores", b"sum_chunk_scores", "used_http2", b"used_http2", "used_ipv6", b"used_ipv6"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CELL_ID_FIELD_NUMBER: _builtins.int
    STATS_FIELD_NUMBER: _builtins.int
    THROTTLING_KBPS_FIELD_NUMBER: _builtins.int
    OS_TYPE_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    cell_id: _builtins.int
    throttling_kbps: _builtins.int
    os_type: _builtins.int
    device_type: _builtins.int
    @_builtins.property
    def stats(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_DownloadRates_Notification.StatsInfo]: ...
    def __init__(
        self,
        *,
        cell_id: _builtins.int | None = ...,
        stats: _abc.Iterable[Global___CClientMetrics_DownloadRates_Notification.StatsInfo] | None = ...,
        throttling_kbps: _builtins.int | None = ...,
        os_type: _builtins.int | None = ...,
        device_type: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "device_type", b"device_type", "os_type", b"os_type", "throttling_kbps", b"throttling_kbps"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "device_type", b"device_type", "os_type", b"os_type", "stats", b"stats", "throttling_kbps", b"throttling_kbps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_DownloadRates_Notification: _TypeAlias = CClientMetrics_DownloadRates_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ContentValidation_Notification(_message.Message):

    VALIDATION_RESULT_FIELD_NUMBER: _builtins.int
    APP_ID_FIELD_NUMBER: _builtins.int
    STAGED_FILES_FIELD_NUMBER: _builtins.int
    USER_INITIATED_FIELD_NUMBER: _builtins.int
    EARLY_OUT_FIELD_NUMBER: _builtins.int
    CHUNKS_SCANNED_FIELD_NUMBER: _builtins.int
    CHUNKS_CORRUPT_FIELD_NUMBER: _builtins.int
    BYTES_SCANNED_FIELD_NUMBER: _builtins.int
    CHUNK_BYTES_CORRUPT_FIELD_NUMBER: _builtins.int
    TOTAL_FILE_SIZE_CORRUPT_FIELD_NUMBER: _builtins.int
    validation_result: _builtins.int
    app_id: _builtins.int
    staged_files: _builtins.bool
    user_initiated: _builtins.bool
    early_out: _builtins.bool
    chunks_scanned: _builtins.int
    chunks_corrupt: _builtins.int
    bytes_scanned: _builtins.int
    chunk_bytes_corrupt: _builtins.int
    total_file_size_corrupt: _builtins.int
    def __init__(
        self,
        *,
        validation_result: _builtins.int | None = ...,
        app_id: _builtins.int | None = ...,
        staged_files: _builtins.bool | None = ...,
        user_initiated: _builtins.bool | None = ...,
        early_out: _builtins.bool | None = ...,
        chunks_scanned: _builtins.int | None = ...,
        chunks_corrupt: _builtins.int | None = ...,
        bytes_scanned: _builtins.int | None = ...,
        chunk_bytes_corrupt: _builtins.int | None = ...,
        total_file_size_corrupt: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "bytes_scanned", b"bytes_scanned", "chunk_bytes_corrupt", b"chunk_bytes_corrupt", "chunks_corrupt", b"chunks_corrupt", "chunks_scanned", b"chunks_scanned", "early_out", b"early_out", "staged_files", b"staged_files", "total_file_size_corrupt", b"total_file_size_corrupt", "user_initiated", b"user_initiated", "validation_result", b"validation_result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "bytes_scanned", b"bytes_scanned", "chunk_bytes_corrupt", b"chunk_bytes_corrupt", "chunks_corrupt", b"chunks_corrupt", "chunks_scanned", b"chunks_scanned", "early_out", b"early_out", "staged_files", b"staged_files", "total_file_size_corrupt", b"total_file_size_corrupt", "user_initiated", b"user_initiated", "validation_result", b"validation_result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ContentValidation_Notification: _TypeAlias = CClientMetrics_ContentValidation_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_CloudAppSyncStats_Notification(_message.Message):

    APP_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_TYPE_FIELD_NUMBER: _builtins.int
    PRELOAD_FIELD_NUMBER: _builtins.int
    BLOCKING_APP_LAUNCH_FIELD_NUMBER: _builtins.int
    FILES_UPLOADED_FIELD_NUMBER: _builtins.int
    FILES_DOWNLOADED_FIELD_NUMBER: _builtins.int
    FILES_DELETED_FIELD_NUMBER: _builtins.int
    BYTES_UPLOADED_FIELD_NUMBER: _builtins.int
    BYTES_DOWNLOADED_FIELD_NUMBER: _builtins.int
    MICROSEC_TOTAL_FIELD_NUMBER: _builtins.int
    MICROSEC_INIT_CACHES_FIELD_NUMBER: _builtins.int
    MICROSEC_VALIDATE_STATE_FIELD_NUMBER: _builtins.int
    MICROSEC_AC_LAUNCH_FIELD_NUMBER: _builtins.int
    MICROSEC_AC_PREP_USER_FILES_FIELD_NUMBER: _builtins.int
    MICROSEC_AC_EXIT_FIELD_NUMBER: _builtins.int
    MICROSEC_BUILD_SYNC_LIST_FIELD_NUMBER: _builtins.int
    MICROSEC_DELETE_FILES_FIELD_NUMBER: _builtins.int
    MICROSEC_DOWNLOAD_FILES_FIELD_NUMBER: _builtins.int
    MICROSEC_UPLOAD_FILES_FIELD_NUMBER: _builtins.int
    HARDWARE_TYPE_FIELD_NUMBER: _builtins.int
    FILES_MANAGED_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    platform_type: _builtins.int
    preload: _builtins.bool
    blocking_app_launch: _builtins.bool
    files_uploaded: _builtins.int
    files_downloaded: _builtins.int
    files_deleted: _builtins.int
    bytes_uploaded: _builtins.int
    bytes_downloaded: _builtins.int
    microsec_total: _builtins.int
    microsec_init_caches: _builtins.int
    microsec_validate_state: _builtins.int
    microsec_ac_launch: _builtins.int
    microsec_ac_prep_user_files: _builtins.int
    microsec_ac_exit: _builtins.int
    microsec_build_sync_list: _builtins.int
    microsec_delete_files: _builtins.int
    microsec_download_files: _builtins.int
    microsec_upload_files: _builtins.int
    hardware_type: _builtins.int
    files_managed: _builtins.int
    def __init__(
        self,
        *,
        app_id: _builtins.int | None = ...,
        platform_type: _builtins.int | None = ...,
        preload: _builtins.bool | None = ...,
        blocking_app_launch: _builtins.bool | None = ...,
        files_uploaded: _builtins.int | None = ...,
        files_downloaded: _builtins.int | None = ...,
        files_deleted: _builtins.int | None = ...,
        bytes_uploaded: _builtins.int | None = ...,
        bytes_downloaded: _builtins.int | None = ...,
        microsec_total: _builtins.int | None = ...,
        microsec_init_caches: _builtins.int | None = ...,
        microsec_validate_state: _builtins.int | None = ...,
        microsec_ac_launch: _builtins.int | None = ...,
        microsec_ac_prep_user_files: _builtins.int | None = ...,
        microsec_ac_exit: _builtins.int | None = ...,
        microsec_build_sync_list: _builtins.int | None = ...,
        microsec_delete_files: _builtins.int | None = ...,
        microsec_download_files: _builtins.int | None = ...,
        microsec_upload_files: _builtins.int | None = ...,
        hardware_type: _builtins.int | None = ...,
        files_managed: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "blocking_app_launch", b"blocking_app_launch", "bytes_downloaded", b"bytes_downloaded", "bytes_uploaded", b"bytes_uploaded", "files_deleted", b"files_deleted", "files_downloaded", b"files_downloaded", "files_managed", b"files_managed", "files_uploaded", b"files_uploaded", "hardware_type", b"hardware_type", "microsec_ac_exit", b"microsec_ac_exit", "microsec_ac_launch", b"microsec_ac_launch", "microsec_ac_prep_user_files", b"microsec_ac_prep_user_files", "microsec_build_sync_list", b"microsec_build_sync_list", "microsec_delete_files", b"microsec_delete_files", "microsec_download_files", b"microsec_download_files", "microsec_init_caches", b"microsec_init_caches", "microsec_total", b"microsec_total", "microsec_upload_files", b"microsec_upload_files", "microsec_validate_state", b"microsec_validate_state", "platform_type", b"platform_type", "preload", b"preload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "blocking_app_launch", b"blocking_app_launch", "bytes_downloaded", b"bytes_downloaded", "bytes_uploaded", b"bytes_uploaded", "files_deleted", b"files_deleted", "files_downloaded", b"files_downloaded", "files_managed", b"files_managed", "files_uploaded", b"files_uploaded", "hardware_type", b"hardware_type", "microsec_ac_exit", b"microsec_ac_exit", "microsec_ac_launch", b"microsec_ac_launch", "microsec_ac_prep_user_files", b"microsec_ac_prep_user_files", "microsec_build_sync_list", b"microsec_build_sync_list", "microsec_delete_files", b"microsec_delete_files", "microsec_download_files", b"microsec_download_files", "microsec_init_caches", b"microsec_init_caches", "microsec_total", b"microsec_total", "microsec_upload_files", b"microsec_upload_files", "microsec_validate_state", b"microsec_validate_state", "platform_type", b"platform_type", "preload", b"preload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_CloudAppSyncStats_Notification: _TypeAlias = CClientMetrics_CloudAppSyncStats_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ContentDownloadResponse_Counts_Notification(_message.Message):

    CELL_ID_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    cell_id: _builtins.int
    @_builtins.property
    def data(self) -> _clientmetrics_pb2.CClientMetrics_ContentDownloadResponse_Hosts: ...
    def __init__(
        self,
        *,
        cell_id: _builtins.int | None = ...,
        data: _clientmetrics_pb2.CClientMetrics_ContentDownloadResponse_Hosts | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cell_id", b"cell_id", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ContentDownloadResponse_Counts_Notification: _TypeAlias = CClientMetrics_ContentDownloadResponse_Counts_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ReportClientArgs_Notification(_message.Message):

    CLIENT_ARGS_FIELD_NUMBER: _builtins.int
    GPU_WEBVIEW_REGKEY_DISABLED_FIELD_NUMBER: _builtins.int
    SUPPRESS_GPU_CHROME_FIELD_NUMBER: _builtins.int
    BROWSER_NOT_SUPPORTED_FIELD_NUMBER: _builtins.int
    HW_ACCEL_VIDEO_REGKEY_DISABLED_FIELD_NUMBER: _builtins.int
    MINI_MODE_ENABLED_FIELD_NUMBER: _builtins.int
    FPS_COUNTER_ENABLED_FIELD_NUMBER: _builtins.int
    LIBRARY_LOW_BANDWIDTH_MODE_ENABLED_FIELD_NUMBER: _builtins.int
    LIBRARY_LOW_PERF_MODE_ENABLED_FIELD_NUMBER: _builtins.int
    GR_MODE_FIELD_NUMBER: _builtins.int
    gpu_webview_regkey_disabled: _builtins.bool
    suppress_gpu_chrome: _builtins.bool
    browser_not_supported: _builtins.bool
    hw_accel_video_regkey_disabled: _builtins.bool
    mini_mode_enabled: _builtins.bool
    fps_counter_enabled: _builtins.bool
    library_low_bandwidth_mode_enabled: _builtins.bool
    library_low_perf_mode_enabled: _builtins.bool
    gr_mode: _enums_pb2.EGRMode.ValueType
    @_builtins.property
    def client_args(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        client_args: _abc.Iterable[_builtins.str] | None = ...,
        gpu_webview_regkey_disabled: _builtins.bool | None = ...,
        suppress_gpu_chrome: _builtins.bool | None = ...,
        browser_not_supported: _builtins.bool | None = ...,
        hw_accel_video_regkey_disabled: _builtins.bool | None = ...,
        mini_mode_enabled: _builtins.bool | None = ...,
        fps_counter_enabled: _builtins.bool | None = ...,
        library_low_bandwidth_mode_enabled: _builtins.bool | None = ...,
        library_low_perf_mode_enabled: _builtins.bool | None = ...,
        gr_mode: _enums_pb2.EGRMode.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["browser_not_supported", b"browser_not_supported", "fps_counter_enabled", b"fps_counter_enabled", "gpu_webview_regkey_disabled", b"gpu_webview_regkey_disabled", "gr_mode", b"gr_mode", "hw_accel_video_regkey_disabled", b"hw_accel_video_regkey_disabled", "library_low_bandwidth_mode_enabled", b"library_low_bandwidth_mode_enabled", "library_low_perf_mode_enabled", b"library_low_perf_mode_enabled", "mini_mode_enabled", b"mini_mode_enabled", "suppress_gpu_chrome", b"suppress_gpu_chrome"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["browser_not_supported", b"browser_not_supported", "client_args", b"client_args", "fps_counter_enabled", b"fps_counter_enabled", "gpu_webview_regkey_disabled", b"gpu_webview_regkey_disabled", "gr_mode", b"gr_mode", "hw_accel_video_regkey_disabled", b"hw_accel_video_regkey_disabled", "library_low_bandwidth_mode_enabled", b"library_low_bandwidth_mode_enabled", "library_low_perf_mode_enabled", b"library_low_perf_mode_enabled", "mini_mode_enabled", b"mini_mode_enabled", "suppress_gpu_chrome", b"suppress_gpu_chrome"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ReportClientArgs_Notification: _TypeAlias = CClientMetrics_ReportClientArgs_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ReportLinuxStats_Notification(_message.Message):

    GLIBC_VERSION_MAJOR_FIELD_NUMBER: _builtins.int
    GLIBC_VERSION_MINOR_FIELD_NUMBER: _builtins.int
    ACCOUNT_TYPE_FIELD_NUMBER: _builtins.int
    LAUNCHER_TYPE_FIELD_NUMBER: _builtins.int
    GAME_SERVER_APPID_FIELD_NUMBER: _builtins.int
    PROCESS_NAME_FIELD_NUMBER: _builtins.int
    glibc_version_major: _builtins.int
    glibc_version_minor: _builtins.int
    account_type: _builtins.int
    launcher_type: _builtins.int
    game_server_appid: _builtins.int
    process_name: _builtins.str
    def __init__(
        self,
        *,
        glibc_version_major: _builtins.int | None = ...,
        glibc_version_minor: _builtins.int | None = ...,
        account_type: _builtins.int | None = ...,
        launcher_type: _builtins.int | None = ...,
        game_server_appid: _builtins.int | None = ...,
        process_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["account_type", b"account_type", "game_server_appid", b"game_server_appid", "glibc_version_major", b"glibc_version_major", "glibc_version_minor", b"glibc_version_minor", "launcher_type", b"launcher_type", "process_name", b"process_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_type", b"account_type", "game_server_appid", b"game_server_appid", "glibc_version_major", b"glibc_version_major", "glibc_version_minor", b"glibc_version_minor", "launcher_type", b"launcher_type", "process_name", b"process_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ReportLinuxStats_Notification: _TypeAlias = CClientMetrics_ReportLinuxStats_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ReportAccessibilitySettings_Notification(_message.Message):

    ACCESSIBILITY_DESKTOP_UI_SCALE_FIELD_NUMBER: _builtins.int
    ACCESSIBILITY_SCREEN_READER_ENABLED_FIELD_NUMBER: _builtins.int
    ACCESSIBILITY_HIGH_CONTRAST_MODE_FIELD_NUMBER: _builtins.int
    ACCESSIBILITY_REDUCE_MOTION_FIELD_NUMBER: _builtins.int
    ACCESSIBILITY_COLOR_FILTER_NAME_FIELD_NUMBER: _builtins.int
    accessibility_desktop_ui_scale: _builtins.float
    accessibility_screen_reader_enabled: _builtins.bool
    accessibility_high_contrast_mode: _builtins.bool
    accessibility_reduce_motion: _builtins.bool
    accessibility_color_filter_name: _builtins.str
    def __init__(
        self,
        *,
        accessibility_desktop_ui_scale: _builtins.float | None = ...,
        accessibility_screen_reader_enabled: _builtins.bool | None = ...,
        accessibility_high_contrast_mode: _builtins.bool | None = ...,
        accessibility_reduce_motion: _builtins.bool | None = ...,
        accessibility_color_filter_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accessibility_color_filter_name", b"accessibility_color_filter_name", "accessibility_desktop_ui_scale", b"accessibility_desktop_ui_scale", "accessibility_high_contrast_mode", b"accessibility_high_contrast_mode", "accessibility_reduce_motion", b"accessibility_reduce_motion", "accessibility_screen_reader_enabled", b"accessibility_screen_reader_enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accessibility_color_filter_name", b"accessibility_color_filter_name", "accessibility_desktop_ui_scale", b"accessibility_desktop_ui_scale", "accessibility_high_contrast_mode", b"accessibility_high_contrast_mode", "accessibility_reduce_motion", b"accessibility_reduce_motion", "accessibility_screen_reader_enabled", b"accessibility_screen_reader_enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ReportAccessibilitySettings_Notification: _TypeAlias = CClientMetrics_ReportAccessibilitySettings_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ClipShare_Notification(_message.Message):

    ERESULT_FIELD_NUMBER: _builtins.int
    SHARE_METHOD_FIELD_NUMBER: _builtins.int
    SECONDS_FIELD_NUMBER: _builtins.int
    BYTES_FIELD_NUMBER: _builtins.int
    GAMEID_FIELD_NUMBER: _builtins.int
    eresult: _builtins.int
    share_method: Global___EClipShareMethod.ValueType
    seconds: _builtins.float
    bytes: _builtins.int
    gameid: _builtins.int
    def __init__(
        self,
        *,
        eresult: _builtins.int | None = ...,
        share_method: Global___EClipShareMethod.ValueType | None = ...,
        seconds: _builtins.float | None = ...,
        bytes: _builtins.int | None = ...,
        gameid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "eresult", b"eresult", "gameid", b"gameid", "seconds", b"seconds", "share_method", b"share_method"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "eresult", b"eresult", "gameid", b"gameid", "seconds", b"seconds", "share_method", b"share_method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ClipShare_Notification: _TypeAlias = CClientMetrics_ClipShare_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_ClipRange_Notification(_message.Message):

    @_typing.final
    class RelativeRangeEdge(_message.Message):

        ORIGINAL_RANGE_METHOD_FIELD_NUMBER: _builtins.int
        LATEST_RANGE_METHOD_FIELD_NUMBER: _builtins.int
        DELTA_MS_FIELD_NUMBER: _builtins.int
        original_range_method: Global___EClipRangeMethod.ValueType
        latest_range_method: Global___EClipRangeMethod.ValueType
        delta_ms: _builtins.int
        def __init__(
            self,
            *,
            original_range_method: Global___EClipRangeMethod.ValueType | None = ...,
            latest_range_method: Global___EClipRangeMethod.ValueType | None = ...,
            delta_ms: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["delta_ms", b"delta_ms", "latest_range_method", b"latest_range_method", "original_range_method", b"original_range_method"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["delta_ms", b"delta_ms", "latest_range_method", b"latest_range_method", "original_range_method", b"original_range_method"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ORIGINAL_RANGE_METHOD_FIELD_NUMBER: _builtins.int
    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    SECONDS_FIELD_NUMBER: _builtins.int
    GAMEID_FIELD_NUMBER: _builtins.int
    original_range_method: Global___EClipRangeMethod.ValueType
    seconds: _builtins.float
    gameid: _builtins.int
    @_builtins.property
    def start(self) -> Global___CClientMetrics_ClipRange_Notification.RelativeRangeEdge: ...
    @_builtins.property
    def end(self) -> Global___CClientMetrics_ClipRange_Notification.RelativeRangeEdge: ...
    def __init__(
        self,
        *,
        original_range_method: Global___EClipRangeMethod.ValueType | None = ...,
        start: Global___CClientMetrics_ClipRange_Notification.RelativeRangeEdge | None = ...,
        end: Global___CClientMetrics_ClipRange_Notification.RelativeRangeEdge | None = ...,
        seconds: _builtins.float | None = ...,
        gameid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "gameid", b"gameid", "original_range_method", b"original_range_method", "seconds", b"seconds", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end", b"end", "gameid", b"gameid", "original_range_method", b"original_range_method", "seconds", b"seconds", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_ClipRange_Notification: _TypeAlias = CClientMetrics_ClipRange_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_EndGameRecording_Notification(_message.Message):

    RECORDING_TYPE_FIELD_NUMBER: _builtins.int
    SECONDS_FIELD_NUMBER: _builtins.int
    BYTES_FIELD_NUMBER: _builtins.int
    GAMEID_FIELD_NUMBER: _builtins.int
    INSTANT_CLIP_FIELD_NUMBER: _builtins.int
    recording_type: _enums_pb2.EGameRecordingType.ValueType
    seconds: _builtins.float
    bytes: _builtins.int
    gameid: _builtins.int
    instant_clip: _builtins.bool
    def __init__(
        self,
        *,
        recording_type: _enums_pb2.EGameRecordingType.ValueType | None = ...,
        seconds: _builtins.float | None = ...,
        bytes: _builtins.int | None = ...,
        gameid: _builtins.int | None = ...,
        instant_clip: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "gameid", b"gameid", "instant_clip", b"instant_clip", "recording_type", b"recording_type", "seconds", b"seconds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes", b"bytes", "gameid", b"gameid", "instant_clip", b"instant_clip", "recording_type", b"recording_type", "seconds", b"seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_EndGameRecording_Notification: _TypeAlias = CClientMetrics_EndGameRecording_Notification  # noqa: Y015

@_typing.final
class CClientMetrics_GamePerformance_Notification(_message.Message):

    @_typing.final
    class FrameRate(_message.Message):

        GAMEID_FIELD_NUMBER: _builtins.int
        FRAME_RATE_FIELD_NUMBER: _builtins.int
        SESSION_SECONDS_FIELD_NUMBER: _builtins.int
        FRAMEGEN_FRAME_RATE_FIELD_NUMBER: _builtins.int
        GAME_SETTINGS_FIELD_NUMBER: _builtins.int
        gameid: _builtins.int
        frame_rate: _builtins.int
        session_seconds: _builtins.int
        framegen_frame_rate: _builtins.int
        @_builtins.property
        def game_settings(self) -> _steammessages_base_pb2.GamePerformanceSettings: ...
        def __init__(
            self,
            *,
            gameid: _builtins.int | None = ...,
            frame_rate: _builtins.int | None = ...,
            session_seconds: _builtins.int | None = ...,
            framegen_frame_rate: _builtins.int | None = ...,
            game_settings: _steammessages_base_pb2.GamePerformanceSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["frame_rate", b"frame_rate", "framegen_frame_rate", b"framegen_frame_rate", "game_settings", b"game_settings", "gameid", b"gameid", "session_seconds", b"session_seconds"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["frame_rate", b"frame_rate", "framegen_frame_rate", b"framegen_frame_rate", "game_settings", b"game_settings", "gameid", b"gameid", "session_seconds", b"session_seconds"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    FRAME_RATES_FIELD_NUMBER: _builtins.int
    SYSTEM_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def frame_rates(self) -> _containers.RepeatedCompositeFieldContainer[Global___CClientMetrics_GamePerformance_Notification.FrameRate]: ...
    @_builtins.property
    def system_info(self) -> _steammessages_base_pb2.UserSystemInformation: ...
    def __init__(
        self,
        *,
        frame_rates: _abc.Iterable[Global___CClientMetrics_GamePerformance_Notification.FrameRate] | None = ...,
        system_info: _steammessages_base_pb2.UserSystemInformation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["system_info", b"system_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frame_rates", b"frame_rates", "system_info", b"system_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CClientMetrics_GamePerformance_Notification: _TypeAlias = CClientMetrics_GamePerformance_Notification  # noqa: Y015
