"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CMsgTest_MessageToClient_Request(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_MessageToClient_Request: _TypeAlias = CMsgTest_MessageToClient_Request  # noqa: Y015

@_typing.final
class CMsgTest_MessageToClient_Response(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_MessageToClient_Response: _TypeAlias = CMsgTest_MessageToClient_Response  # noqa: Y015

@_typing.final
class CMsgTest_NotifyClient_Notification(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_NotifyClient_Notification: _TypeAlias = CMsgTest_NotifyClient_Notification  # noqa: Y015

@_typing.final
class CMsgTest_MessageToServer_Request(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_MessageToServer_Request: _TypeAlias = CMsgTest_MessageToServer_Request  # noqa: Y015

@_typing.final
class CMsgTest_MessageToServer_Response(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_MessageToServer_Response: _TypeAlias = CMsgTest_MessageToServer_Response  # noqa: Y015

@_typing.final
class CMsgTest_NotifyServer_Notification(_message.Message):

    SOME_TEXT_FIELD_NUMBER: _builtins.int
    some_text: _builtins.str
    def __init__(
        self,
        *,
        some_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["some_text", b"some_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_NotifyServer_Notification: _TypeAlias = CMsgTest_NotifyServer_Notification  # noqa: Y015

@_typing.final
class CMsgTest_TestClientCall_Request(_message.Message):

    PARAM_FIELD_NUMBER: _builtins.int
    param: _builtins.int
    def __init__(
        self,
        *,
        param: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["param", b"param"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["param", b"param"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_TestClientCall_Request: _TypeAlias = CMsgTest_TestClientCall_Request  # noqa: Y015

@_typing.final
class CMsgTest_TestClientCall_Response(_message.Message):

    RESULT_FIELD_NUMBER: _builtins.int
    result: _builtins.int
    def __init__(
        self,
        *,
        result: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_TestClientCall_Response: _TypeAlias = CMsgTest_TestClientCall_Response  # noqa: Y015

@_typing.final
class CMsgTest_NoBody_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_NoBody_Request: _TypeAlias = CMsgTest_NoBody_Request  # noqa: Y015

@_typing.final
class CMsgTest_CallClient_Response(_message.Message):

    TESTVALUE_FIELD_NUMBER: _builtins.int
    testvalue: _builtins.int
    def __init__(
        self,
        *,
        testvalue: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["testvalue", b"testvalue"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["testvalue", b"testvalue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgTest_CallClient_Response: _TypeAlias = CMsgTest_CallClient_Response  # noqa: Y015
