"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CGameNotifications_Variable(_message.Message):

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str | None = ...,
        value: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_Variable: _TypeAlias = CGameNotifications_Variable  # noqa: Y015

@_typing.final
class CGameNotifications_LocalizedText(_message.Message):

    TOKEN_FIELD_NUMBER: _builtins.int
    VARIABLES_FIELD_NUMBER: _builtins.int
    RENDERED_TEXT_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    rendered_text: _builtins.str
    @_builtins.property
    def variables(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_Variable]: ...
    def __init__(
        self,
        *,
        token: _builtins.str | None = ...,
        variables: _abc.Iterable[Global___CGameNotifications_Variable] | None = ...,
        rendered_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rendered_text", b"rendered_text", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rendered_text", b"rendered_text", "token", b"token", "variables", b"variables"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_LocalizedText: _TypeAlias = CGameNotifications_LocalizedText  # noqa: Y015

@_typing.final
class CGameNotifications_UserStatus(_message.Message):

    STEAMID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    steamid: _builtins.int
    state: _builtins.str
    @_builtins.property
    def title(self) -> Global___CGameNotifications_LocalizedText: ...
    @_builtins.property
    def message(self) -> Global___CGameNotifications_LocalizedText: ...
    def __init__(
        self,
        *,
        steamid: _builtins.int | None = ...,
        state: _builtins.str | None = ...,
        title: Global___CGameNotifications_LocalizedText | None = ...,
        message: Global___CGameNotifications_LocalizedText | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "state", b"state", "steamid", b"steamid", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "state", b"state", "steamid", b"steamid", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_UserStatus: _TypeAlias = CGameNotifications_UserStatus  # noqa: Y015

@_typing.final
class CGameNotifications_CreateSession_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    USERS_FIELD_NUMBER: _builtins.int
    STEAMID_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    context: _builtins.int
    steamid: _builtins.int
    @_builtins.property
    def title(self) -> Global___CGameNotifications_LocalizedText: ...
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_UserStatus]: ...
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        context: _builtins.int | None = ...,
        title: Global___CGameNotifications_LocalizedText | None = ...,
        users: _abc.Iterable[Global___CGameNotifications_UserStatus] | None = ...,
        steamid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "context", b"context", "steamid", b"steamid", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "context", b"context", "steamid", b"steamid", "title", b"title", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_CreateSession_Request: _TypeAlias = CGameNotifications_CreateSession_Request  # noqa: Y015

@_typing.final
class CGameNotifications_CreateSession_Response(_message.Message):

    SESSIONID_FIELD_NUMBER: _builtins.int
    sessionid: _builtins.int
    def __init__(
        self,
        *,
        sessionid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sessionid", b"sessionid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sessionid", b"sessionid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_CreateSession_Response: _TypeAlias = CGameNotifications_CreateSession_Response  # noqa: Y015

@_typing.final
class CGameNotifications_DeleteSession_Request(_message.Message):

    SESSIONID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    STEAMID_FIELD_NUMBER: _builtins.int
    sessionid: _builtins.int
    appid: _builtins.int
    steamid: _builtins.int
    def __init__(
        self,
        *,
        sessionid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
        steamid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "sessionid", b"sessionid", "steamid", b"steamid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "sessionid", b"sessionid", "steamid", b"steamid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_DeleteSession_Request: _TypeAlias = CGameNotifications_DeleteSession_Request  # noqa: Y015

@_typing.final
class CGameNotifications_DeleteSession_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_DeleteSession_Response: _TypeAlias = CGameNotifications_DeleteSession_Response  # noqa: Y015

@_typing.final
class CGameNotifications_UpdateSession_Request(_message.Message):

    SESSIONID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    USERS_FIELD_NUMBER: _builtins.int
    STEAMID_FIELD_NUMBER: _builtins.int
    sessionid: _builtins.int
    appid: _builtins.int
    steamid: _builtins.int
    @_builtins.property
    def title(self) -> Global___CGameNotifications_LocalizedText: ...
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_UserStatus]: ...
    def __init__(
        self,
        *,
        sessionid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
        title: Global___CGameNotifications_LocalizedText | None = ...,
        users: _abc.Iterable[Global___CGameNotifications_UserStatus] | None = ...,
        steamid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "sessionid", b"sessionid", "steamid", b"steamid", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "sessionid", b"sessionid", "steamid", b"steamid", "title", b"title", "users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_UpdateSession_Request: _TypeAlias = CGameNotifications_UpdateSession_Request  # noqa: Y015

@_typing.final
class CGameNotifications_UpdateSession_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_UpdateSession_Response: _TypeAlias = CGameNotifications_UpdateSession_Response  # noqa: Y015

@_typing.final
class CGameNotifications_EnumerateSessions_Request(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    INCLUDE_ALL_USER_MESSAGES_FIELD_NUMBER: _builtins.int
    INCLUDE_AUTH_USER_MESSAGE_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    include_all_user_messages: _builtins.bool
    include_auth_user_message: _builtins.bool
    language: _builtins.str
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        include_all_user_messages: _builtins.bool | None = ...,
        include_auth_user_message: _builtins.bool | None = ...,
        language: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "include_all_user_messages", b"include_all_user_messages", "include_auth_user_message", b"include_auth_user_message", "language", b"language"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "include_all_user_messages", b"include_all_user_messages", "include_auth_user_message", b"include_auth_user_message", "language", b"language"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_EnumerateSessions_Request: _TypeAlias = CGameNotifications_EnumerateSessions_Request  # noqa: Y015

@_typing.final
class CGameNotifications_Session(_message.Message):

    SESSIONID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    TIME_CREATED_FIELD_NUMBER: _builtins.int
    TIME_UPDATED_FIELD_NUMBER: _builtins.int
    USER_STATUS_FIELD_NUMBER: _builtins.int
    sessionid: _builtins.int
    appid: _builtins.int
    context: _builtins.int
    time_created: _builtins.int
    time_updated: _builtins.int
    @_builtins.property
    def title(self) -> Global___CGameNotifications_LocalizedText: ...
    @_builtins.property
    def user_status(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_UserStatus]: ...
    def __init__(
        self,
        *,
        sessionid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
        context: _builtins.int | None = ...,
        title: Global___CGameNotifications_LocalizedText | None = ...,
        time_created: _builtins.int | None = ...,
        time_updated: _builtins.int | None = ...,
        user_status: _abc.Iterable[Global___CGameNotifications_UserStatus] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "context", b"context", "sessionid", b"sessionid", "time_created", b"time_created", "time_updated", b"time_updated", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "context", b"context", "sessionid", b"sessionid", "time_created", b"time_created", "time_updated", b"time_updated", "title", b"title", "user_status", b"user_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_Session: _TypeAlias = CGameNotifications_Session  # noqa: Y015

@_typing.final
class CGameNotifications_EnumerateSessions_Response(_message.Message):

    SESSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_Session]: ...
    def __init__(
        self,
        *,
        sessions: _abc.Iterable[Global___CGameNotifications_Session] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sessions", b"sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_EnumerateSessions_Response: _TypeAlias = CGameNotifications_EnumerateSessions_Response  # noqa: Y015

@_typing.final
class CGameNotifications_GetSessionDetails_Request(_message.Message):

    @_typing.final
    class RequestedSession(_message.Message):

        SESSIONID_FIELD_NUMBER: _builtins.int
        INCLUDE_AUTH_USER_MESSAGE_FIELD_NUMBER: _builtins.int
        sessionid: _builtins.int
        include_auth_user_message: _builtins.bool
        def __init__(
            self,
            *,
            sessionid: _builtins.int | None = ...,
            include_auth_user_message: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["include_auth_user_message", b"include_auth_user_message", "sessionid", b"sessionid"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["include_auth_user_message", b"include_auth_user_message", "sessionid", b"sessionid"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SESSIONS_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    language: _builtins.str
    @_builtins.property
    def sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_GetSessionDetails_Request.RequestedSession]: ...
    def __init__(
        self,
        *,
        sessions: _abc.Iterable[Global___CGameNotifications_GetSessionDetails_Request.RequestedSession] | None = ...,
        appid: _builtins.int | None = ...,
        language: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "language", b"language"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "language", b"language", "sessions", b"sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_GetSessionDetails_Request: _TypeAlias = CGameNotifications_GetSessionDetails_Request  # noqa: Y015

@_typing.final
class CGameNotifications_GetSessionDetails_Response(_message.Message):

    SESSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___CGameNotifications_Session]: ...
    def __init__(
        self,
        *,
        sessions: _abc.Iterable[Global___CGameNotifications_Session] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sessions", b"sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_GetSessionDetails_Response: _TypeAlias = CGameNotifications_GetSessionDetails_Response  # noqa: Y015

@_typing.final
class GameNotificationSettings(_message.Message):

    APPID_FIELD_NUMBER: _builtins.int
    ALLOW_NOTIFICATIONS_FIELD_NUMBER: _builtins.int
    appid: _builtins.int
    allow_notifications: _builtins.bool
    def __init__(
        self,
        *,
        appid: _builtins.int | None = ...,
        allow_notifications: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["allow_notifications", b"allow_notifications", "appid", b"appid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_notifications", b"allow_notifications", "appid", b"appid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GameNotificationSettings: _TypeAlias = GameNotificationSettings  # noqa: Y015

@_typing.final
class CGameNotifications_UpdateNotificationSettings_Request(_message.Message):

    GAME_NOTIFICATION_SETTINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def game_notification_settings(self) -> _containers.RepeatedCompositeFieldContainer[Global___GameNotificationSettings]: ...
    def __init__(
        self,
        *,
        game_notification_settings: _abc.Iterable[Global___GameNotificationSettings] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["game_notification_settings", b"game_notification_settings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_UpdateNotificationSettings_Request: _TypeAlias = CGameNotifications_UpdateNotificationSettings_Request  # noqa: Y015

@_typing.final
class CGameNotifications_UpdateNotificationSettings_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_UpdateNotificationSettings_Response: _TypeAlias = CGameNotifications_UpdateNotificationSettings_Response  # noqa: Y015

@_typing.final
class CGameNotifications_OnNotificationsRequested_Notification(_message.Message):

    STEAMID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    steamid: _builtins.int
    appid: _builtins.int
    def __init__(
        self,
        *,
        steamid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "steamid", b"steamid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "steamid", b"steamid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_OnNotificationsRequested_Notification: _TypeAlias = CGameNotifications_OnNotificationsRequested_Notification  # noqa: Y015

@_typing.final
class CGameNotifications_OnUserStatusChanged_Notification(_message.Message):

    STEAMID_FIELD_NUMBER: _builtins.int
    SESSIONID_FIELD_NUMBER: _builtins.int
    APPID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    steamid: _builtins.int
    sessionid: _builtins.int
    appid: _builtins.int
    removed: _builtins.bool
    @_builtins.property
    def status(self) -> Global___CGameNotifications_UserStatus: ...
    def __init__(
        self,
        *,
        steamid: _builtins.int | None = ...,
        sessionid: _builtins.int | None = ...,
        appid: _builtins.int | None = ...,
        status: Global___CGameNotifications_UserStatus | None = ...,
        removed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "removed", b"removed", "sessionid", b"sessionid", "status", b"status", "steamid", b"steamid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["appid", b"appid", "removed", b"removed", "sessionid", b"sessionid", "status", b"status", "steamid", b"steamid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotifications_OnUserStatusChanged_Notification: _TypeAlias = CGameNotifications_OnUserStatusChanged_Notification  # noqa: Y015
