"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import steam.protobufs.enums_pb2 as _enums_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CBluetoothManager_GetState_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetState_Request: _TypeAlias = CBluetoothManager_GetState_Request  # noqa: Y015

@_typing.final
class CMsgBluetoothManagerAdapterInfo(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgBluetoothManagerAdapterInfo: _TypeAlias = CMsgBluetoothManagerAdapterInfo  # noqa: Y015

@_typing.final
class CMsgBluetoothManagerDeviceInfo(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    SHOULD_HIDE_HINT_FIELD_NUMBER: _builtins.int
    ETYPE_FIELD_NUMBER: _builtins.int
    IS_CONNECTED_FIELD_NUMBER: _builtins.int
    IS_PAIRED_FIELD_NUMBER: _builtins.int
    STRENGTH_RAW_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    should_hide_hint: _builtins.bool
    etype: _enums_pb2.EBluetoothDeviceType.ValueType
    is_connected: _builtins.bool
    is_paired: _builtins.bool
    strength_raw: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        should_hide_hint: _builtins.bool | None = ...,
        etype: _enums_pb2.EBluetoothDeviceType.ValueType | None = ...,
        is_connected: _builtins.bool | None = ...,
        is_paired: _builtins.bool | None = ...,
        strength_raw: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["etype", b"etype", "id", b"id", "is_connected", b"is_connected", "is_paired", b"is_paired", "should_hide_hint", b"should_hide_hint", "strength_raw", b"strength_raw"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["etype", b"etype", "id", b"id", "is_connected", b"is_connected", "is_paired", b"is_paired", "should_hide_hint", b"should_hide_hint", "strength_raw", b"strength_raw"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgBluetoothManagerDeviceInfo: _TypeAlias = CMsgBluetoothManagerDeviceInfo  # noqa: Y015

@_typing.final
class CBluetoothManager_GetState_Response(_message.Message):

    IS_SERVICE_AVAILABLE_FIELD_NUMBER: _builtins.int
    IS_ENABLED_FIELD_NUMBER: _builtins.int
    IS_DISCOVERING_FIELD_NUMBER: _builtins.int
    ADAPTERS_FIELD_NUMBER: _builtins.int
    DEVICES_FIELD_NUMBER: _builtins.int
    is_service_available: _builtins.bool
    is_enabled: _builtins.bool
    is_discovering: _builtins.bool
    @_builtins.property
    def adapters(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgBluetoothManagerAdapterInfo]: ...
    @_builtins.property
    def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___CMsgBluetoothManagerDeviceInfo]: ...
    def __init__(
        self,
        *,
        is_service_available: _builtins.bool | None = ...,
        is_enabled: _builtins.bool | None = ...,
        is_discovering: _builtins.bool | None = ...,
        adapters: _abc.Iterable[Global___CMsgBluetoothManagerAdapterInfo] | None = ...,
        devices: _abc.Iterable[Global___CMsgBluetoothManagerDeviceInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["is_discovering", b"is_discovering", "is_enabled", b"is_enabled", "is_service_available", b"is_service_available"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adapters", b"adapters", "devices", b"devices", "is_discovering", b"is_discovering", "is_enabled", b"is_enabled", "is_service_available", b"is_service_available"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetState_Response: _TypeAlias = CBluetoothManager_GetState_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_GetAdapterDetails_Request(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetAdapterDetails_Request: _TypeAlias = CBluetoothManager_GetAdapterDetails_Request  # noqa: Y015

@_typing.final
class CMsgBluetoothManagerAdapterDetails(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    MAC_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    IS_ENABLED_FIELD_NUMBER: _builtins.int
    IS_DISCOVERING_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    mac: _builtins.str
    name: _builtins.str
    is_enabled: _builtins.bool
    is_discovering: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        mac: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        is_enabled: _builtins.bool | None = ...,
        is_discovering: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_discovering", b"is_discovering", "is_enabled", b"is_enabled", "mac", b"mac", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_discovering", b"is_discovering", "is_enabled", b"is_enabled", "mac", b"mac", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgBluetoothManagerAdapterDetails: _TypeAlias = CMsgBluetoothManagerAdapterDetails  # noqa: Y015

@_typing.final
class CBluetoothManager_GetAdapterDetails_Response(_message.Message):

    ADAPTER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def adapter(self) -> Global___CMsgBluetoothManagerAdapterDetails: ...
    def __init__(
        self,
        *,
        adapter: Global___CMsgBluetoothManagerAdapterDetails | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adapter", b"adapter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adapter", b"adapter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetAdapterDetails_Response: _TypeAlias = CBluetoothManager_GetAdapterDetails_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_GetDeviceDetails_Request(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetDeviceDetails_Request: _TypeAlias = CBluetoothManager_GetDeviceDetails_Request  # noqa: Y015

@_typing.final
class CMsgBluetoothManagerDeviceDetails(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    ADAPTER_ID_FIELD_NUMBER: _builtins.int
    ETYPE_FIELD_NUMBER: _builtins.int
    MAC_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    IS_CONNECTED_FIELD_NUMBER: _builtins.int
    IS_PAIRED_FIELD_NUMBER: _builtins.int
    IS_PAIRING_FIELD_NUMBER: _builtins.int
    WAKE_ALLOWED_FIELD_NUMBER: _builtins.int
    WAKE_ALLOWED_SUPPORTED_FIELD_NUMBER: _builtins.int
    BATTERY_PERCENT_FIELD_NUMBER: _builtins.int
    OPERATION_IN_PROGRESS_FIELD_NUMBER: _builtins.int
    IS_TRUSTED_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    adapter_id: _builtins.int
    etype: _enums_pb2.EBluetoothDeviceType.ValueType
    mac: _builtins.str
    name: _builtins.str
    is_connected: _builtins.bool
    is_paired: _builtins.bool
    is_pairing: _builtins.bool
    wake_allowed: _builtins.bool
    wake_allowed_supported: _builtins.bool
    battery_percent: _builtins.int
    operation_in_progress: _builtins.bool
    is_trusted: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        adapter_id: _builtins.int | None = ...,
        etype: _enums_pb2.EBluetoothDeviceType.ValueType | None = ...,
        mac: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        is_connected: _builtins.bool | None = ...,
        is_paired: _builtins.bool | None = ...,
        is_pairing: _builtins.bool | None = ...,
        wake_allowed: _builtins.bool | None = ...,
        wake_allowed_supported: _builtins.bool | None = ...,
        battery_percent: _builtins.int | None = ...,
        operation_in_progress: _builtins.bool | None = ...,
        is_trusted: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adapter_id", b"adapter_id", "battery_percent", b"battery_percent", "etype", b"etype", "id", b"id", "is_connected", b"is_connected", "is_paired", b"is_paired", "is_pairing", b"is_pairing", "is_trusted", b"is_trusted", "mac", b"mac", "name", b"name", "operation_in_progress", b"operation_in_progress", "wake_allowed", b"wake_allowed", "wake_allowed_supported", b"wake_allowed_supported"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adapter_id", b"adapter_id", "battery_percent", b"battery_percent", "etype", b"etype", "id", b"id", "is_connected", b"is_connected", "is_paired", b"is_paired", "is_pairing", b"is_pairing", "is_trusted", b"is_trusted", "mac", b"mac", "name", b"name", "operation_in_progress", b"operation_in_progress", "wake_allowed", b"wake_allowed", "wake_allowed_supported", b"wake_allowed_supported"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CMsgBluetoothManagerDeviceDetails: _TypeAlias = CMsgBluetoothManagerDeviceDetails  # noqa: Y015

@_typing.final
class CBluetoothManager_GetDeviceDetails_Response(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def device(self) -> Global___CMsgBluetoothManagerDeviceDetails: ...
    def __init__(
        self,
        *,
        device: Global___CMsgBluetoothManagerDeviceDetails | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_GetDeviceDetails_Response: _TypeAlias = CBluetoothManager_GetDeviceDetails_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_StateChanged_Notification(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_StateChanged_Notification: _TypeAlias = CBluetoothManager_StateChanged_Notification  # noqa: Y015

@_typing.final
class CBluetoothManager_SetDiscovering_Request(_message.Message):

    ENABLED_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetDiscovering_Request: _TypeAlias = CBluetoothManager_SetDiscovering_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_SetDiscovering_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetDiscovering_Response: _TypeAlias = CBluetoothManager_SetDiscovering_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_SetLoginAdvertising_Request(_message.Message):

    ENABLED_FIELD_NUMBER: _builtins.int
    CLIENT_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    client_id: _builtins.int
    device_id: _builtins.int
    def __init__(
        self,
        *,
        enabled: _builtins.bool | None = ...,
        client_id: _builtins.int | None = ...,
        device_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "device_id", b"device_id", "enabled", b"enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_id", b"client_id", "device_id", b"device_id", "enabled", b"enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetLoginAdvertising_Request: _TypeAlias = CBluetoothManager_SetLoginAdvertising_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_SetLoginAdvertising_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetLoginAdvertising_Response: _TypeAlias = CBluetoothManager_SetLoginAdvertising_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_Pair_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Pair_Request: _TypeAlias = CBluetoothManager_Pair_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_Pair_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Pair_Response: _TypeAlias = CBluetoothManager_Pair_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_CancelPair_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_CancelPair_Request: _TypeAlias = CBluetoothManager_CancelPair_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_CancelPair_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_CancelPair_Response: _TypeAlias = CBluetoothManager_CancelPair_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_Forget_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Forget_Request: _TypeAlias = CBluetoothManager_Forget_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_Forget_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Forget_Response: _TypeAlias = CBluetoothManager_Forget_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_Connect_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Connect_Request: _TypeAlias = CBluetoothManager_Connect_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_Connect_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Connect_Response: _TypeAlias = CBluetoothManager_Connect_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_Disconnect_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Disconnect_Request: _TypeAlias = CBluetoothManager_Disconnect_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_Disconnect_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_Disconnect_Response: _TypeAlias = CBluetoothManager_Disconnect_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_SetWakeAllowed_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    ALLOWED_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    allowed: _builtins.bool
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
        allowed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "device", b"device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetWakeAllowed_Request: _TypeAlias = CBluetoothManager_SetWakeAllowed_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_SetWakeAllowed_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetWakeAllowed_Response: _TypeAlias = CBluetoothManager_SetWakeAllowed_Response  # noqa: Y015

@_typing.final
class CBluetoothManager_SetTrusted_Request(_message.Message):

    DEVICE_FIELD_NUMBER: _builtins.int
    TRUSTED_FIELD_NUMBER: _builtins.int
    device: _builtins.int
    trusted: _builtins.bool
    def __init__(
        self,
        *,
        device: _builtins.int | None = ...,
        trusted: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "trusted", b"trusted"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "trusted", b"trusted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetTrusted_Request: _TypeAlias = CBluetoothManager_SetTrusted_Request  # noqa: Y015

@_typing.final
class CBluetoothManager_SetTrusted_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CBluetoothManager_SetTrusted_Response: _TypeAlias = CBluetoothManager_SetTrusted_Response  # noqa: Y015
