"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import steam.protobufs.enums_pb2 as _enums_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CStorageDeviceManager_IsServiceAvailable_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_IsServiceAvailable_Request: _TypeAlias = CStorageDeviceManager_IsServiceAvailable_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_IsServiceAvailable_Response(_message.Message):

    IS_AVAILABLE_FIELD_NUMBER: _builtins.int
    is_available: _builtins.bool
    def __init__(
        self,
        *,
        is_available: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["is_available", b"is_available"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_available", b"is_available"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_IsServiceAvailable_Response: _TypeAlias = CStorageDeviceManager_IsServiceAvailable_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManagerDrive(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    VENDOR_FIELD_NUMBER: _builtins.int
    SERIAL_FIELD_NUMBER: _builtins.int
    IS_EJECTABLE_FIELD_NUMBER: _builtins.int
    SIZE_BYTES_FIELD_NUMBER: _builtins.int
    MEDIA_TYPE_FIELD_NUMBER: _builtins.int
    IS_UNFORMATTED_FIELD_NUMBER: _builtins.int
    ADOPT_STAGE_FIELD_NUMBER: _builtins.int
    IS_FORMATTABLE_FIELD_NUMBER: _builtins.int
    IS_MEDIA_AVAILABLE_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    model: _builtins.str
    vendor: _builtins.str
    serial: _builtins.str
    is_ejectable: _builtins.bool
    size_bytes: _builtins.int
    media_type: _enums_pb2.EStorageDriveMediaType.ValueType
    is_unformatted: _builtins.bool
    adopt_stage: _enums_pb2.EStorageFormatStage.ValueType
    is_formattable: _builtins.bool
    is_media_available: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        model: _builtins.str | None = ...,
        vendor: _builtins.str | None = ...,
        serial: _builtins.str | None = ...,
        is_ejectable: _builtins.bool | None = ...,
        size_bytes: _builtins.int | None = ...,
        media_type: _enums_pb2.EStorageDriveMediaType.ValueType | None = ...,
        is_unformatted: _builtins.bool | None = ...,
        adopt_stage: _enums_pb2.EStorageFormatStage.ValueType | None = ...,
        is_formattable: _builtins.bool | None = ...,
        is_media_available: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adopt_stage", b"adopt_stage", "id", b"id", "is_ejectable", b"is_ejectable", "is_formattable", b"is_formattable", "is_media_available", b"is_media_available", "is_unformatted", b"is_unformatted", "media_type", b"media_type", "model", b"model", "serial", b"serial", "size_bytes", b"size_bytes", "vendor", b"vendor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adopt_stage", b"adopt_stage", "id", b"id", "is_ejectable", b"is_ejectable", "is_formattable", b"is_formattable", "is_media_available", b"is_media_available", "is_unformatted", b"is_unformatted", "media_type", b"media_type", "model", b"model", "serial", b"serial", "size_bytes", b"size_bytes", "vendor", b"vendor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManagerDrive: _TypeAlias = CStorageDeviceManagerDrive  # noqa: Y015

@_typing.final
class CStorageDeviceManagerBlockDevice(_message.Message):

    ID_FIELD_NUMBER: _builtins.int
    DRIVE_ID_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    FRIENDLY_PATH_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    SIZE_BYTES_FIELD_NUMBER: _builtins.int
    IS_FORMATTABLE_FIELD_NUMBER: _builtins.int
    IS_READ_ONLY_FIELD_NUMBER: _builtins.int
    IS_ROOT_DEVICE_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    FILESYSTEM_TYPE_FIELD_NUMBER: _builtins.int
    MOUNT_PATHS_FIELD_NUMBER: _builtins.int
    IS_UNMOUNTING_FIELD_NUMBER: _builtins.int
    HAS_STEAM_LIBRARY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    drive_id: _builtins.int
    path: _builtins.str
    friendly_path: _builtins.str
    label: _builtins.str
    size_bytes: _builtins.int
    is_formattable: _builtins.bool
    is_read_only: _builtins.bool
    is_root_device: _builtins.bool
    content_type: _enums_pb2.EStorageBlockContentType.ValueType
    filesystem_type: _enums_pb2.EStorageBlockFileSystemType.ValueType
    is_unmounting: _builtins.bool
    has_steam_library: _builtins.bool
    @_builtins.property
    def mount_paths(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.int | None = ...,
        drive_id: _builtins.int | None = ...,
        path: _builtins.str | None = ...,
        friendly_path: _builtins.str | None = ...,
        label: _builtins.str | None = ...,
        size_bytes: _builtins.int | None = ...,
        is_formattable: _builtins.bool | None = ...,
        is_read_only: _builtins.bool | None = ...,
        is_root_device: _builtins.bool | None = ...,
        content_type: _enums_pb2.EStorageBlockContentType.ValueType | None = ...,
        filesystem_type: _enums_pb2.EStorageBlockFileSystemType.ValueType | None = ...,
        mount_paths: _abc.Iterable[_builtins.str] | None = ...,
        is_unmounting: _builtins.bool | None = ...,
        has_steam_library: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "drive_id", b"drive_id", "filesystem_type", b"filesystem_type", "friendly_path", b"friendly_path", "has_steam_library", b"has_steam_library", "id", b"id", "is_formattable", b"is_formattable", "is_read_only", b"is_read_only", "is_root_device", b"is_root_device", "is_unmounting", b"is_unmounting", "label", b"label", "path", b"path", "size_bytes", b"size_bytes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "drive_id", b"drive_id", "filesystem_type", b"filesystem_type", "friendly_path", b"friendly_path", "has_steam_library", b"has_steam_library", "id", b"id", "is_formattable", b"is_formattable", "is_read_only", b"is_read_only", "is_root_device", b"is_root_device", "is_unmounting", b"is_unmounting", "label", b"label", "mount_paths", b"mount_paths", "path", b"path", "size_bytes", b"size_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManagerBlockDevice: _TypeAlias = CStorageDeviceManagerBlockDevice  # noqa: Y015

@_typing.final
class CStorageDeviceManagerState(_message.Message):

    DRIVES_FIELD_NUMBER: _builtins.int
    BLOCK_DEVICES_FIELD_NUMBER: _builtins.int
    IS_UNMOUNT_SUPPORTED_FIELD_NUMBER: _builtins.int
    IS_TRIM_SUPPORTED_FIELD_NUMBER: _builtins.int
    IS_TRIM_RUNNING_FIELD_NUMBER: _builtins.int
    IS_ADOPT_SUPPORTED_FIELD_NUMBER: _builtins.int
    is_unmount_supported: _builtins.bool
    is_trim_supported: _builtins.bool
    is_trim_running: _builtins.bool
    is_adopt_supported: _builtins.bool
    @_builtins.property
    def drives(self) -> _containers.RepeatedCompositeFieldContainer[Global___CStorageDeviceManagerDrive]: ...
    @_builtins.property
    def block_devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___CStorageDeviceManagerBlockDevice]: ...
    def __init__(
        self,
        *,
        drives: _abc.Iterable[Global___CStorageDeviceManagerDrive] | None = ...,
        block_devices: _abc.Iterable[Global___CStorageDeviceManagerBlockDevice] | None = ...,
        is_unmount_supported: _builtins.bool | None = ...,
        is_trim_supported: _builtins.bool | None = ...,
        is_trim_running: _builtins.bool | None = ...,
        is_adopt_supported: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["is_adopt_supported", b"is_adopt_supported", "is_trim_running", b"is_trim_running", "is_trim_supported", b"is_trim_supported", "is_unmount_supported", b"is_unmount_supported"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_devices", b"block_devices", "drives", b"drives", "is_adopt_supported", b"is_adopt_supported", "is_trim_running", b"is_trim_running", "is_trim_supported", b"is_trim_supported", "is_unmount_supported", b"is_unmount_supported"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManagerState: _TypeAlias = CStorageDeviceManagerState  # noqa: Y015

@_typing.final
class CStorageDeviceManager_GetState_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_GetState_Request: _TypeAlias = CStorageDeviceManager_GetState_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_GetState_Response(_message.Message):

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___CStorageDeviceManagerState: ...
    def __init__(
        self,
        *,
        state: Global___CStorageDeviceManagerState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_GetState_Response: _TypeAlias = CStorageDeviceManager_GetState_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManager_StateChanged_Notification(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_StateChanged_Notification: _TypeAlias = CStorageDeviceManager_StateChanged_Notification  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Eject_Request(_message.Message):

    DRIVE_ID_FIELD_NUMBER: _builtins.int
    drive_id: _builtins.int
    def __init__(
        self,
        *,
        drive_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["drive_id", b"drive_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drive_id", b"drive_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Eject_Request: _TypeAlias = CStorageDeviceManager_Eject_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Eject_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Eject_Response: _TypeAlias = CStorageDeviceManager_Eject_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Adopt_Request(_message.Message):

    DRIVE_ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    VALIDATE_FIELD_NUMBER: _builtins.int
    drive_id: _builtins.int
    label: _builtins.str
    validate: _builtins.bool
    def __init__(
        self,
        *,
        drive_id: _builtins.int | None = ...,
        label: _builtins.str | None = ...,
        validate: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["drive_id", b"drive_id", "label", b"label", "validate", b"validate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["drive_id", b"drive_id", "label", b"label", "validate", b"validate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Adopt_Request: _TypeAlias = CStorageDeviceManager_Adopt_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Adopt_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Adopt_Response: _TypeAlias = CStorageDeviceManager_Adopt_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Format_Request(_message.Message):

    BLOCK_DEVICE_ID_FIELD_NUMBER: _builtins.int
    block_device_id: _builtins.int
    def __init__(
        self,
        *,
        block_device_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["block_device_id", b"block_device_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_device_id", b"block_device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Format_Request: _TypeAlias = CStorageDeviceManager_Format_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Format_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Format_Response: _TypeAlias = CStorageDeviceManager_Format_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Unmount_Request(_message.Message):

    BLOCK_DEVICE_ID_FIELD_NUMBER: _builtins.int
    block_device_id: _builtins.int
    def __init__(
        self,
        *,
        block_device_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["block_device_id", b"block_device_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_device_id", b"block_device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Unmount_Request: _TypeAlias = CStorageDeviceManager_Unmount_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_Unmount_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_Unmount_Response: _TypeAlias = CStorageDeviceManager_Unmount_Response  # noqa: Y015

@_typing.final
class CStorageDeviceManager_TrimAll_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_TrimAll_Request: _TypeAlias = CStorageDeviceManager_TrimAll_Request  # noqa: Y015

@_typing.final
class CStorageDeviceManager_TrimAll_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CStorageDeviceManager_TrimAll_Response: _TypeAlias = CStorageDeviceManager_TrimAll_Response  # noqa: Y015
