"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CGameNotes_UploadImage_Request(_message.Message):

    FILE_PREFIX_FIELD_NUMBER: _builtins.int
    MIME_TYPE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    file_prefix: _builtins.str
    mime_type: _builtins.str
    data: _builtins.bytes
    def __init__(
        self,
        *,
        file_prefix: _builtins.str | None = ...,
        mime_type: _builtins.str | None = ...,
        data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "file_prefix", b"file_prefix", "mime_type", b"mime_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "file_prefix", b"file_prefix", "mime_type", b"mime_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotes_UploadImage_Request: _TypeAlias = CGameNotes_UploadImage_Request  # noqa: Y015

@_typing.final
class CGameNotes_UploadImage_Response(_message.Message):

    FILENAME_FIELD_NUMBER: _builtins.int
    filename: _builtins.str
    def __init__(
        self,
        *,
        filename: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CGameNotes_UploadImage_Response: _TypeAlias = CGameNotes_UploadImage_Response  # noqa: Y015
