"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CTransportValidation_AppendToString_Request(_message.Message):

    APPEND_STRINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def append_strings(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        append_strings: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["append_strings", b"append_strings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_AppendToString_Request: _TypeAlias = CTransportValidation_AppendToString_Request  # noqa: Y015

@_typing.final
class CTransportValidation_AppendToString_Response(_message.Message):

    COMBINED_TEXT_FIELD_NUMBER: _builtins.int
    combined_text: _builtins.str
    def __init__(
        self,
        *,
        combined_text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["combined_text", b"combined_text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["combined_text", b"combined_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_AppendToString_Response: _TypeAlias = CTransportValidation_AppendToString_Response  # noqa: Y015

@_typing.final
class CTransportValidation_NotifyText_Notification(_message.Message):

    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_NotifyText_Notification: _TypeAlias = CTransportValidation_NotifyText_Notification  # noqa: Y015

@_typing.final
class CTransportValidation_NotifyNumber_Notification(_message.Message):

    NUMBER_FIELD_NUMBER: _builtins.int
    number: _builtins.int
    def __init__(
        self,
        *,
        number: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["number", b"number"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["number", b"number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_NotifyNumber_Notification: _TypeAlias = CTransportValidation_NotifyNumber_Notification  # noqa: Y015

@_typing.final
class CTransportValidation_GetLastNotifyNumber_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_GetLastNotifyNumber_Request: _TypeAlias = CTransportValidation_GetLastNotifyNumber_Request  # noqa: Y015

@_typing.final
class CTransportValidation_GetLastNotifyNumber_Response(_message.Message):

    LAST_NOTIFY_NUMBER_FIELD_NUMBER: _builtins.int
    last_notify_number: _builtins.int
    def __init__(
        self,
        *,
        last_notify_number: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_notify_number", b"last_notify_number"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["last_notify_number", b"last_notify_number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_GetLastNotifyNumber_Response: _TypeAlias = CTransportValidation_GetLastNotifyNumber_Response  # noqa: Y015

@_typing.final
class CTransportValidation_TriggerSyntheticEvents_Request(_message.Message):

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_TriggerSyntheticEvents_Request: _TypeAlias = CTransportValidation_TriggerSyntheticEvents_Request  # noqa: Y015

@_typing.final
class CTransportValidation_TriggerSyntheticEvents_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_TriggerSyntheticEvents_Response: _TypeAlias = CTransportValidation_TriggerSyntheticEvents_Response  # noqa: Y015

@_typing.final
class CTransportValidation_NotifySyntheticEvent_Notification(_message.Message):

    SEQUENCE_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    def __init__(
        self,
        *,
        sequence: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sequence", b"sequence"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sequence", b"sequence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_NotifySyntheticEvent_Notification: _TypeAlias = CTransportValidation_NotifySyntheticEvent_Notification  # noqa: Y015

@_typing.final
class CTransportValidation_TriggerDataRequest_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_TriggerDataRequest_Request: _TypeAlias = CTransportValidation_TriggerDataRequest_Request  # noqa: Y015

@_typing.final
class CTransportValidation_TriggerDataRequest_Response(_message.Message):

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.int
    def __init__(
        self,
        *,
        data: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_TriggerDataRequest_Response: _TypeAlias = CTransportValidation_TriggerDataRequest_Response  # noqa: Y015

@_typing.final
class CTransportValidation_DataRequest_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_DataRequest_Request: _TypeAlias = CTransportValidation_DataRequest_Request  # noqa: Y015

@_typing.final
class CTransportValidation_DataRequest_Response(_message.Message):

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.int
    def __init__(
        self,
        *,
        data: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_DataRequest_Response: _TypeAlias = CTransportValidation_DataRequest_Response  # noqa: Y015

@_typing.final
class CTransportValidation_AddNumbers_Request(_message.Message):

    NUMBERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def numbers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        numbers: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["numbers", b"numbers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_AddNumbers_Request: _TypeAlias = CTransportValidation_AddNumbers_Request  # noqa: Y015

@_typing.final
class CTransportValidation_AddNumbers_Response(_message.Message):

    ACCUMULATED_FIELD_NUMBER: _builtins.int
    accumulated: _builtins.int
    def __init__(
        self,
        *,
        accumulated: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accumulated", b"accumulated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accumulated", b"accumulated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_AddNumbers_Response: _TypeAlias = CTransportValidation_AddNumbers_Response  # noqa: Y015

@_typing.final
class CTransportValidation_CountOrderedBytes_Request(_message.Message):

    ORDERED_BYTES_FIELD_NUMBER: _builtins.int
    ordered_bytes: _builtins.bytes
    def __init__(
        self,
        *,
        ordered_bytes: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ordered_bytes", b"ordered_bytes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ordered_bytes", b"ordered_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_CountOrderedBytes_Request: _TypeAlias = CTransportValidation_CountOrderedBytes_Request  # noqa: Y015

@_typing.final
class CTransportValidation_CountOrderedBytes_Response(_message.Message):

    BYTE_COUNT_FIELD_NUMBER: _builtins.int
    byte_count: _builtins.int
    def __init__(
        self,
        *,
        byte_count: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["byte_count", b"byte_count"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["byte_count", b"byte_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_CountOrderedBytes_Response: _TypeAlias = CTransportValidation_CountOrderedBytes_Response  # noqa: Y015

@_typing.final
class CTransportValidation_ThreadedCount_Request(_message.Message):

    START_NUM_FIELD_NUMBER: _builtins.int
    END_NUM_FIELD_NUMBER: _builtins.int
    start_num: _builtins.int
    end_num: _builtins.int
    def __init__(
        self,
        *,
        start_num: _builtins.int | None = ...,
        end_num: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["end_num", b"end_num", "start_num", b"start_num"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_num", b"end_num", "start_num", b"start_num"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_ThreadedCount_Request: _TypeAlias = CTransportValidation_ThreadedCount_Request  # noqa: Y015

@_typing.final
class CTransportValidation_ThreadedCount_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_ThreadedCount_Response: _TypeAlias = CTransportValidation_ThreadedCount_Response  # noqa: Y015

@_typing.final
class CTransportValidation_NotifyCount_Notification(_message.Message):

    NUM_FIELD_NUMBER: _builtins.int
    num: _builtins.int
    def __init__(
        self,
        *,
        num: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["num", b"num"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["num", b"num"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_NotifyCount_Notification: _TypeAlias = CTransportValidation_NotifyCount_Notification  # noqa: Y015

@_typing.final
class CTransportValidation_RequestInvalidBool_Request(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_RequestInvalidBool_Request: _TypeAlias = CTransportValidation_RequestInvalidBool_Request  # noqa: Y015

@_typing.final
class CTransportValidation_RequestInvalidBool_Response(_message.Message):

    BEFORE_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    AFTER_FIELD_NUMBER: _builtins.int
    before: _builtins.int
    output: _builtins.bool
    after: _builtins.int
    def __init__(
        self,
        *,
        before: _builtins.int | None = ...,
        output: _builtins.bool | None = ...,
        after: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before", "output", b"output"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before", "output", b"output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_RequestInvalidBool_Response: _TypeAlias = CTransportValidation_RequestInvalidBool_Response  # noqa: Y015

@_typing.final
class CTransportValidation_GetLargeResponse_Request(_message.Message):

    DATA_SIZE_FIELD_NUMBER: _builtins.int
    data_size: _builtins.int
    def __init__(
        self,
        *,
        data_size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data_size", b"data_size"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_size", b"data_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_GetLargeResponse_Request: _TypeAlias = CTransportValidation_GetLargeResponse_Request  # noqa: Y015

@_typing.final
class CTransportValidation_GetLargeResponse_Response(_message.Message):

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_GetLargeResponse_Response: _TypeAlias = CTransportValidation_GetLargeResponse_Response  # noqa: Y015

@_typing.final
class CTransportValidation_RequestLargeNotification_Request(_message.Message):

    DATA_SIZE_FIELD_NUMBER: _builtins.int
    data_size: _builtins.int
    def __init__(
        self,
        *,
        data_size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data_size", b"data_size"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_size", b"data_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_RequestLargeNotification_Request: _TypeAlias = CTransportValidation_RequestLargeNotification_Request  # noqa: Y015

@_typing.final
class CTransportValidation_RequestLargeNotification_Response(_message.Message):

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_RequestLargeNotification_Response: _TypeAlias = CTransportValidation_RequestLargeNotification_Response  # noqa: Y015

@_typing.final
class CTransportValidation_NotifyLarge_Notification(_message.Message):

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidation_NotifyLarge_Notification: _TypeAlias = CTransportValidation_NotifyLarge_Notification  # noqa: Y015

@_typing.final
class CTransportValidationClient_AddNumbers_Request(_message.Message):

    NUMBERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def numbers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        numbers: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["numbers", b"numbers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidationClient_AddNumbers_Request: _TypeAlias = CTransportValidationClient_AddNumbers_Request  # noqa: Y015

@_typing.final
class CTransportValidationClient_AddNumbers_Response(_message.Message):

    ACCUMULATED_FIELD_NUMBER: _builtins.int
    accumulated: _builtins.int
    def __init__(
        self,
        *,
        accumulated: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["accumulated", b"accumulated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accumulated", b"accumulated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CTransportValidationClient_AddNumbers_Response: _TypeAlias = CTransportValidationClient_AddNumbers_Response  # noqa: Y015
